### ISSUE TITLE
a way to skip the long migration of sqllite galaxy database when planemo test or serve

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/planemo#1012]
Hi,

Is there any tip to skip the long migration of the sqllite galaxy database which is run when using the `planemo serve` or `planemo test` command ?
```
INFO  [galaxy.model.migrate.check] Migrating 0 -> 1...
...
INFO  [galaxy.model.migrate.check] Migrating 153 -> 154
```
In my current setting, even using a local galaxy repo, I have to wait and to wait again each time I test the development of a tool. However, I may remember (but can't do it actually) a configuration where the migration was really quick, maybe only the few last scheme versions. Maybe it is just a dream ?

**Comment by mvdbeek** [comment]
Which version of planemo are you using and what command are you running ? Normally the migrations are completely skipped with modern planemo and Galaxy.

**Comment by drosofff** [comment]
Hi @mvdbeek 
Thanks for the quick answer !
`planemo, version 0.70.0`

```
chris@plastisipi:~/tools-artbio/tools/sambamba$ cat ~/.planemo.yml
## Planemo Global Configuration File.
## Everything in this file is completely optional - these values can all be
## configured via command line options for the corresponding commands.

## Specify a default galaxy_root for test and server commands here.
galaxy_root: /home/chris/galaxy-planemo/galaxy/
```
and
```
chris@plastisipi:~/galaxy-planemo/galaxy$ git status
On branch release_19.05
Your branch is up-to-date with 'origin/release_19.05'.
```

Now, I see this in the start log for `planemo test --conda_dependency_resolution --conda_auto_install --conda_channels iuc,conda-forge,bioconda,defaults --job_output_files ./newtests . `

```
The Galaxy client build is being skipped due to the SKIP_CLIENT_BUILD environment variable.
Activating virtualenv at .venv
2020-05-21 13:28:30,422 WARNI [galaxy.config] Config file (config/user_preferences_extra_conf.yml) could not be found or is malformed.
2020-05-21 13:28:30,610 INFO  [galaxy.queue_worker] Initializing main Galaxy Queue Worker on sqlalchemy+sqlite:////tmp/tmpsodu2dip/galaxy.sqlite?isolation_level=IMMEDIATE
2020-05-21 13:28:30,666 INFO  [galaxy.model.migrate.check] Creating database for URI [sqlite:////tmp/tmpsodu2dip/galaxy.sqlite?isolation_level=IMMEDIATE]
2020-05-21 13:28:30,698 INFO  [galaxy.model.migrate.check] Migrating 0 -> 1...
2020-05-21 13:28:30,861 INFO  [galaxy.model.migrate.check]
2020-05-21 13:28:30,862 INFO  [galaxy.model.migrate.check] Migrating 1 -> 2...
```

**Comment by mvdbeek** [comment]
Can you try this against a more recent Galaxy version ? You should be able to comment `galaxy_root ` which should use the current master branch. For going directly to the most recent database schema you'd need at least 19.09. For older releases you would need to use an older version of planemo (0.62.1 should use a pre-seeded database).

**Comment by drosofff** [comment]
Ah !!! so it was not a dream ! my memory was real...

Thank marius, I install a fresh local planemo galaxy immediately

**Comment by drosofff** [comment]
👍 Thank you, it worked !
