### ISSUE TITLE
Specifying input parameters for workflow testing

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/planemo#1019]
Hello,

To specify an input file for workflow testing, a section like this has to be included in the YAML file 
(I also saw an example with `class: Collection`):

```
mutant_R1:
  class: File
  path: mutant_R1.fastq
```

What's the equivalent for an input parameter?

**Comment by jmchilton** [comment]
I was hoping this would sort of just work - but it doesn't and I have a test case for confirming that https://github.com/galaxyproject/planemo/pull/1057. I'll try to make some progress on this - it is clearly a priority since we're on both a workflow testing push and workflow parameter push 😅.

**Comment by simonbray** [comment]
Would be great, thanks a lot!

**Comment by jmchilton** [comment]
I think this should be fixed by https://github.com/galaxyproject/planemo/pull/1057. I'll try to get another Planemo release published this week.
