### ISSUE TITLE
Unpin cwltool version

### ISSUE THREAD

**Issue by TMiguelT** [galaxyproject/planemo#1033]
Hi. Any idea why this needs to be pinned? I fear it may in part be causing my dependency woes.

https://github.com/galaxyproject/planemo/blob/deccc48cb15ea9e670f1dbbc0d6dd1e96fe96418/requirements.txt#L6

**Comment by mvdbeek** [comment]
I believe that was to not break python 2, so your PR looks good to me!

**Comment by jmchilton** [comment]
There was some fallout (I needed to drop support for Python 2 in gxformat2 for instance) but I think overall this was a good change pushing us forward. I'm sure we'll have to re-pin at some point because those interfaces are always breaking on us but good to be caught up for sure! Thanks so much.

**Comment by TMiguelT** [comment]
I would really rather it not be pinned, I suppose a range could be okay, but in general it's very unhelpful for packages that want to use `planemo` as a dependency. My references for not pinning are [here](https://pipenv-fork.readthedocs.io/en/latest/advanced.html#pipfile-vs-setup-py), [here](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires). In my case, when I installed `planemo` and `cwl-utils`, the dependencies were unsatisfiable since there was no intersection between the two ranges.
