### ISSUE TITLE
Planemo should not call run_tests.sh

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#1035]
We've packaged up so much - the engine based approach should be very close to workable at this point. Just need to take time to work through it I think - handling details like updating test data. 

This would let us revert #988

**Comment by mvdbeek** [comment]
Won't symlinks outside of a docker mountpoint always need to be resolved or copied to something within the mountpoint ? 
I guess I don't understand what the engine approach would change in that regard ?

**Comment by mvdbeek** [comment]
To clarify, it'll help for inputs and outputs, but not if the referred tool script itself is a symlink. We don't have a ton of tools doing that fortunately.
