### ISSUE TITLE
Bug with python version instanciated by virtualenv

### ISSUE THREAD

**Issue by ecamenen** [galaxyproject/planemo#1039]
Hi. I took over a previous project of a tool developed under Planemo which was working and now doesn't work anymore under Travis when I restarted exactly the same build (https://travis-ci.org/github/ecamenen/rgcca-galaxy/builds/669356177).
![error_virtualenv](https://user-images.githubusercontent.com/27341903/88526092-c6f66980-cffb-11ea-82b4-0af05416d593.png)
I re-installed everything locally, under Conda (0.70.0) or Pip, on variouscomputers with no results whereas everything was working before. Less than two months ago, it just show a depreceted message, now it raises an error with the Python version. 
![depreceted_virtualenv](https://user-images.githubusercontent.com/27341903/88526093-c78f0000-cffb-11ea-828f-6ef6aa79029e.png)
In any case, the python version is >=3.5, but it looks like virtualenv is forcing 2.7. So I installed the correct python, then changed the path of the symbolic link of virtualenv called by the installation. Apparently, I still have to debug the pip which is no longer recognized.
Any idea where the problem might come from?

**Comment by jmchilton** [comment]
The "master" branch of Galaxy was recently updated from 20.01 to 20.5 - this might be why things broke for the same build. You may want to add ``--galaxy_branch 20.01`` to your Planemo CLI invocation.

**Comment by ecamenen** [comment]
Perfect ! Thank you
