### ISSUE TITLE
using planemo test --update_test_data does produce the output files but the test fails  

### ISSUE THREAD

**Issue by fubar2** [galaxyproject/planemo#1070]
Has #846 come back?

I see the same reported behaviour with a fresh Galaxy dev checkout and planemo 0.72.0.dev0

When I remove a test output and run test --update_test_data, planemo _**does**_ correctly recreate the missing output but the test fails with:

`Test file (outfile_sample) is missing. If you use planemo try --update_test_data to generate one.`

It is indeed **not** really passing the test if there's a missing output so this needs some thought.

Perhaps planemo should have an unforgiving "test" that does exactly that and fails if it fails....as distinct from a different command to execute the specified test and generate fresh appropriate outputs, then test properly? Once generated, those fresh outputs are then ideal for the *real* pass/fail test. In generating them there has certainly been a test, but it seems odd to report that process as successful - I think I'll want to re-test with the generated output before declaring victory.

Here's the traceback:

`
FAIL: ( pyrevargparse ) > Test-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ross/galaxy/test/functional/test_toolbox.py", line 99, in test_tool
    self.do_it(tool_version=tool_version, test_index=test_index)
  File "/home/ross/galaxy/test/functional/test_toolbox.py", line 36, in do_it
    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)
  File "/home/ross/galaxy/lib/galaxy/tool_util/verify/interactor.py", line 834, in verify_tool
    raise e
  File "/home/ross/galaxy/lib/galaxy/tool_util/verify/interactor.py", line 830, in verify_tool
    job_stdio = _verify_outputs(testdef, test_history, jobs, tool_id, data_list, data_collection_list, galaxy_interactor, quiet=quiet)
  File "/home/ross/galaxy/lib/galaxy/tool_util/verify/interactor.py", line 1005, in _verify_outputs
    raise JobOutputsError(found_exceptions, job_stdio)
galaxy.tool_util.verify.interactor.JobOutputsError: Test file (outfile_sample) is missing. If you use planemo try --update_test_data to generate one.
`

**Comment by simonbray** [comment]
Hi @fubar2, I always assumed this was intended behaviour, i.e. 1) `planemo test --update_test_data` needs to be run to regenerate the data, but the test will fail (because the results are different to the original test data) and then 2) `planemo test` is run to check the tests are passing with the new files.

In the bug you mentioned the files were not being created at all.

**Comment by fubar2** [comment]
`In the bug you mentioned the files were not being created at all.`

Oh, but they are being created - I use the flag to replace whatever is in the test-data folder and use them in the next run and it passes. It's not unexpected and not unreasonable that it fails, but the error message could perhaps be more informative particularly since I've set that flag. However, my suggestion stands - a 'generate test outputs' mode makes sense to me but I can easily work around this - it's not important.

**Comment by simonbray** [comment]
> It's not unexpected and not unreasonable that it fails, but the error message could perhaps be more informative particularly since I've set that flag.

Yep, I completely agree, the message could definitely be improved.
