### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#108]
Planemo needs a logo.

**Comment by carlfeberhard** [comment]
![planemo](https://cloud.githubusercontent.com/assets/5102959/7205339/9aab07fa-e4f6-11e4-94ed-9a374a59ac95.png)

(2 alts)

**Comment by erasche** [comment]
Oooh. Very sexy! :+1:

**Comment by martenson** [comment]
The bottom one is my favorite, neat!

**Comment by jmchilton** [comment]
Love both these, also particularly love the bottom one. @jxtx commented that it would be great if there was some motif that connected this logo with the Galaxy logo. @carlfeberhard said "Do whatcha want with them".

**Comment by erasche** [comment]
You could use the top and overlay the galaxy three bars in such a way that would imply planetary rotation about an axis. (again, out of office today so not replying with a mock up)

**Comment by martenson** [comment]
Some ideas from Petr Kadlec (who designed the new Galaxy logo, http://puradesign.cz/en):
![planemo-logo](https://cloud.githubusercontent.com/assets/1814954/7381608/2e71af2c-edd3-11e4-8e08-118376b1f4b8.png)

**Comment by bgruening** [comment]
First one :)

**Comment by erasche** [comment]
Yeah, first one for that set.

**Comment by jmchilton** [comment]
Very nice - they are all very nice. My preference is for the third - it feels sleeker (E) and astronomical (O). Happy to adopt the first though if that is where the consensus is.

Current Votes: 
+ 2 on first of these
+ 1 on the third

**Comment by martenson** [comment]
What about the third one but with thicker 'galaxy alingments' (like in the first one). The feel a bit thin. However having two graphical elements in textual logo might be too much, not sure :/

**Comment by erasche** [comment]
Well... if you're going to offer me the chance to be picky about typography....

The size of the bars from the galaxy logo *usually should* be the same weight as the width of the font (since it's a sans font and everything is pretty consistent), however, they feel much too light since they don't visually occupy the same space as an N/M that surround them (closer to the visual area of the L), thus you need them to be a wee bit heavier, like in the first. Additionally, the thin options feel too thin, like they're getting away from the Galaxy logo.

Absolutely use the astronomical-O from the third.

**Comment by jmchilton** [comment]
Ekkk.. opened up Gimp - that is never good - let me know if I messed this up or if I am not allowed to modify the image.

![replace_o](https://cloud.githubusercontent.com/assets/216771/7382934/a8e9b7a2-ede4-11e4-800e-6f841d2dcbed.png)

I prefer this 1. better than the previous 1 - I may still on balance prefer the slim E - but I am happy to lose that - both are really, really great.

**Comment by erasche** [comment]
While I'm still being picky...those hard corners on the M suck. But otherwise, # 1 looks much better.

**Comment by dannon** [comment]
+1 vote for #3

**Comment by petrkadlec** [comment]
I played with the thickness of the bars furthermore.. And the first one has also the corners of letters made a little softer.
![planemo-logo2](https://cloud.githubusercontent.com/assets/12165223/7385754/6cfc7d3a-ee4b-11e4-8d3a-78109debb83e.png)

**Comment by erasche** [comment]
E from 2, lettering from 1, looks great @petrkadlec

**Comment by martenson** [comment]
+1 on the second in the last batch

**Comment by blankenberg** [comment]
Also, +1 on the second in the last batch.

**Comment by jmchilton** [comment]
Another vote from me for the second one. Seems like the majority opinion so I pushed it out into the README. Thanks a bunch all!
