### ISSUE TITLE
Allow existing dataset / dataset collection ids in jobs for planemo run

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/planemo#1080]

**Comment by simonbray** [comment]
Seems to be a similar issue to https://github.com/galaxyproject/planemo/issues/1073

**Comment by mvdbeek** [comment]
I

**Comment by simonbray** [comment]
@mvdbeek what time scale did you want to do this on? I was hoping to take a look at it in the next week or two.

**Comment by mvdbeek** [comment]
I'm gonna poke at it later today or tomorrow, I'll let you know how that's going.

**Comment by simonbray** [comment]
What I did so far was in this commit (https://github.com/galaxyproject/planemo/pull/1076/commits/5929da8245887879f0260334c142cb262faecbcc), which allows executing a workflow using just the workflow ID rather than a local JSON/YAML file.

**Comment by simonbray** [comment]
@mvdbeek, just to let you know, I started to work on this here: https://github.com/galaxyproject/galaxy/compare/dev...simonbray:staging-with-id

**Comment by mvdbeek** [comment]
Awesome, I've gloriously overestimated the time I have available 😅

**Comment by simonbray** [comment]
Haha no worries. I'll try and make a PR in the next couple of days.
