### ISSUE TITLE
Create upload_data command

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/planemo#1104]
> Can you please create a planemo issue about this one? I guess a planemo upload_data command might be useful that returns the IDs?
>
> _Originally posted by @bgruening in https://github.com/galaxyproject/planemo/pull/1102#discussion_r535632480_

I guess this command would take a workflow and job file and:

- upload data
- get dataset IDs
- write a new job file, replacing all `path`s with `galaxy_id`s

**Comment by jmchilton** [comment]
That sounds cool I think!
