### ISSUE TITLE
Planemo run failing with --engine docker_galaxy

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/planemo#1107]
I had some issue running

```
$ planemo run wf.ga wf-job.yml --engine docker_galaxy
```

which failed at https://github.com/galaxyproject/planemo/blob/master/planemo/galaxy/workflows.py#L56, i.e. when trying to install toolshed repositories.

I don't know much about the dockerized galaxy, but I guess this installation step should be skipped, aren't you supposed to provide a list of tools for installation in the `docker run` command? Or is there some special case where you might want to do this installation?

After appending `--ignore_dependency_problems` it works as expected.

**Comment by fubar2** [comment]
Could this be related to #1098 ?

**Comment by mvdbeek** [comment]
I think docker galaxy is not actively maintained, and `--biocontainers` is the much better option.
