### ISSUE TITLE
ZeroDivisionError on master branch

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/planemo#1117]
Planemo test on the (`master` branch) fails for the mock test in the setup job of the IUC tool test workflow:

```
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/planemo/reports/report_markdown.tpl", line 14, in top-level template code
    <div class="progress-bar progress-bar-success" style="width: {{ (state.success / raw_data.results.total) * 100 }}%" aria-valuenow="{{ state.success }}" aria-valuemin="0" aria-valuemax="{{ raw_data.results.total }}" data-toggle="tooltip" title="{{state.success}} Passed">
```

Odd is also that `--test_output_markdown` is not used.

**Comment by simonbray** [comment]
I also encountered this error when the `*-tests.yml` file was missing. Maybe this is also the case for you?

**Comment by bernt-matthias** [comment]
I guess it's kind of similar. In the IUC workflow we do a mock `planemo test` run with an empty tool xml file in order to initialize the `.planemo` dir which is than cached for later jobs.
