### ISSUE TITLE
GCC Abstract

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#112]
Like #109 but for the GCC :).  We merged some pretty different concepts into a single abstract for the BOSC because there were already going to be multiple Galaxy talks - at the GCC it might make sense to separate things out more.

**Comment by bgruening** [comment]
@jmchilton any ideas? How you would like to structure it? We need to hand it in tomorrow, right?

**Comment by jmchilton** [comment]
WIP @ https://docs.google.com/document/d/1M2fgN0mCDujH2QqCJVKDb_OnORCMXpZG3u3YhR3-TtI/edit?usp=sharing

@bgruening @erasche @kellrott let me know if you don't want your names on it - if anyone else outside devteam does want your name on it let me know.

**Comment by bgruening** [comment]
@jmchilton thanks! This is a nice writeup!

**Comment by jmchilton** [comment]
Submitted earlier in the week.
