### ISSUE TITLE
New planemo casts __tool_directory__ to a temp folder under .planemo in tool_scripts.sh

### ISSUE THREAD

**Issue by qiagu** [galaxyproject/planemo#1132]
Is there a benefit for doing this?
An issue of this change is that the casted files will be deleted no matter whether the `--no_cleanup` is enabled or not. As a result, the temp files become less useful for debugging or other purpose.

**Comment by mvdbeek** [comment]
We'll have to dereference symlinks so we can use docker is the answer. If we get around to a pulsar client we can undo that change.
