### ISSUE TITLE
Git as a planemo dependency

### ISSUE THREAD

**Issue by fubar2** [galaxyproject/planemo#1162]
After wrestling with strange biocontainer failures, I finally figured out they were caused by git not currently being in requirements.txt
although it is needed in cmd_clone, cmd_pull, cmd_travis_init commands, galaxy/config.py and options.py and of course all the git modules.

Does it make sense to add it as a requirement?

Trivial work around for biocontainers is to include it.

**Comment by nsoranzo** [comment]
AFAIK `requirements.txt` can be used only to specify Python dependencies, not system packages like git.

**Comment by fubar2** [comment]
Ah! 
Thanks @nsoranzo - closing this.
