### ISSUE TITLE
Can't run test command in planemo 0.74.2

### ISSUE THREAD

**Issue by simleo** [galaxyproject/planemo#1208]
```console
[simleo@neuron:tmp]$ python3 -m venv venv
[simleo@neuron:tmp]$ source venv/bin/activate
(venv) [simleo@neuron:tmp]$ rm ~/.cache/pip -rf
(venv) [simleo@neuron:tmp]$ pip install --upgrade pip
(venv) [simleo@neuron:tmp]$ pip install planemo==0.74.2
(venv) [simleo@neuron:tmp]$ planemo test
Problem loading command test, exception cannot import name 'galaxy_requests_post'
Usage: planemo [OPTIONS] COMMAND [ARGS]...
Try 'planemo --help' for help.

Error: No such command 'test'.
```

**Comment by davelopez** [comment]
Hi, is there any particular reason to use that version? I think this issue was resolved here https://github.com/galaxyproject/planemo/pull/1201 so using a recent version should fix it.
Sorry for the inconvenience!

**Comment by simleo** [comment]
> Hi, is there any particular reason to use that version?

The reason is that versions `>=0.74.3` are affected by #1160, and I'm using the `docker_galaxy` engine.

**Comment by mvdbeek** [comment]
Not to say we're not going to fix `docker)engine`, but I'd strongly suggest `--biocontainers` instead of the `docker_galaxy` engine, that allows using docker containers for dependencies.

**Comment by simleo** [comment]
Thanks @mvdbeek, I switched to `--biocontainers`. However, I ran into another problem: the automated Galaxy installation broke with a `cryptography` installation error from pip:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-u13bmqsr/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
```

As explained [here](https://github.com/pyca/cryptography/issues/5753), this is due to pip being to old. The problem seems to be in Galaxy, in `scripts/common_startup.sh`:

```bash
if [ $REPLACE_PIP -eq 1 ]; then
    python -m pip install 'pip>=8.1'
fi
```

The above command does not have `--upgrade`, so if pip is `>= 8.1` it does not get updated. However, 8.1 is not enough.

To work around the problem, I had to do this before running `planemo test`:

```
rm ~/.planemo/gx_venv* -rf
python -m venv ~/.planemo/gx_venv_3
source ~/.planemo/gx_venv_3/bin/activate
pip install --upgrade pip
```

**Comment by nsoranzo** [comment]
@simleo With at least pip 19.0, compiling `cryptography` [shouldn't be needed](https://cryptography.io/en/latest/faq/#why-are-there-no-wheels-for-my-python3-x-version), but I have a different error if I try to install it with pip 18.1. Can you please double check that pip 19.0 is enough to fix this for you as well?

**Comment by simleo** [comment]
@nsoranzo yes, pip 19.0 is enough:

```
Collecting cryptography==3.4.7 (from -r ./lib/galaxy/dependencies/dev-requirements.txt (line 50))
  Downloading https://files.pythonhosted.org/packages/16/9d/aa507ddc5dc630b499d4905000b17448a969f0cdcdb9bbc2fe5e369a5fad/cryptography-3.4.7-cp36-abi3-manylinux2010_x86_64.whl (3.1MB)
    100% |████████████████████████████████| 3.1MB 10.9MB/s 
```

**Comment by simleo** [comment]
Also confirming that 18.1 is _not_ enough. The error message is more verbose, but it boils down to this line:

```
    error: can't find Rust compiler
```

So I guess you want to bump pip's min version to 19.0 in `common_startup.sh`.

**Comment by nsoranzo** [comment]
Great, thanks @simleo , PR incoming!

**Comment by nsoranzo** [comment]
The required minimum version of `pip` has been increased to 19.0 in Galaxy `release_21.05` onwards, anything left to fix here?

**Comment by simleo** [comment]
> anything left to fix here?

Well, that depends on whether you want to fix older versions of Planemo. That would require re-adding `galaxy_requests_post` to `galaxy-tool-util`, I guess. In my case, I was able to sidestep the issue as described.

**Comment by simleo** [comment]
Thanks again everyone BTW!

**Comment by mvdbeek** [comment]
> Well, that depends on whether you want to fix older versions of Planemo. That would require re-adding `galaxy_requests_post` to `galaxy-tool-util`, I guess. In my case, I was able to sidestep the issue as described.

I think the right solution for this would be merging https://github.com/galaxyproject/planemo/pull/1203 and producing locked releases for planemo (the application) and creating "lightly" pinned releases for planemo-lib

**Comment by nsoranzo** [comment]
> Well, that depends on whether you want to fix older versions of Planemo. That would require re-adding galaxy_requests_post to galaxy-tool-util, I guess.

In that case, the solution would more likely be to pin galaxy-tool-util, but I don't think we have a goal of fixing older releases. I agree with @mvdbeek's suggestion any way.

So, closing this.
