### ISSUE TITLE
planemo 0.74.9 - test fails on diff, despite <assert_contents> 

### ISSUE THREAD

**Issue by TomHarrop** [galaxyproject/planemo#1218]
I've got three tests that all use `<assert_contents>` to check the file size as follows:

```.xml
<output name="out_hal" file="evolverMammals.hal" >
    <assert_contents>
        <has_size value="1611326" delta="200000" />
    </assert_contents>
</output>
```
The three tests are all failing with
```
Output out_hal:  different than expected, difference (using diff):
( /tmp/tmphox04cn0evolverMammals.hal v. /tmp/tmprhfgyghbevolverMammals.hal )
Binary data detected, not displaying diff
```

The outputs *are* different. I am not expecting the files to be diffed, since I included an `<assert_contents>`. I'm relatively new to planemo & galaxy so I may be misunderstanding the docs!

I'm on planemo 0.74.9, python 3.9.7 on ubuntu.

I'm testing as follows:

```.bash
planemo test \
    --job_output_files job_output_files \
    --job_config_file /path/to/job_conf.xml \
    cactus_cactus.xml
```

The wrapper I'm working on is here: https://github.com/usegalaxy-au/galaxy-local-tools/blob/master/tools/cactus/cactus_cactus.xml 

Thanks!

**Comment by nsoranzo** [comment]
If you don't want to compare against `evolverMammals.hal` you need to remove ` file="evolverMammals.hal"` from the `<output />` element. You can also remove the `evolverMammals.hal` itself.
