### ISSUE TITLE
Cache eggs between --install_galaxy calls.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#123]
See discussion on #49.

**Comment by natefoo** [comment]
What you mentioned in #49 about caching should be fine. You could either force `$GALAXY_EGGS_PATH` to be set and point at some cache directory, or write a bit of magic to check some cache directory to install from there into Galaxy's standard eggs directory.

**Comment by jmchilton** [comment]
Happens as of https://github.com/galaxyproject/planemo/commit/56d46d4a94bfcbd9f44748e1b50b221148b54eb9. Seems to work well.
