### ISSUE TITLE
sanitizer(s) throw error(s) when linting XML

### ISSUE THREAD

**Issue by adRn-s** [galaxyproject/planemo#1233]
Hi,

I'm having a bit of trouble with a CI pipeline because `planemo` throws an error when it encounters [these](https://docs.galaxyproject.org/en/master/dev/schema.html#tool-inputs-param-sanitizer).

I wasn't able  to find any mention to **sanitizers** in other issues at the repo nor in the documentation. I guess not many people were using this bit of the XML spec... still, could we have them included in `planemo`? Thanks in advance for your answers!

**Comment by mvdbeek** [comment]
You'll have to provide an example that fails. We have a lot of tools using sanitizers that we lint with planemo.

**Comment by adRn-s** [comment]
Oh, my bad. I just got confused because of the output message:

```
.. ERROR: Invalid XML found in file: plotHeatmap.xml. Errors [/tmp/tmpwl8e1vpl:189:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'sanitizer': This element is not expected.]
Failed linting
```

But after a careful look, the problem was with having a closed param, like `<param ... /> <sanitizer> ... <sanitizer/>`. File linting now validates my XML.

Thanks!
