### ISSUE TITLE
Planemo lint not working with empty xml due to attribute xpath not found in Python 3.7.6.

### ISSUE THREAD

**Issue by diegogomezca** [galaxyproject/planemo#1240]
The following shows the error:

"...">planemo lint .
Error loading tool with path "... .xml"
Traceback (most recent call last):
  File "...\anaconda3\lib\site-packages\galaxy\tool_util\loader_directory.py", line 113, in _load_tools_from_path
    tool_element = loader_func(possible_tool_file)
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'xpath'
Could not lint "... xml" due to malformed xml.

**Comment by simonbray** [comment]
But an empty file is not valid XML (I hope?). So the `malformed xml` message is accurate.

What would you expect to see here?

**Comment by diegogomezca** [comment]
I was trying with a well-formed xml but I had an error with the library versions. I have updated them and it is working properly. Thanks!
