### ISSUE TITLE
Install local tools on existing galaxy instance

### ISSUE THREAD

**Issue by bvalot** [galaxyproject/planemo#1243]
Hello,

I have developed new tools for galaxy using planemo. I lint and test it successfully.
Is there a way to install it on my local galaxy instance for production using planemo? 

Thanks in advance
Benoit

**Comment by mvdbeek** [comment]
Hi @bvalot, for production use we'd recommend pushing the tools to a github repository and handling the uploads to the tool shed with planemo-ci-action. You can use https://github.com/galaxyproject/galaxy-tool-repository-template as a template for this, see https://training.galaxyproject.org/training-material/topics/dev/tutorials/tool-from-scratch/tutorial.html#publishing-galaxy-tools for more instructions.#1242 

@bgruening's recommendation should only be used for development or if you can't publish your tools for some reason. Pushing these tools to the tool shed ensures that other users can reproduce your analysis on other Galaxy servers.

**Comment by mvdbeek** [comment]
If you fork https://github.com/galaxyproject/galaxy-tool-repository-template you only need to follow the setup instructions in https://github.com/galaxyproject/galaxy-tool-repository-template#setup. Tools on the main branch will then be uploaded by a github workflow. Internally that uses `planemo shed_update --shed_target "$SHED_TARGET" --shed_key "$SHED_KEY" --force_repository_creation "$DIR"`.

**Comment by bvalot** [comment]
Ok. So I try to do it [here](https://github.com/bvalot/galaxy).
But I don't understand the last step with the PAT secret?

Furthemore, is there other think to do to be able to install this tools on my galaxy instance?

**Comment by mvdbeek** [comment]
The PAT is only needed if you want to run slash commands (like `/run-all-tool-tests branch=a_non_default_branch`).
The code check is failing on your python files currently: https://github.com/bvalot/galaxy/runs/6863802328?check_suite_focus=true. 

One easy fix is to run [black](https://black.readthedocs.io/en/stable/getting_started.html) on your files. That should fix the majority of the issues, then run [flake8](https://flake8.pycqa.org/en/latest/#using-flake8) and fix the remaining complaints.

If all the checks pass then the deploy action (https://github.com/bvalot/galaxy/runs/6863950400?check_suite_focus=true, which will be skipped if any of the tests fail) will upload your tools to the tool shed, and then you can install the tools on your Galaxy instance as normal.

**Comment by bvalot** [comment]
Thanks. 

I make black/flake8 syntax correction, verify planemo test and push to github.
Let's see!

**Comment by bvalot** [comment]
flake8 check pass. Now it seems to have a problem with the push/pr

**Comment by bvalot** [comment]
Now I have some problems with test of pyMLST tools. It works with planemo on venv but not in docker

**Comment by mvdbeek** [comment]
Yep, this is in the test output:
```
Job in error state.. tool_id: clamlst_search_wrapper, exit_code: 1, stderr: sed: unsupported command
```
what you want to do is to include `sed` in your requirements. Not all sed versions include the same featureset.

**Comment by bvalot** [comment]
Ok thanks. That correct 2 failed on 4.

But I don't understand whats wrong in this case.

**Comment by mvdbeek** [comment]
Did you see the test reports on the summary page (https://github.com/bvalot/galaxy/actions/runs/2500329542) ?
For the first one i see
![Screenshot 2022-06-15 at 10 30 35](https://user-images.githubusercontent.com/6804901/173781349-fb4f6f04-5f29-403d-981c-78b693a26bd2.png)

Your tool is attempting to create an index next to the input dataset. That would be unaccounted for storage, and it also doesn't work in secure environments, where the input files are mounted read-only. The usual trick is to create a symlink to your input file and then call whatever index command you need to run on the symlinked location, so the index is being created in the working directory.

The other 2 failures are pretty cryptic, these are just failing with an exit code of 1, but aren't printing any failure reason to stderr.

**Comment by bvalot** [comment]
> The other 2 failures are pretty cryptic, these are just failing with an exit code of 1, but aren't printing any failure reason to stderr.

I think,it is the problem of the database that must be open in read and write. 
I don't see information in the documentation to have input data that are also output.

**Comment by mvdbeek** [comment]
That breaks galaxy's concept of reproducibility and traceability and isn't supported. You can copy the input to a new output.

**Comment by bvalot** [comment]
> That breaks galaxy's concept of reproducibility and traceability and isn't supported. You can copy the input to a new output.

I can do that with "Pre-job and pre-process code" ?

**Comment by mvdbeek** [comment]
`cp '$input' '$output' && <the remainder of your command section that should now use $output instead of $input>`

**Comment by bvalot** [comment]
Oh, very simple indeed!

**Comment by bvalot** [comment]
It is really complicate to debug as the problem occurs only on docker test.
