### ISSUE TITLE
Normalize Issues

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#125]
1. Removes XML declaration (That's the `<?xml version="1.0" standalone="yes" encoding="UTF-8" ?>` string, or at the minimum `<?xml version="1.0"?>` that appears at the top of most XML files.)
2. Removes CDATA from `<command/>` blocks even when there's a `>` character there.

**Comment by jmchilton** [comment]
The real issue here is that it is advertised I think :) - the output is not something you should replace your tools with.

**Comment by erasche** [comment]
Well, then time to remove it before more people open similar issues? (Or hide it from the command menu?)

**Comment by jmchilton** [comment]
Is #126 sufficient?

**Comment by erasche** [comment]
+1
