### ISSUE TITLE
Job working directories are removed despite `--no_cleanup`

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/planemo#1253]
planemo, version 0.75.0.dev0 

`GALAXY_SLOTS=2 planemo test --biocontainers --no_dependency_resolution --no_conda_auto_init --galaxy_python_version 3.7 --failed --no_cleanup`

**Comment by nsoranzo** [comment]
I don't seem able to replicate this on the latest planemo and Galaxy on latest dev commit. What I am checking is that, after seeing:
```
2022-06-29 00:32:30,575 INFO  [galaxy.jobs.command_factory] Built script [/tmp/tmp8d9qv3hh/job_working_directory/000/1/tool_script.sh] for tool command
```
in the logs, `galaxy.jobs.command_factory] Built script [/tmp/tmp8d9qv3hh/job_working_directory/000/1/tool_script.sh` is still there after the test failed.

**Comment by bernt-matthias** [comment]
Ahh .. only failing job dirs are kept .. and it seems that I am responsible :( https://github.com/galaxyproject/planemo/pull/1226 .. 

I think I just wanted to play around with a successful job. Wondering if we should revert / improve this - since now the behavior is different from the CLI help:

```
  --no_cleanup                    Do not cleanup temp files created for and by
                                  Galaxy.
```

**Comment by mvdbeek** [comment]
Ah, yes, we definitely want an option to have `never`, not sure there's a usecase for onsuccess. Either you're debugging with `--no_cleanup`, or you're not :)

**Comment by nsoranzo** [comment]
The code makes sense to me as it is, I'd be more in favour of updating the CLI help.

**Comment by mvdbeek** [comment]
I don't think it makes sense, when would you want to use `--no_cleanup` but have the non-errored jobs be removed (which is what we do now) ? Note that `onsucess` also removes the output of jobs that succeeded, but where the tests fail. I think this is super common, I'd even make `never` the default.

**Comment by bernt-matthias** [comment]
How about restoring the original behavior, i.e. `--no_cleanup` implying `never`, and adding a `--cleanup X` parameter with `X` being `always`, `never`, or `onsuccess`?

**Comment by bernt-matthias** [comment]
I will open a PR. I guess we can just revert https://github.com/galaxyproject/planemo/pull/1226 - or?

**Comment by mvdbeek** [comment]
Didn't you want https://github.com/galaxyproject/planemo/pull/1226 so that you could use `always` by default ? This makes a lot of sense to me in the CI context.
