### ISSUE TITLE
planemo 0.74.11 fails with Python 3.10: AttributeError: module 'collections' has no attribute 'Callable'

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/planemo#1266]
When trying to run `planemo test` with Python 3.10, nose (a dependency of the Galaxy config that planemo installs) tries to refer to `collections.Callable` leading to an error because, since Python 3.3, `Callable` has been in `collections.abc`, not `collections`. The deprecation of `collections.Callable` finally resulted in it not being available as an import in Python 3.10.

Upstream, Galaxy is dropping nose support (see this PR: https://github.com/galaxyproject/galaxy/pull/13909) and this problem will be resolved as part of that process. This issue is being reported to offer a work-around and to explain what is behind the above-mentioned error.

Two workarounds are apparent:

1. Use a Python version < 3.10 to run planemo.
2. Patch nose 1.3.7 with [this patch](https://gist.github.com/pvanheus/a41aee46901d22012dd655facec91e5c)

The first of these is preferred.

**Comment by nsoranzo** [comment]
Thanks @pvanheus for documenting this issue! The first step is going to be merging https://github.com/galaxyproject/planemo/pull/1232 .

**Comment by mvdbeek** [comment]
Still need a new release, but indeed this should be fixed with https://github.com/galaxyproject/planemo/pull/1232
