### ISSUE TITLE
XSD Validation of Tools

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#127]
WIP at https://github.com/galaxyproject/planemo/commits/lxml using https://github.com/JeanFred/Galaxy-XSD.

The approach I was thinking was:

 - Make lxml an optional dependency.
 - If it is present, add an optional linter flag that causes planemo to also validate XSD.
 - ``normalize`` the tool to expand macros and then do XSD validation on that (XSD validation with macros in place would be ... troublesome).

I don't want lxml to be a required dependency because it requires libxml et. al. which can be problematic to install on some machines.

**Comment by jmchilton** [comment]
Made some more progress on this (now in xsd branch - https://github.com/galaxyproject/planemo/compare/xsd?expand=1) - includes WIP toward a ``shed_lint`` command #107.

**Comment by jmchilton** [comment]
Addressed with https://github.com/galaxyproject/planemo/pull/130

**Comment by jmchilton** [comment]
Merged - looking forward to more PRs to Galaxy-XSD :).

**Comment by erasche** [comment]
soon.jpg :)
