### ISSUE TITLE
[BUG] The new handling of the asserts section forgot a possible syntax

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/planemo#1309]
Hi,
One of the IWC workflow lint raise error because of this line:
https://github.com/galaxyproject/planemo/blob/483f310cdbe9cf5b57a0ae774581b7ad7f53d5c4/planemo/workflow_lint.py#L266

See: https://github.com/galaxyproject/iwc/actions/runs/3357665520/jobs/5580414418

The tests responsible for the fail are:
https://github.com/galaxyproject/iwc/blob/fbdefc404c7abe8b9a4b5b8a2a4b25ad8f38ecb9/workflows/epigenetics/atacseq/atacseq-tests.yml#L113-L118

Indeed when specifying multiple tests of the same kind, the only way to have them all taken into account is this syntax.
This is documented here: https://github.com/galaxyproject/galaxy/blob/dev/test/functional/tools/simple_constructs.yml
And the parser code is here:
https://github.com/galaxyproject/galaxy/blob/d30b8659eebb38cc4aff1111d3549be043bf374d/lib/galaxy/tool_util/parser/yaml.py#L267-L292

Also, if we modify it, maybe it would be good to also lint the asserts in the elements of a collection but this may come in a second wave.

**Comment by lldelisle** [comment]
I am trying to write a PR about that. I hope nobody started.

**Comment by mvdbeek** [comment]
That would be great, thank you @lldelisle!

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/planemo/pull/1310, thanks @lldelisle!
