### ISSUE TITLE
Planemo lint -- Select parameter has multiple options with the same text content

### ISSUE THREAD

**Issue by qiagu** [galaxyproject/planemo#1324]
`Planemo lint` with `galaxy-tool-util` v22.1 raises an error:

```
Applying linter inputs... FAIL
.. ERROR: Select parameter [metrics] has multiple options with the same value
.. INFO: Found 61 input parameters.
``` 

Downgrading `galaxy-tool-util` to v21.1.x solves the issue.

**Comment by mvdbeek** [comment]
Isn't that a problem in your tool?

**Comment by qiagu** [comment]
Ha, exactly. The old version `galaxy-tool-util` failed to catch the error.
