### ISSUE TITLE
Test failure for tool: Assertion for h5 fails claiming that h5py is not installed (but it is if you go to the venv for galaxy)

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/planemo#1333]
Hi there!

After installing the latest planemo version on a venv, and then running on [this tool](https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/blob/feature/fix_scanpy_versions_sorting/tools/tertiary-analysis/scanpy/anndata_operations.xml):

```
planemo test anndata_operations.xml
```

We get errors in the tests with `h5 assertion requires unavailable optional dependency h5py`.

However, descending into the galaxy venv created by planemo, shows that the package is indeed installed (and h5py is in the list of required dependencies for galaxy), redoing the same steps Galaxy seems to be doing:

```
(gx_venv_3) [pcm32@tololo scanpy]$ python
Python 3.9.5 (default, Jul 27 2021, 12:28:44) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
>>> 
>>> try:
...       import h5py
... except ImportError:
...       h5py = None
... 
>>> h5py
<module 'h5py' from '/main/homes/pcm32/.planemo/gx_venv_3/lib/python3.9/site-packages/h5py/__init__.py'>
>>> def _assert_h5py():
...     if h5py is None:
...         raise Exception(IMPORT_MISSING_MESSAGE)
... 
>>> _assert_h5py()
# no exception raised...
```

I also see this with an older version of Galaxy (21.01 I think) being used in a CI (see [artifacts here](https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/actions/runs/3574983028) at the bottom if it helps).

I'm not sure if this is more of a Galaxy bug rather than planemo, but since it happened in both occasions from planemo I thought I should raise it here. Thanks!

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/planemo/pull/1326, I'll cut a release tomorrow

**Comment by pcm32** [comment]
Great! Thanks, will try it as I see it.

**Comment by mvdbeek** [comment]
Release is up, https://pypi.org/project/planemo/0.75.3/. Let me know if this doesn't fix it.

**Comment by pcm32** [comment]
I can confirm it is working now, thanks!
