### ISSUE TITLE
planemo lint errors when value and deltra attrs in <has_size> contain suffixes

### ISSUE THREAD

**Issue by maximskorik** [galaxyproject/planemo#1335]
### Description
`planemo lint` returns an error when `value` or `delta` attributes of `<has_size>` contain suffixes. Per [Galaxy documentation](https://docs.galaxyproject.org/en/latest/dev/schema.html#id111) suffixes should be accepted. Despite the linting errors, the tests finish successfully, and suffixes work as expected.

Error message:
```
.. ERROR: Test 1: attribute 'value' for 'has_size' needs to be 'int' got '1708k'
.. ERROR: Test 1: attribute 'delta' for 'has_size' needs to be 'int' got '1k'
```

Locally the linter only throws errors concerning the `delta` attributes, whereas `galaxyproject/planemo-ci-action@v1` in GitHub Actions complains about both `value` and `delta`.

### Example
A reproducible example can be found here: https://github.com/RECETOX/galaxytools/pull/314

**Comment by bernt-matthias** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/13248 .. could need some help there @nsoranzo

**Comment by nsoranzo** [comment]
Fixed by https://github.com/galaxyproject/galaxy/pull/15873 .
