### ISSUE TITLE
change conda by mamba ?

### ISSUE THREAD

**Issue by pimarin** [galaxyproject/planemo#1340]
Hello,

Isn't be better to change the conda command by mamba to spent less time during test deployment ?

**Comment by bgruening** [comment]
The mamba solver, the things that makes mamba fast is integrated in the laster conda release, so latest conda should be as fast as mamba if this solver is activated. Can you try to upgrade?

**Comment by nsoranzo** [comment]
If you run Planemo with the the dev branch of Galaxy (e.g. `planemo test --galaxy_branch dev` or using `--galaxy_root`) the mamba solver should be used automatically.
