### ISSUE TITLE
shed_create with testtoolshed fails

### ISSUE THREAD

**Issue by paulzierep** [galaxyproject/planemo#1353]
I tried an initial upload to the testtoolshed:
`planemo shed_create --shed_target testtoolshed`
and got:
`Repository [pharokka] does not exist in the targeted Tool Shed.`
but when I tried to do it again:
`planemo shed_create --shed_target testtoolshed`
 I got:
`Unexpected HTTP status code: 400: {"err_msg": "You already own a repository named <b>pharokka<\/b>, please choose a different name.", "err_code": 400008}`
However shed_update reports that it does not exist.
`planemo shed_update --check_diff --shed_target testtoolshed`
`Repository [pharokka] does not exist in the targeted Tool Shed.
Failed to update repository 'pharokka' as it does not exist on the test Tool Shed.`

**Comment by bgruening** [comment]
Try something like planemo shed_upload --force_repository_creation

**Comment by paulzierep** [comment]
`planemo shed_upload --force_repository_creation --shed_target testtoolshed`

leads to:

```
cd '/home/paul/git/tools-iuc/tools/pharokka' && git rev-parse HEAD
galaxy.util.commands WARNING: Passing program arguments as a string may be a security hazard if combined with untrusted input
git diff --quiet
Unexpected HTTP status code: 400: {"err_msg": "You already own a repository named <b>pharokka<\/b>, please choose a different name.", "err_code": 400008}
Repository [pharokka] does not exist in the targeted Tool Shed.
```

Seems to be realted to https://help.galaxyproject.org/t/error-pushing-tool-to-toolshed-using-planemo/5427/9

**Comment by nsoranzo** [comment]
@paulzierep Can you please try `planemo shed_update --shed_target testtoolshed` , i.e. without `--check_diff` ?
That probably fails because the repo is empty.

**Comment by paulzierep** [comment]
`planemo shed_update --shed_target testtoolshed`
leads as well to:
```
Repository [pharokka] does not exist in the targeted Tool Shed.
Failed to update repository 'pharokka' as it does not exist on the test Tool Shed.
```

**Comment by bgruening** [comment]
Please try `--force_repository_creation`

**Comment by paulzierep** [comment]
@mvdbeek can we reopen this, seems not to be fixed for me.
@bgruening `--force_repository_creation` does not help see above

**Comment by paulzierep** [comment]
OK I found that this https://github.com/galaxyproject/planemo/issues/1220 was the issue.

**Comment by mvdbeek** [comment]
And `Failed to find repository for owner/name {owner}/{name}"` should help a lot there, that's why this I closed this.
