### ISSUE TITLE
Is it possible to test data managers with planemo ? 

### ISSUE THREAD

**Issue by paulzierep** [galaxyproject/planemo#1362]
I am writing a data manager and wanted to check if it is possible to test it with planemo. Could not found anything in the docs about it.
When I run:

```
planemo serve . 
```

In the DM folder, I can see the tool in the DM tool panel, but when I try to use it, it shows:

`Tool execution through the `tool_runner` requires a `runtool_btn` flag or `URL` parameter.`

Currently, I test the DM via upload in the testtoolshed and local installation, but I feel there should be a faster and simpler way.

**Comment by mvdbeek** [comment]
Yes, `planemo test data_manager/tool.xml`

**Comment by paulzierep** [comment]
Ah OK that worked, but should `planemo test/serve .` not also work ? Is this in the docs ?
