### ISSUE TITLE
lint wrongly complains that tests expected to fail are missing output

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#138]
e.g.

```
$ planemo lint ../pico_galaxy/tools/seq_select_by_id/ --report_level warn
Linting tool /mnt/galaxy/repositories/pico_galaxy/tools/seq_select_by_id/seq_select_by_id.xml
Applying linter lint_tests... WARNING
.. WARNING: No outputs defined for tests, this test is likely invalid.
Failed linting
```

This contains a failure-condition test which rightly has no output:

```
        <test expect_failure="true" expect_exit_code="1">
            <param name="input_file" value="empty.fasta" ftype="fasta" />
            <param name="input_tabular" value="k12_hypothetical.tabular" ftype="tabular" />
            <param name="column" value="1" />
            <assert_stdout>
                <has_line line="Indexed 0 sequences" />
            </assert_stdout>
            <assert_stderr>
                <has_line line="Identifier 'gi|16127999|ref|NP_414546.1|' not found in sequence file" />
            </assert_stderr>
        </test>
```

**Comment by erasche** [comment]
More linting issues:

/home/travis/build/galaxyproject/tools-iuc/packages/package_tpp_4_8_0/tool_dependencies.xml:5: element actions: Schemas validity error : Element 'actions', attribute 'architecture': The attribute 'architecture' is not allowed.
/home/travis/build/galaxyproject/tools-iuc/packages/package_tpp_4_8_0/tool_dependencies.xml:5: element actions: Schemas validity error : Element 'actions', attribute 'os': The attribute 'os' is not allowed.

**Comment by erasche** [comment]
Edit: Not linting issues. Thanks @jmchilton Opened https://github.com/galaxyproject/tools-iuc/issues/118
