### ISSUE TITLE
planemo autoupdate report bug

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/planemo#1403]
It is not the first time it happens:
https://github.com/galaxyproject/iwc/pull/276
While there is no error in the autoupdate itself, there is a bug in the report:

> toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicates/2.18.2.4 should be updated to toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_MarkDuplicatesWithMateCigar/2.18.2.3

**Comment by nsoranzo** [comment]
Will hopefully be fixed by #1406.

**Comment by lldelisle** [comment]
Would be great. Thank you very much for taking care of this.
