### ISSUE TITLE
planemo training_init creates maintainers not editorial_board

### ISSUE THREAD

**Issue by patrick-austin** [galaxyproject/planemo#1415]
Based on galaxyproject/training-material/pull/4273 it seems that the metadata.yaml should be initialised with `editorial_board` rather than `maintainers` as is done here:
https://github.com/galaxyproject/planemo/blob/5951e90ca4e1eb5059a9b1da5cb9aadae4618e8f/planemo/training/topic.py#L115

Don't know if anything else needs to change as part of this (or if this is a planemo issue versus GTN issue).

**Comment by hexylena** [comment]
Ah most people aren't contributing new topics so we hadn't noticed this. Yeah it's just a simple rename.
