### ISSUE TITLE
Planemo serve: --host not utilised

### ISSUE THREAD

**Issue by selten** [galaxyproject/planemo#1429]
- Operating system: Ubuntu 22.04 in Docker
- Setup details: Planemo and Galaxy are both installed in a docker container, this container is ran to allow 'planemo serve', 'planemo test' etc. However, for planemo serve we set --host to 0.0.0.0 for accessing the container outside of Docker. In the newer versions of Galaxy (22.05, 23.0, etc.) this is not respected by planemo.
- Steps to reproduce:
  1.  Setup planemo
  2. Setup Galaxy >= 22.05
  3. Run planemo serve with --host

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/planemo/pull/1430, thanks @selten!
