### ISSUE TITLE
Shed Documentation Section

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#147]
Publishing to the tool shed. Walk through ``shed_init``, ``shed_create``, ``shed_diff``, and ``shed_upload``.

Related https://github.com/galaxyproject/planemo/issues/25.

**Comment by jmchilton** [comment]
Initial attempt closed with 374ee648d4bd9196fe8665d1356cba9b82fae0cd. See at http://planemo.readthedocs.org/en/latest/publishing.html#shed.

**Comment by erasche** [comment]
Thanks!
