### ISSUE TITLE
New toolshed categories are not updating for the existing tools

### ISSUE THREAD

**Issue by pavanvidem** [galaxyproject/planemo#1480]
We recently added a few new toolshed categories to the existing tools in this PR: https://github.com/galaxyproject/tools-iuc/pull/6114 

The categories should have been updated in the toolsshed for at least the updated tools. But this is not the case. For eg., Scanpy has been updated recently but the new categories are not updated in the toolshed. 

If a new tool is added, then the categories are updated. For example, the new Seurat tool suite belongs to the Single Cell category on toolshed.

**Comment by mvdbeek** [comment]
That's not how it works, otherwise any user can create new (nonsense) categories.

**Comment by mvdbeek** [comment]
The categories exist, so I'm not sure what this is about.

**Comment by bgruening** [comment]
If Pavan adds a new category to the shed.yml (a category that exists in the TS already), its not populated upon push. I guess we need to understand why changes to a shed.yml is not reflected in the TS.

**Comment by mvdbeek** [comment]
What repo is this ?

**Comment by pavanvidem** [comment]
the tools are from IUC

**Comment by mvdbeek** [comment]
Which tool repo is an example that should have been updated ?

**Comment by mvdbeek** [comment]
Please be more specific. The PR just lists changes to the .shed.yml file

**Comment by pavanvidem** [comment]
All the tools in that PR. For example Scanpy https://github.com/galaxyproject/tools-iuc/tree/main/tools/scanpy

**Comment by mvdbeek** [comment]
I need a deploy commit, the last commit in there has not been deployed afaict

**Comment by mvdbeek** [comment]
Or if you're not finding one let me know about a repo I can deploy.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/planemo/pull/1481 should fix this. I don't think it ever worked, so nice one!

**Comment by pavanvidem** [comment]
@mvdbee thanks a lot!  I can see the Scanpy tools in the Single Cell category on toolshed.
 
This will trigger upon a tool update or? What about the other tools in that PR where I recently added the Single Cell category? Should I just bump the other tools' galaxy versions to trigger? is there a better trick?

**Comment by mvdbeek** [comment]
Someone with iuc permissions can set the category in the TS user interface or reupload the package, which will also update the metadata.
