### ISSUE TITLE
Dockerized Galaxy Alternative

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#15]
Every command that uses a `--galaxy_root`, should also allow use of a Dockerized Galaxy instance instead based on https://github.com/bgruening/docker-galaxy-stable.

**Comment by jmchilton** [comment]
I think this is particularly important for ``shed_test``. If we can get shed tests running in a container - then we are one step closer to using it a complete replacement for the install and test framework. It would mean the server components that would be responsible for running tests could run the exact environment that command-line users would. This would be a big improvement over the current install and test framework - that uses AMIs in a relatively oblique way.

**Comment by bgruening** [comment]
@jmchilton we have a TS based Docker Image based on our Docker image. If you agree we can merge this into the main docker image or as additional layer.

**Comment by jmchilton** [comment]
@bgruening Do you have a link for the tool shed based on your Docker image?

**Comment by bgruening** [comment]
Ping @smithcr!
