### ISSUE TITLE
planemo shed_lint and tool_dependency_definition

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#156]
For a tool dependency definition there should be only two files present, ``.shed.yml`` and ``tool_dependencies.xml`` (since the Tool Shed insists on just the ``tool_dependencies.xml`` being uploaded, not even allowing a README file).

```
$ more galaxy_blast/dependencies/package_blast_plus_2_2_30/.shed.yml
name: package_blast_plus_2_2_30
owner: iuc
homepage_url: https://github.com/peterjc/galaxy_blast/dependencies/package_blast_plus_2_2_30
remote_repository_url: https://github.com/peterjc/galaxy_blast/dependencies/package_blast_plus_2_2_30
description: NCBI BLAST+ 2.2.30 (binaries only) 
long_description: |
  This Tool Shed package is intended to be used as a dependency of the Galaxy wrappers
  for NCBI BLAST+ and any other tools which call the BLAST+ binaries internally.

  Development is hosted on GitHub https://github.com/peterjc/galaxy_blast/ which can
  be used for reporting any issues.
categories:
- Sequence Analysis
type: tool_dependency_definition
```

```
$ planemo shed_lint galaxy_blast/dependencies/package_blast_plus_2_2_30
Linting repository /mnt/galaxy/repositories/galaxy_blast/dependencies/package_blast_plus_2_2_30
Applying linter dependencies... CHECK
.. INFO: tool_dependencies.xml found and appears to be valid XML
Applying linter itory_dependencies... CHECK
.. INFO: No repository_dependencies.xml, skipping.
Applying linter yaml... CHECK
.. INFO: .shed.yml found and appears to be valid YAML.
Applying linter e... CHECK
.. INFO: No README found skipping.
```

Having looked at the ``.shed.yml`` and noticed ``type: tool_dependency_definition``, rather than looking at any ``repository_dependencies.xml`` this should be checking there isn't such a file.

Having a README file would be harmless (not used by the ToolShed, but might be useful for humans, and would be shown on GitHub/Bitbucket etc).

**Comment by jmchilton** [comment]
Extra files are no longer a problem - ``planemo shed_upload`` will just not "realize" invalid files for the given repository ``type`` - so you can have a README, CONTRIBUTING, LICENSE, etc... on github - they just won't be published to the tool shed. That said - I think it ``planemo shed_lint`` should definitely verify a ``package_`` repository has a ``tool_dependencies.xml`` file and ``suite_`` repository has a ``repository_dependencies.xml`` file and perhaps even that they don't have the opposite.

**Comment by peterjc** [comment]
+1 on verifying there is a ``tool_dependencies.xml`` for package repositories.
