### ISSUE TITLE
Improve Travis Testing

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#16]
- [ ] Handle custom datatypes.
- [x] Handle tool data tables.
- [ ] `travis_init` should report more and have `-f` option.
- [ ] Split setup and testing into separate steps (https://twitter.com/pjacock/status/572412594130182146).

**Comment by peterjc** [comment]
In addition to status handling from splitting setup and test on TravisCI (failure in setup gets a grey icon, while failure in tests gets a red icon and is regarded as an error), this also has the benefit of hiding (collapsing) the setup log when viewing the TravisCI output, focusing on the test output.
