### ISSUE TITLE
Shed Operations on Github URLs

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#169]
Update shed realization process to take in git URLs in addiiton to file paths. This will allow each of ``shed_create``, ``shed_upload``, ``shed_diff``, ``shed_download``, and ``shed_lint`` to work on repositories sitting in Github.

**Comment by peterjc** [comment]
Would this mean you can just download & install planemo, and then pull a tool directly from GitHub to the Tool Shed (without first cloning the tool from GitHub to the local disk)?

**Comment by jmchilton** [comment]
Yes... I mean planemo would clone the repo into ``/tmp`` presumably - but the "user" wouldn't really be exposed to that directly.

I am not sure there is a super-compelling use case on its own - but after that functionality was added the next step would be creating a well tested "model" persisting links ``.shed.yml`` URLs (presumably mostly on github), and then building a REST-y web interface on top of that "model" and the existing ``shed_`` commands - perhaps optionally tapping into the shed database directly for auth and user management, and then ultimately an actual web app for managing shed repositories.

This would implement a vision for replacing the tool developer-facing portions of the tool shed web interface with a simpler interface that centered on sync-ing repositories Github. The team had discussed this interface with the scientific advisory board long before planemo had these ``shed_*`` operations - so I am not sure the web interface vision is as important now that ``planemo`` and @erasche's Jenkins work make publishing... easy enough? - but I do think if this is implemented it will be powered by planemo's interface to the tool shed.

**Comment by erasche** [comment]
When I saw this, the super-compelling use case that came to mind was a queued task on a TS server, meaning @martenson would have the TS-GitHub integration done for him, he just has to queue a task on receipt of a github hook.

**Comment by peterjc** [comment]
@jmchilton's description of a Tool shed web interface for Tool authors to pull/sync their repositories updates from Github is interesting - but is still a manual process.

Meanwhile, I'm starting to use planemo for automating pushing my tools to the Tool Shed from the command line, a bit step forward in reproducibility/automation :+1:

**Comment by martenson** [comment]
@peterjc not necesarilly a manual process - I am thinking more of a cron-like job with option to manually instant run
