### ISSUE TITLE
Implement shed_test command.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#176]
- Don't test local stuff - test stuff published to shed.
  - Setup an on-the-fly Galaxy instance with ``planemo.galaxy_config`` module.
  - Update to actually configure shed artifacts.
  - Use ``bioblend`` to install the repository.
  - Run the tests (I think ``run_tests.sh --installed`` might be do this).
- Allow specifying a ``shed_target``.
- Use ``.shed.yml`` to resolve id, etc....

**Comment by peterjc** [comment]
When you say "Don't test local stuff - test stuff published to shed." I assuming this would catch mismatches between local files in the git repository vs the files actually included in the tar-ball which would be published on the Tool Shed (e.g. incomplete manifest information in ``.shed.yml``)?
