### ISSUE TITLE
Auto-include does not ignore #example# or example~ files

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#179]
e.g. Tar-ball contains temp files from common Unix editors:

```
$ planemo shed_upload --tar_only  ~/repositories/pico_galaxy/tools/nlstradamus/ && tar -xvf shed_upload.tar.gz
cp '/tmp/tmpDhxzFT' 'shed_upload.tar.gz'
#README.rst#
README.rst~
README.rst
nlstradamus.xml
tool_dependencies.xml
```

Either planemo needs some additional default excludes, or perhaps it could read the local ``.gitignore`` to expand the exclude list? (I would have said that was too magic, but planemo seems to do a lot of clever stuff like this already)

**Comment by jmchilton** [comment]
Indeed - seems like a good idea.

**Comment by erasche** [comment]
+1 to gitignore, though that will definitely look like magic.

**Comment by jmchilton** [comment]
I would rather explicitly exclude ``*~`` and ``#*#`` patterns (in an eventually overriddable way) than worry about ``.gitignore`` (I'll try to do this soon). There may in fact be derived artifacts that should be tarred up but should not be in the git repository - so I think it would be best to ignore ``.gitignore``.
