### ISSUE TITLE
Different behaviour between test cases and citations

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#182]
An empty test block counts as a warning, whereas an empty citation block doesn't. I would expect consistent behaviour between the two of them, specifically that an empty test block would be downgraded to INFO. An empty test block, like an empty citation block, implies that we know they're supposed to be there, but don't have a test case added for one reason or another.

```xml
<tests>
</tests>
<citations>
</citations>
```

See https://github.com/galaxyproject/planemo/pull/152 for related discussion

**Comment by peterjc** [comment]
Best practice is to have both tests and citations, but I would prefer to be stricter about trying to get people to add tests.

**Comment by erasche** [comment]
Agreed, I would prefer to be stricter about adding tests than about adding citations.

However, there are cases when you don't have tests, and would like to indicate that. I see `<tests></tests>` the best way to indicate "I have no tests", like `<citations></citations>` is the best way to indicate "I have no citations"

E.g:

- https://github.com/galaxyproject/tools-iuc/blob/master/data_managers/data_manager_bowtie_index_builder/data_manager/bowtie_index_builder.xml
- https://github.com/galaxyproject/tools-iuc/blob/entrez/tools/ncbi_entrez_eutils/epost.xml (I don't really need to test post, if the rest of the commands are working, no need to fill up their history server)
- https://github.com/galaxyproject/tools-iuc/blob/master/tools/jbrowse/jbrowse.xml hard to test/testing won't tell us anything useful until #19

**Comment by peterjc** [comment]
Why can't those three examples have tests? Even if they are "dummy" tests which do little more than verify that an output file was made.

**Comment by erasche** [comment]
That's a fair point.
