### ISSUE TITLE
Allow testing tool_dependencies.xml without a tool shed.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#19]
- [ ] Finish work on transcribing tool sheds to Homebrew taps (https://github.com/jmchilton/shed2tap).
 - [ ] Every hour synchronize the tool shed and test tool shed with a brew tap (e.g. https://github.com/jmchilton/homebrew-toolshed). 
 - [ ] Add planemo options for installing a `tool_dependencies.xml` with as if it were installed into a particular tool shed - all with `brew` using these taps.
 - [ ] Implement a Galaxy dependency resolver that uses `tool_dependencies.xml` plus these custom taps to resolve dependencies the way it would be done via tool shed installs.
 - [ ] Add option to `test` command to do resolution in this fashion.

**Comment by erasche** [comment]
From #86 

Possibly should try and find the packages locally (e.g. ../../packages/###)

**Comment by mdshw5** [comment]
Is there any progress on this feature? I'm currently trying to test a tool with tool_dependencies using `planemo serve` but realize that I need to set up a local tool shed and then.. (inform planemo about it?)

**Comment by jmchilton** [comment]
Not really - sorry. If you want to test tools with ``planemo serve`` you need to make sure the dependencies are locally available. It doesn't address tool shed dependencies at this time - to do that testing I guess I would recommend publishing to the test tool shed and testing manually.

**Comment by mdshw5** [comment]
Got it. Thanks!
Matt Shirley

**Comment by jmchilton** [comment]
Closing as won't fix - we are moving toward conda and these options exist today. The remaining issues are largely all Galaxy issues.
