### ISSUE TITLE
Check for missing <when/> blocks

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#194]
Since Galaxy complains about this, it'd be reasonable for planemo to lint on it as well.

xref https://github.com/galaxyproject/tools-devteam/pull/131 https://github.com/galaxyproject/tools-iuc/pull/130

**Comment by martenson** [comment]
Given that Galaxy falls back with reasonable defaults (and the number of these warnings) this might be better when the warnings are removed form Galaxy itself.

**Comment by jmchilton** [comment]
I feel like it is a good warning - it will catch typos and encourage people to be explicit.

**Comment by nsoranzo** [comment]
Yes, please!

**Comment by peterjc** [comment]
+1 on warning about this in planemo (and keeping the warnings in Galaxy)

**Comment by peterjc** [comment]
I just saw the opposite problem which ``planemo lint`` could also spot: ``<when/>`` blocks which did not match the select, e.g. something like this:

```
        <conditional name="input_type_conditional">
            <param name="input_type" type="select" label="Input Type">
                <option value="single" selected="true">Single Dataset</option>
                <option value="paired_collection">Paired Collection</option>
                <!-- note missing paired_files here -->
            </param>
            <when value="single">
                 <param name="fastq_input1" type="data" format="fastqsanger" label="Select fastq dataset" help="Specify dataset with single reads"/>
            </when>
            <when value="paired_files">
                 <param name="fastq_input_f" type="data" format="fastqsanger" label="Select forward fastq dataset" help="Specify dataset with forward reads"/>
                 <param name="fastq_input_r" type="data" format="fastqsanger" label="Select reverse fastq dataset" help="Specify dataset with reverse reads"/>
            </when>
            <when value="paired_collection">
                 <param name="fastq_input" type="data_collection" format="fastqsanger" label="Select dataset pair" help="Specify paired dataset collection containing paired reads" />
            </when>
        </conditional>
```

**Comment by peterjc** [comment]
Could a small extension to this catch the reverse problem as in my example above?

**Comment by erasche** [comment]
@peterjc that's covered in #350. https://github.com/galaxyproject/planemo/pull/350/files#diff-4179932f7b3dedef8f42d33fb6259e01R61

**Comment by peterjc** [comment]
Great, thanks.
