### ISSUE TITLE
planemo shed_upload fails if only trying to change metadata

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#199]
e.g.

```
$ planemo shed_upload --shed_target testtoolshed ~/repositories/pico_galaxy/tools/mira4_assembler/ ; echo "$? returned"
cd '/mnt/galaxy/repositories/pico_galaxy/tools/mira4_assembler' && git rev-parse HEAD
cd '/mnt/galaxy/repositories/pico_galaxy/tools/mira4_assembler' && git diff --quiet
/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/mnt/galaxy/repositories/planemo/.venv/lib/python2.6/site-packages/requests-2.7.0-py2.6.egg/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Could not update mira4_assembler
No changes to repository.
255 returned
```

There was a change to the meta-data in ``.shed.yml`` which I was hoping to push to the Test Tool Shed via ``planemo shed_upload`` even though the files themselves had not changed: https://github.com/peterjc/pico_galaxy/commit/238db3900d3a01e82089aaaae4a1919556805504

**Comment by jmchilton** [comment]
This is a serious and "known" limitation - but I cannot find an issue for it now. The extended metadata is only used during creation. This needs to be fixed and soon-ish if we are going to continue to push broad adoption of ``.shed.yml`` files - I'll try to get to this this week.

**Comment by peterjc** [comment]
I was planning to add more categories to my ``.shed.yml`` files and then push to the Tool Shed, so I'll wait before doing that... thanks!

**Comment by erasche** [comment]
Sorry, this is at least partially my fault. I didn't ever get around to implementing the "update" API route for the TS/.shed.yml stuff. Happy to help with this as well.

**Comment by jmchilton** [comment]
WIP @ https://github.com/jmchilton/planemo/tree/update_metadata. 

Thinking about adding a ``--metadata`` option to ``shed_upload`` - but adding a separate command ``shed_update`` more like ``shed_create`` for explicitly managing metadata. Wonder if ``shed_update`` should default to also doing an upload that can be disabled with ``--no_upload`` - or by default just have it manage metadata by default and requiring a flag like ``--upload`` to force it to update contents as well.

**Comment by peterjc** [comment]
That's great - I'm switching to using ``planemo shed_update`` now:
* https://github.com/peterjc/pico_galaxy/commit/3c6f0dca0e1318eecd1e07d177ffc5752b4f6c95
* https://github.com/peterjc/galaxy_blast/commit/bdc053f0ffebd364eb60c9e963873fc2d9e049d0
