### ISSUE TITLE
Bad english in error message

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#211]
`.. ERROR: Found param input with not name specified.`

perhaps "Found param input with no name specified".

**Comment by davebx** [comment]
My guess is he meant to say "Found input param with no name specified"

**Comment by erasche** [comment]
While we're on the topic...

```
Applying linter inputs... FAIL
.. ERROR: Found param input with not name specified.
.. ERROR: Found param input with not name specified.
.. INFO: Found 28 input parameters.
```

It might be nice to template in some other value (like the label? type? help? anything?) in order to help users figure out which parameter is missing a name
