### ISSUE TITLE
Docker appliance very out of date

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/planemo#212]
I'm new to using Planemo, and so far I'm loving it.  The Docker appliance seemed like a great way to go, giving me a pristine Galaxy instance quickly, with an editor, terminal, etc. However, I recently realized that the version of Planemo in the docker instance is quite old:

    ubuntu@eb19c6eb2489:/opt/galaxy/tools$ planemo --version                                                                                                         
    planemo, version 0.5.0

After a bit more looking, it seems this is perhaps because the version in linuxbrew is old?

**Comment by jmchilton** [comment]
Thanks for the bug report @lparsons - I will try to build a new version soon. Someone on IRC also pointed out the Docker image only works if your UID is 1000 - which is an unreasonable limitation. I'll try to fix both of these problems this week - but in the meantime I would recommend installing planemo with either pip or Homebrew or linuxbrew (which both do have much newer versions available than 0.5.0).

**Comment by jmchilton** [comment]
Docker image has been updated with the latest stable planemo and now works for users whose base OS UID is not 1000.
