### ISSUE TITLE
Utility addition to recursive uploads allowing filtering based on git diffs

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#225]
@bgruening reported an issue on the TTS whereby my automated jenkins job was wiping out any of his testing. So! This means I need to be smarter about uploads.

Here's what I imagine will work best (feedback welcome!)

- provide some way for planemo to accept a git diff (or a `$PREV_GIT_COMMIT_ID` allowing calculation of a git diff)
- based on the paths involved in that diff, figure out a set of directories with possible changes
- pass those to the recursive upload function.

**Comment by peterjc** [comment]
Would it be too slow to just call a recursive ``planemo shed_update`` on everything?

**Comment by erasche** [comment]
@peterjc huh, didn't know about `shed_update`, but that's essentially what we were doing with `shed_upload` it looks like.

It wasn't a speed issue, Björn was just uploading custom revisions, and I was wiping them out. It's a completely solvable problem *just* by having the upload bot work well enough that humans don't need to manually upload things to the toolshed, resulting in the bot uploading on top of them.
