### ISSUE TITLE
URL Checking functionality for packages

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#228]
As a **stopgap** measure (until I've got a distributed, fault-tolerant package storage service online), I'd like to add a feature to planemo to check URL validity, especially in light of issues like https://github.com/galaxyproject/tools-iuc/pull/189

This feature would likely take the form of a `--validate_urls` flag in `shed_lint`, which would urlopen+read the first few bytes of each url, additionally checking the return code for equality to 200

**Comment by jmchilton** [comment]
That would be awesome @erasche!
