### ISSUE TITLE
Linting rules for tool_type="data_source"

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#232]
- [x] no tests
- [x] ~~sometimes no help (but I'm adding dummy help)~~ (agreed this should still be there)
- [x] ~~basically never citations (since not rerunnable)~~ (agreed these should still be there)
- [x] `<display/>` input type
- [x] `<uihints />` are also present.

**Comment by jmchilton** [comment]
Turned this issue into a check list - hope that is okay.

**Comment by erasche** [comment]
absolutely
