### ISSUE TITLE
Virtualbox Virtual Appliance

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#239]
The planemo-machine Virtualbox (OVA) virtual appliance is now working nicely and has a nice XUbuntu window manager setup. This needs to be made available and documented.

- [X] ~~Install X11 earlier so the virtualbox extras include X utilities (might fix copy and paste). (planemo-machine)~~ (Was a client configuration in Virtualbox GUI)
- [x] Setup Atom IDE. (I use sublime personally - but Atom is open source so I feel more comfortable advertising it). (planemo-machine)
- [x] Auto login into the ubuntu user. (planemo-machine)
- [x] Upload an OVA to images.galaxyproject.org.
- [x] Update planemo appliance to describe this.

**Comment by znerp** [comment]
I tried running tests with planemo via a virtual box with vagrant (I created the vagrantfile according to https://planemo.readthedocs.io/en/latest/appliance.html), but there seems to be a problem with installing dependencies like numpy. 

Thus, @ThomasWollmann and I tried to follow the directions in .travis.yml of the tools-iuc directory of galaxy. Getting multiple errors on the way, we manually removed multiple components like pip, components of python etc. After reinstalling some components we finally got the following error when simply running "planemo" (thus already failing at planemo conda_init):

Traceback (most recent call last):
  File "/home/ubuntu/.linuxbrew/Cellar/planemo/0.12.2/libexec/bin/planemo", line 9, in <module>
    load_entry_point('planemo==0.12.2', 'console_scripts', 'planemo')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ubuntu/.linuxbrew/Cellar/planemo/0.12.2/libexec/lib/python2.7/site-packages/planemo/cli.py", line 12, in <module>
    from .io import error  # noqa, import must happen after Galaxy hack
  File "/home/ubuntu/.linuxbrew/Cellar/planemo/0.12.2/libexec/lib/python2.7/site-packages/planemo/io.py", line 10, in <module>
    from galaxy.tools.deps import commands
  File "/usr/local/lib/python2.7/dist-packages/galaxy/tools/deps/__init__.py", line 16, in <module>
    from .requirements import (
  File "/usr/local/lib/python2.7/dist-packages/galaxy/tools/deps/requirements.py", line 16, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

Some help resolving this issue would be really appreciated!

**Comment by bgruening** [comment]
@znerp you can use https://images.galaxyproject.org/planemo/latest.ova from the summer this year if you really need to. But most users simply use `pip install planemo` or conda to install planemo without a VM.

**Comment by ThomasWollmann** [comment]
> @znerp you can use https://images.galaxyproject.org/planemo/latest.ova from the summer this year if you really need to. But most users simply use pip install planemo or conda to install planemo without a VM.

@bgruening We need some kind of VM, since dev maschine is running Windows.

**Comment by bgruening** [comment]
@ThomasWollmann is the linked Vm good enough if you update planemo inside of it.

**Comment by ThomasWollmann** [comment]
@znerp gave it a try but updating is not straight forward, since the python packages are shipped with the dist and have to be updated too. Therefore, he removed all python related system packages and installed newer versions through a fresh pip/conda installation.
