### ISSUE TITLE
GCC 2015 - Workshop Exercises

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#241]
Intro Tutorial.

- [X] Add ``project_init`` for seqtk package.
- [ ] Update planemo_appliance docs to publish seqtk package to local tool shed.
- [ ] Update planemo_standalone docs to publish seqtk package to test tool shed.

Advanced Tutorial.

Given a minimal wrapper (mapper):

 - [ ] Add test case for command-line.
 - [ ] Add conditional - check command-line.
 - [ ] Add and test index data.
 - [ ] Add metadata support.
 - [ ] Add collection support.

Advanced Collections Example (?):

- [ ] Split on something (barcode?) and collect output.

**Comment by jmchilton** [comment]
Added some demo code for use with ``project_init`` to build these up on here - https://github.com/galaxyproject/planemo/commit/b48e9e64655a8d0d8fd4c8ad979df77e961096e2.

**Comment by jmchilton** [comment]
Ping @blankenberg - you had mentioned metadata validation. Is that possible with bwa? Can you provide a short example of what you were thinking for say this tool (https://github.com/galaxyproject/planemo/blob/b48e9e64655a8d0d8fd4c8ad979df77e961096e2/project_templates/bwa/bwa-mem.xml)?

**Comment by bgruening** [comment]
John I did a GalaxyDevDay yesterday here in FR, here are my small observations.

* Showing a small initial example is a nice start. We used the [head tool](https://github.com/bgruening/galaxytools/blob/master/tools/text_processing/text_processing/head.xml) it's simply enough.
* Editing the `.planemo.yml` was not a good idea and it distracted people. I think entering the `--galaxy_root_dir` is ok for a workshop if you only do it a few times.
* We did this for 4h and we were able to complete a few tools but we never touched advanced stuff like collections and meta-data. Even repeats turned out to be quiet hard.

This workshop is probably not comparable to the GCC workshop. Yesterday all of the participants started to write there own wrapper. But be aware that things are more complicated for beginners than we can imagine.

**Comment by martenson** [comment]
@bgruening awesome feedback, thanks!

**Comment by jmchilton** [comment]
@martenson indeed - awesome feedback - thanks @bgruening.

This does bring the key question though - which is "WTF"? Why are @martenson and I taking point when we are probably the only two people involved who have never done a tool workshop :fearful:. Everyone else who has done this before better prevent us from looking like idiots.

**Comment by peterjc** [comment]
I've only helped at GCC2014...

**Comment by martenson** [comment]
also you guys wrapped a bzillion of tools :D
@jmchilton I learned a lot about tools preparing the training, let's call it the trainer's training :)

**Comment by bgruening** [comment]
@jmchilton I trust in you and we will help you wherever we can. I was just pointing out that you don't need to explain every detail. If the audience are beginners, it's enough for them to get a tool like gnu-coreutils done. And they will be happy. Questions will arise and we can answer them with: `sure this is possible, here is an example ...`

@peterjc what was your impression? With planemo everything get's easier, but I doubt we will enter the such complicated cases like data collections?

**Comment by peterjc** [comment]
I'd expect data collections to be a stretch goal - unless most of the participants have already got the basics, it seems too much to cover in the time available. But, as you say, we can give some advice one-on-one.

**Comment by jmchilton** [comment]
I was planning to start the second or "advanced" session off by giving them the minimal bwa wrapper I recently committed and having them add paired collection support and tests - in the middle of writing the tutorial for doing that now. After that I was going to move on top adding conditionals and optional parameters but building that up quickly by just testing the command-lines with assertions.

At least for that first part they will have the answer right there in the tutorial so it should go pretty quick I hope - so I think we will cover collections in a small way at least. The testing stuff will probably be more opened ended and will slow things down.

**Comment by bgruening** [comment]
@jmchilton this sounds good! Have a good flight!

**Comment by Christian-B** [comment]
Excellent examples thanks a lot. Opened my eyes up to much that planemo could do.

Thanks so much for having the virtual machines!!!

One thing I missed is the creation of a tool_dependencies.xml file which would be required for the seqkt and bwa tools to actually work if downloaded from the toolshed.

Also maybe a link to the galaxy log on the desktop of the virtual machine.

**Comment by jmchilton** [comment]
Workshop has been given twice now - once at GCC and once at FoG - made several passes at this. I think the examples are pretty solid now.
