### ISSUE TITLE
Optional configuration file .shed.yml not documented?

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#25]
Reading the code behind ``planemo shed_upload`` it seems that settings like the repository owner and name if not given via command line arguments can be set via a ``.shed.yml`` configuration file (or a global configuration file).

I was unable to find any documentation for this, or an example.

**Comment by jmchilton** [comment]
Documentation now exists http://galaxy-iuc-standards.readthedocs.org/en/latest/best_practices/shed_yml.html though it still needs to be linked inside of planemo commands in places.

**Comment by peterjc** [comment]
Also needs to cover the include/exclude settings, but since the doc source https://github.com/galaxy-iuc/standards/blob/master/docs/best_practices/shed_yml.rst is on another repository we don't need to reopen this issue.

**Comment by jmchilton** [comment]
It also needs to cover the demultiplexing stuff - I think there is an open issue on iuc best practices though.

**Comment by jmchilton** [comment]
https://github.com/galaxy-iuc/standards/issues/6
