### ISSUE TITLE
Manifest approach to building tar balls for shed upload?

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#26]
Reading the ``build_tarball(...)`` function in ``planemo/shed.py`` used in the command ``planemo shed_upload``, currently it appears to essentially collect all the files under the given path.

This should work fine where you have ``.../my_tool/test-data/`` and ``.../my_tool/tool-data/`` under ``.../my_tool/`` as used on https://github.com/galaxyproject/tools-devteam/ and https://github.com/galaxyproject/tools-iuc and https://github.com/bgruening/galaxytools

This will not work where there is a common ``test-data/`` and ``tool-data/`` folder used by multiple tools, as on https://github.com/peterjc/galaxy_blast and https://github.com/peterjc/pico_galaxy

Maybe I should re-arrange my folder structure, but an alternative would be extending the ``build_tarball(...)`` function to allow this to be configured, perhaps with a manifest (white list of files to include)? Perhaps this could go in the ``.shed.yml`` file (see #25)?

See also #24 which would allow a workaround allowing the tar-ball to build outside of the ``planemo shed_upload`` command.

**Comment by jmchilton** [comment]
Some initial work on this by @bgruening here https://github.com/galaxyproject/planemo/commit/cb1c33536df4d50c6cf1db2f2a5584d4f6dcc394.

**Comment by jmchilton** [comment]
More WIP with https://github.com/galaxyproject/planemo/commit/e8d2e227583cb548d9c7c70c89163051066849fa - laying out some abstractions that will hopefully allow decoupling the real directory structure from the target tool shed repository structure.

**Comment by jmchilton** [comment]
@peterjc I think this is done-ish now (still need to improve ``shed_diff`` #141) but ``shed_upload`` allows fairly custom creation of shed repositories from source repositories now - it would be interesting to know if this is enough for your repositories and development workflow:

- https://github.com/galaxyproject/planemo/blob/master/tests/data/repos/multi_repos_flat_configured/.shed.yml
- https://github.com/galaxyproject/planemo/blob/master/tests/data/repos/multi_repos_flat_configured_complex/.shed.yml
- https://github.com/galaxyproject/planemo/blob/master/tests/data/repos/multi_repos_flat_flag/.shed.yml
