### ISSUE TITLE
Unable to update toolshed when I'm not the owner

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/planemo#263]
I'm using an API key for authentication, but I'm not able to update the `rseqc` repository owned by `nilesh`, even though I have permissions to do so. I get the error: "You do not have permission to update this repository". Any workarounds?

**Comment by erasche** [comment]
CC @peterjc who was experiencing this issue as well.

**Comment by peterjc** [comment]
Yes, this came up during the GCC2015 hackathon https://trello.com/b/S4m5seuj/gcc2015-hackathons - but it looks like we didn't log an issue which was an oversight.

In my case, I was trying to update ``ncbi_blast_plus`` owned by ``devteam`` using my API key for ``peterjc`` (I have permissions to upload tar-balls via the web-interface).

**Comment by peterjc** [comment]
Has this been fixed? I was just able to update https://toolshed.g2.bx.psu.edu/view/devteam/blast_datatypes via planemo, and also https://toolshed.g2.bx.psu.edu/view/devteam/ncbi_blast_plus too (Test and main Tool Shed):

```
$ planemo shed_update -t testtoolshed tools/ncbi_blast_plus/ -m "v0.1.05 - Update citation information now GigaScience paper is out"
cd '/mnt/galaxy/repositories/galaxy_blast/tools/ncbi_blast_plus' && git rev-parse HEAD
cd '/mnt/galaxy/repositories/galaxy_blast/tools/ncbi_blast_plus' && git diff --quiet
Repository ncbi_blast_plus updated successfully.
Repository metadata updated.
```

```
$ planemo shed_update -t toolshed tools/ncbi_blast_plus/ -m "v0.1.05 - Update citation information now GigaScience paper is out"
cd '/mnt/galaxy/repositories/galaxy_blast/tools/ncbi_blast_plus' && git rev-parse HEAD
cd '/mnt/galaxy/repositories/galaxy_blast/tools/ncbi_blast_plus' && git diff --quiet
Repository ncbi_blast_plus updated successfully.
Repository metadata updated.
```

**Comment by martenson** [comment]
@peterjc yeah this was resolved on the Galaxy end; thanks for the help @peterjc and @lparsons
