### ISSUE TITLE
tool_init should add tests and citations tags

### ISSUE THREAD

**Issue by Christian-B** [galaxyproject/planemo#265]
tool_init will adds empty requirements, inputs and outputs tags and even a help tags with TODO.

Why could it not also include empty tests and citations  tags.

Even nicer would be to include one or two example citations (Commented out of course)
For example a doi and a bibtex examples.

**Comment by erasche** [comment]
(Or a link to the wiki docs on citations)

**Comment by Christian-B** [comment]
I agree with @erasche suggestion of a link to the wiki docs!

**Comment by nsoranzo** [comment]
:+1: To the empty `<tests>`, not sure about `<citations>`.

**Comment by Christian-B** [comment]
Old issue and as I am no longer using planemo closing
