### ISSUE TITLE
consider having shed_target default to 'local'

### ISSUE THREAD

**Issue by martenson** [galaxyproject/planemo#269]
to prevent accidental updates to MTS

**Comment by lparsons** [comment]
Another option would be to have no default, and require the user to specify.

**Comment by peterjc** [comment]
Either of the above is better than defaulting to the main Tool Shed.

**Comment by erasche** [comment]
:+1:

**Comment by blankenberg** [comment]
Allow setting a default in .planemo.yml, with the default default being no target, which would require always passing --shed_target.

**Comment by erasche** [comment]
xref https://github.com/galaxyproject/planemo/pull/224

**Comment by jmchilton** [comment]
I'm happy to allow specifying a default in ``~/.planemo.yml`` - but I really, really don't want to change the default default. ~~The whole goal of planemo~~... ~~A key goal of planemo~~ One thing I really want to accomplish with planemo is to eliminating the need for local and test tool sheds. The default should be to push to the main shed.

**Comment by martenson** [comment]
I am +1 on what @jmchilton just said.

**Comment by blankenberg** [comment]
I don't feel very strongly about changing the default default, especially considering the future direction (where presumably it would eventually need to be changed back to the MTS). 

If I can set my default, particularly to None/a non-existant toolshed definition and have it always fail quickly when ```--shed_target``` isn't provided, that should be good enough to prevent accidents.

**Comment by peterjc** [comment]
A configurable default in ``~/.planemo.yml`` seems like a sensible compromise since we have people for and against defaulting to the Main Tool Shed.

**Comment by peterjc** [comment]
I just accidentally created some repositories on the main Tool Shed due to the unfortunate default; will update my ``~/.planemo.yml`` but still think we need a less dangerous default.

**Comment by jmchilton** [comment]
:disappointed: :sob:
