### ISSUE TITLE
shed_update succeeds and then reports fail

### ISSUE THREAD

**Issue by martenson** [galaxyproject/planemo#279]
https://gist.github.com/martenson/62140ae2b149d0df0a73

The repo updates ok and then it fails to update description (because .shed.yml does not have it) resulting in somewhat confusing messages being presented to user.

**Comment by jmchilton** [comment]
I think this has been fixed... maybe? Let me know if this is still a problem in more recent versions @martenson.

**Comment by martenson** [comment]
yeah I think https://github.com/galaxyproject/planemo/pull/322/files#diff-f8da753ded15ce21e93b7f64d535aa78R113 improved it
