### ISSUE TITLE
lint --xsd doesn't let user see serialized XML

### ISSUE THREAD

**Issue by mr-c** [galaxyproject/planemo#293]
Would be handy to look at the XML after the macros have been evaluated.

**Comment by peterjc** [comment]
Like ``planemo normalize`` offers? Or something different...

**Comment by mr-c** [comment]
Bingo! Thanks, I forgot about that feature

On Fri, Sep 11, 2015 at 1:49 AM Peter Cock <notifications@github.com> wrote:

> Like planemo normalize offers? Or something different...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/galaxyproject/planemo/issues/293#issuecomment-139490335>
> .
>
-- 
Michael R. Crusoe: Software Research Engineer crusoe@ucdavis.edu
The lab for Data Intensive Biology; University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by mr-c** [comment]
Hmm, the line numbers still don't match the errors I'm seeing.

On Fri, Sep 11, 2015 at 10:25 AM Michael Crusoe <michael.crusoe@gmail.com>
wrote:

> Bingo! Thanks, I forgot about that feature
>
> On Fri, Sep 11, 2015 at 1:49 AM Peter Cock <notifications@github.com>
> wrote:
>
>> Like planemo normalize offers? Or something different...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/galaxyproject/planemo/issues/293#issuecomment-139490335>
>> .
>>
> --
> Michael R. Crusoe: Software Research Engineer crusoe@ucdavis.edu
> The lab for Data Intensive Biology; University of California, Davis
> https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe
>
-- 
Michael R. Crusoe: Software Research Engineer crusoe@ucdavis.edu
The lab for Data Intensive Biology; University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by jmchilton** [comment]
Closing this because that is what the ``normalize`` is for, not sure about the line number thing - feel free to create a new issue. Thanks all.
