### ISSUE TITLE
lint --xsd error

### ISSUE THREAD

**Issue by mr-c** [galaxyproject/planemo#298]
More of an FYI, as I know this is experimental:

```
Applying linter tool_xsd... FAIL
.. ERROR: Invalid tmpWhVRKx found. Errors [/tmp/tmpWhVRKx:95: element has_text: Schemas validity error : Element 'has_text': This element is not expected. Expected is ( has_line ).
/tmp/tmpWhVRKx:110: element has_text: Schemas validity error : Element 'has_text': This element is not expected. Expected is ( has_line ).
/tmp/tmpWhVRKx fails to validate
```
According to https://wiki.galaxyproject.org/Admin/Tools/ToolConfigSyntax#A.3Cassert_contents.3E_tag_set_.28functional_tests.29
`has_text` is valid and there is no `has_line`

**Comment by jmchilton** [comment]
This particular problem is resolved, obviously the XSD has A LOT of work left to do.
