### ISSUE TITLE
planemo shed_diff should return 1 if not in tool shed

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#300]
Currently ``planemo shed_diff`` returns 0 for no file differences, and 1 if there are file differences (see #299 on if this should also look at the meta-data as well).

If a tool does not (yet) exist in the target tool shed, surprisingly I get return code 0:

```
$ planemo --version
planemo, version 0.14.1.dev0
$ planemo shed_diff --fail_fast -t toolshed tools/mira4_9/ ; echo "Return code $?"
Repository [mira4_9] does not exist in the targeted Tool Shed, can't do shed_diff
Return code 0
```

To me this counts as a major difference, so I expect a return code of 1 here. This is important if using ``shed_diff`` as a filter to look for tools which need uploading/updating on the target tool shed.

**Comment by jmchilton** [comment]
Agreed completely here @peterjc, definitely a bug :smiley_cat: :bug: :beetle:.

**Comment by jmchilton** [comment]
Actually ``diff`` returns a 2 - so I did that instead - https://github.com/galaxyproject/planemo/commit/c1facd04c50e2b7e05ee4a5ba41e961135f0dafb. Exit code handling is a lot better now I think.

**Comment by peterjc** [comment]
That sounds good, thanks :)

**Comment by jmchilton** [comment]
Think this is resolved now, closed.
