### ISSUE TITLE
Inconsistent text/markdown report from planemo test

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#306]
I've been trying the new ``planemo test`` text and markdown report from #304 by @erasche (requested in #302).

```
$ planemo --version
planemo, version 0.14.1.dev0
```

```
$ rm -f example.* && planemo test --test_output_text example.txt --test_output_markdown example.md tools/mira4_9/
...
galaxy.jobs.handler INFO 2015-09-21 11:22:04,985 job handler stop queue stopped
There were problems with 7 test(s) - out of 7 test(s) executed. See tool_test_output.html for detailed breakdown.
mira_4_9_bait[0]: failed
mira_4_9_bait[1]: failed
mira_4_9_bait[2]: failed
mira_4_9_bait[3]: failed
mira_4_9_bait[4]: failed
mira_4_9_bait[5]: failed
mira_4_9_bait[6]: failed
```

So this failed, yet:

```
$ cat example.txt 
There were problems with 7 out of 7 test(s) executed.

mira_assembler.test_tool_000000: success
```

and:

```
$ cat example.md 
# Tool Test Results (powered by Planemo)

## Executive Summary

| Test State | Count |
| ---------- | ----- |
| Total      | 7 |
| Passed     | 0 |
| Error      | 0 |
| Failure    | 0 |
| Skipped    | 0 |


## Detailed Results

### functional.test_toolbox.TestForTool_mira_assembler.test_tool_000000

Job Passed
```

Part of the output seems to related to an older successful test of ``tools/mira3/`` instead.

This was using https://travis-ci.org/peterjc/galaxy_mira/ specifically commit 32618785666d20326802d138fc482a071c2bd9ae on the ``planemo_ci`` branch.

**Comment by erasche** [comment]
Oh dear, looks like my markdown template is wrong. Well. Should be a quick fix, will PR when I get into the office

**Comment by erasche** [comment]
Sorry @peterjc, "PR when I get into the office" turned into "Oh, crap, there's a grant due (today) and y'all are so far behind where you're supposed to be." 

Will get this fixed for you shortly

**Comment by peterjc** [comment]
No rush - I'm tinkering with another area of planemo at the moment anyway. Thanks.

**Comment by peterjc** [comment]
@erasche I've scanned over the commit https://github.com/galaxyproject/planemo/commit/7e4db984d9a8ebea1a9f24b2bdc83856133725c4 , but don't immediately see where ``raw_data`` could be getting mixed up...
