### ISSUE TITLE
Demultiplexing error

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#313]
```
cd '/home/hxr/work/tools-iuc/tools/hmmer3' && git rev-parse HEAD
cd '/home/hxr/work/tools-iuc/tools/hmmer3' && git diff --quiet
Repository hmmer_hmmemit updated successfully.
cd '/home/hxr/work/tools-iuc/tools/hmmer3' && git rev-parse HEAD
cd '/home/hxr/work/tools-iuc/tools/hmmer3' && git diff --quiet
Repository hmmer_hmmconvert updated successfully.
cd '/home/hxr/work/tools-iuc/tools/hmmer3' && git rev-parse HEAD
cd '/home/hxr/work/tools-iuc/tools/hmmer3' && git diff --quiet
Unexpected response from galaxy: 400: {"err_msg": "Enter the required repository name.", "err_code": 400008}
Repository [None] does not exist in the targeted Tool Shed.
cd '/home/hxr/work/tools-iuc/tools/hmmer3' && git rev-parse HEAD
cd '/home/hxr/work/tools-iuc/tools/hmmer3' && git diff --quiet
Repository hmmer_nhmmscan updated successfully.
```

hard to tell which tool exactly produced that error.

**Comment by erasche** [comment]
Followed by:

```
Could not update suite_hmmer_3
Unexpected response from galaxy: 500: {"content_alert": "", "err_msg": "The repository_dependencies.xml file contains an invalid <repository> tag.  Unable to locate repository with name None and owner iuc.  "}
```

**Comment by erasche** [comment]
Okay, it's trying to include a `macros.xml` file.

**Comment by erasche** [comment]
Ignoring the macros.xml file in the .shed.yml produces a failure:

```
Unexpected response from galaxy: 500: {"content_alert": "", "err_msg": "Metadata may have been defined for some items in revision '5cbcb382871e'.  Correct the following problems if necessary and reset metadata.<br/><b>hmmemit.xml<\/b> - This file refers to a missing file <b>macros.xml<\/b>.  Upload a file named <b>macros.xml<\/b> to the repository to correct this error.<br/>"}
```

Seems like a bug in tool file discovery process.

**Comment by erasche** [comment]
@jmchilton where might I go about patching this? I'm not at all familiar with the demultiplexing and shed upload. Any pointers would be greatly appreciated :)

**Comment by jmchilton** [comment]
Everything interesting I think happens below ``_realize_effective_repositories``  in the call stack - https://github.com/galaxyproject/planemo/blob/master/planemo/shed/__init__.py#L719. I'll try myself to find some time to look at this, since you know I promised I would.

**Comment by jmchilton** [comment]
I know I promised to work on this, but I'm not sure it will be possible before mid November anymore, sorry. I have to get ready for Genome Informatics and Festival of Genomics so I should focus on Galaxy and workflows for the time being.

**Comment by erasche** [comment]
OK. Not a problem. Thanks for the update. khmer and hmmer updates are blocking on this, so maybe I'll find time for it soon.

**Comment by jmchilton** [comment]
Maybe a more pressing weekend project than Galaxy admin configuration documentation (snore) and more fun :wink:.

**Comment by natefoo** [comment]
Snore? The most exciting of weekend projects!

**Comment by erasche** [comment]
I've tracked it down to something that *looks* like a Galaxy bug.

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/loader_directory.py#L43

Is picking up tool dependencies because someone chose to write `'<tool'` instead of `'<tool '`.
