### ISSUE TITLE
Complete action coverage in planemo dependency_script 

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#318]
The initial `planemo dependency_script` implementation https://github.com/galaxyproject/planemo/commit/f798c7e29b2276ce68b828e72fc6a6460c73792b (see #303 and #310) only covers some of the actions available in a `tool_dependencies.xml` file.

This issue is to complete that, especially the actions to setup R/Python/Perl environments.

Note thus far `planemo dependency_script` has avoided worrying about dependency chains - full support of some actions may be impossible without that?

**Comment by mdshw5** [comment]
Support of `autoconf` actions would be helpful, since many builds will need this e.g.: https://travis-ci.org/mdshw5/sra-tools-galaxy/builds/91434933

**Comment by bgruening** [comment]
ping @peterjc - can we close out all the dependency_script issues now that we have conda?
Thanks a bunch for your work here! This was very needed, but I feel the approach with conda is more stable.

**Comment by peterjc** [comment]
I would agree with the shift to conda there is little reason to work on ``dependency_script`` except so far as it may help with writing conda recipes based on tool shed XML recipes.

I am still using ``dependency_script`` in my TravisCI tool testing, but am planning to shift over to conda.

With all that said, yes, let's close this issue as a "won't fix".
