### ISSUE TITLE
Multiple env.sh files from planemo dependency_script?

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#319]
The initial `planemo dependency_script` implementation f798c7e (see #303 and #310) produces a single `dep_install.sh` and `env.sh` script even when called on multiple `tool_dependencies.xml` files. The simplistic usage model is to run `bash dep_install.sh` and `source env.sh` prior to running Galaxy or any Galaxy tests.

In general do we need a way to produce separate `env.sh` scripts and put them where Galaxy will use automatically them prior to tool execution? [I don't know how that works currently...]
## 

The simple model can work fine, e.g. peterjc/galaxy_blast@a1303d7 and https://travis-ci.org/peterjc/galaxy_blast/builds/84294442 uses `planemo dependency_script` to run two `tool_dependencies.xml` files to install BLAST+ 2.2.31 and Blast2GO.

However, if I wanted to also install BLAST+ 2.2.30 there would be a clash of binary names. There is a similar problem with https://github.com/peterjc/galaxy_mira where I want to  install three versions of the MIRA assembly suite, which all have a binary `mira` and thus cannot simply be put in the same `$INSTALL_DIR`. Calling `planemo dependency_script` three times with different `$INSTALL_DIR` paths works.

However, if `$PATH` was used to find the `mira` binary this still present a problem as there are competing answers - likewise with different versions of BLAST+ on `$PATH`.

For MIRA, I am already use `$MIRA3`, `$MIRA4` and `$MIRA4_9` to hopefully avoid this...

**Comment by jmchilton** [comment]
``planemo test --tool_dependency_dir <dep_dir>``

Arrange ``env.sh`` files like ``<dep_dir>/mira/<version>/env.sh`` and make sure ``<version>`` matches the requirements.

Does that make sense?

**Comment by peterjc** [comment]
Thanks John. Let's take a full example https://toolshed.g2.bx.psu.edu/view/peterjc/package_mira_3_4_1_1 whose  ``tool_dependencies.xml`` file is:

```
<?xml version="1.0"?>
<tool_dependency>
    <package name="MIRA" version="3.4.1.1">
        <install version="1.0">
            <actions_group>
...
```

So ``planemo dependency_script --tool_dependency_dir <dep_dir> -r packages/`` would look at ``packages/package_mira_3_4_1_1/tool_dependencies.xml`` and create  ``<dep_dir>/MIRA/3.4.1.1/env.sh`` (etc if run on multiple packages).

That should then be detected by users of http://toolshed.g2.bx.psu.edu/view/peterjc/mira_assembler because its tool XML file has a matching ``<requirement>`` tag:

```
<tool id="mira_assembler" name="Assemble with MIRA v3.4" version="0.0.11">
    <description>Takes Sanger, Roche, Illumina, and Ion Torrent data</description>
    <requirements>
        <requirement type="binary">mira</requirement>
        <requirement type="package" version="3.4.1.1">MIRA</requirement>
    </requirements>
...
```

For the installation script, is there any reason to generate one bash script per package? Or is the current single output file enough?

**Comment by peterjc** [comment]
@jmchilton your outline above matches what is described on https://wiki.galaxyproject.org/Admin/Config/ToolDependencies - thanks.

Is there an optional heirachy on top of that used by the Tool Shed installation? e.g. looking at the ``tool_dependency_dir`` set in our ``galaxy.ini``, we have things like ``<dep_dir>/bwa/0.5.9/devteam/package_bwa_0_5_9/ec2595e4d313/env.sh `` or ``<dep_dir>/FastQC/0.11.2/devteam/package_fastqc_0_11_2/4b65f6e39cb0/env.sh`` -- the extra bits look like the Tool Shed owner, repository name and revision hash.

**Comment by jmchilton** [comment]
The tool shed dependency resolution requires entries in the install database so it is no amenable to approaches like this, I would consider them a black box and not worry about 'em.

**Comment by peterjc** [comment]
So both Galaxy itself and ``planemo test --tool_dependency_dir <dep_dir> ...`` will find and use ``<dep_dir>/<name>/<version>/env.sh``?

**Comment by jmchilton** [comment]
By default yes, unless you explicitly override the dependency resolution strategy in either case.

**Comment by peterjc** [comment]
Good. We have a plan then :+1: 

--

Separately it looks like for ``https://github.com/peterjc/galaxy_mira`` while I do set ``$MIRA3`` in the package, the MIRA 3 wrapper is only using ``$PATH`` to find the ``mira`` binary. So I can either implement this ``planemo dependency_script`` enhancement, or revise the MIRA 3 wrapper to check ``$MIRA3`` before falling back on ``$PATH`` ;)

**Comment by peterjc** [comment]
Aside: I solved the MIRA issue by manually changing the install order, see https://github.com/galaxyproject/planemo/commit/f798c7e29b2276ce68b828e72fc6a6460c73792b#commitcomment-13669301 and the working commit:  peterjc/galaxy_mira@0d41761 and https://travis-ci.org/peterjc/galaxy_mira/builds/84351148

**Comment by peterjc** [comment]
See also this nice blog post from Peter Van Heusden http://pvh.wp.sanbi.ac.za/2015/10/09/how-galaxy-resolves-dependencies-or-not/

**Comment by bgruening** [comment]
@peterjc this can be closed correct?

**Comment by peterjc** [comment]
Yes, as per our discussion on #318, with Galaxy moving from its legacy XML based packages to conda, there is little reason to put further work into ``planemo dependency_script``.
