### ISSUE TITLE
Update TravisCI Docs

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#338]
README should probably be updated with more standard examples of using TravisCI with projects - including descriptions and links to tools-devteam, tools-iuc, and Peter's repos.

**Comment by souravsingh** [comment]
Is the issue open?I would like to work on this.

**Comment by peterjc** [comment]
Great - see also https://github.com/galaxyproject/planemo/labels/docs%20missing for other missing documentation issues.
