### ISSUE TITLE
Add "Methylation" to planemo shed_init categories 

### ISSUE THREAD

**Issue by nitesh1989** [galaxyproject/planemo#348]
Methylation would be nice if it were added. More tools are coming up in that area now.

```Error: Invalid value for "--category": invalid choice: Methylation. (choose from Assembly, ChIP-seq, Combinatorial Selections, Computational chemistry, Convert Formats, Data Managers, Data Source, Fasta Manipulation, Fastq Manipulation, Genome-Wide Association Study, Genomic Interval Operations, Graphics, Imaging, Metabolomics, Metagenomics, Micro-array Analysis, Next Gen Mappers, Ontology Manipulation, Phylogenetics, Proteomics, RNA, SAM, Sequence Analysis, Statistics, Systems Biology, Text Manipulation, Tool Dependency Packages, Tool Generators, Transcriptomics, Variant Analysis, Visualization, Web Services)```

**Comment by martenson** [comment]
I think Planemo loads categories from MTS's API

**Comment by nitesh1989** [comment]
Then we can just add a category to the MTS API then. I'll get on that.

**Comment by martenson** [comment]
I can do that for you. Give me name and description.

**Comment by nitesh1989** [comment]
"Epigenetics" is a better category apparently according to Mike. That will encapsulate a bunch of tools in along with methylation.

**Comment by martenson** [comment]
And the descripyion?

**Comment by nitesh1989** [comment]
"Tools for analyzing Epigenetic/Epigenomic datasets"

**Comment by bgruening** [comment]
@martenson Not sure about fetching the categories. See this one: https://github.com/galaxyproject/planemo/pull/285/files

**Comment by erasche** [comment]
yep. they are hard coded in planemo.

**Comment by martenson** [comment]
It is hardcoded so it works offline I think. Nevertheless the category needs to go to TS first. Done.
