### ISSUE TITLE
Fix tests for wheel fallout.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#352]
Fix planemo for wheel fallout?

**Comment by erasche** [comment]
![fallout](http://static.tumblr.com/edfdee9c99f9ee4bea607ac7786f6a86/qmekzxj/TJ5mpemsc/tumblr_static_3263-vault-boy-approves_zpsd28b23c1.gif)

**Comment by jmchilton** [comment]
This this is done, still failing tests related to CWL which got merged when tests were broken.
