### ISSUE TITLE
Add tests for #350

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#353]
https://github.com/galaxyproject/planemo/pull/350

**Comment by jmchilton** [comment]
Made some modifications to get the seqtk_seq.xml tool generated by ``tool_init`` in the docs to pass. That might a good think to test also.

**Comment by jmchilton** [comment]
Added a bunch of tests for this last week, closing.

**Comment by erasche** [comment]
THanks @jmchilton, I appreciate it. :)
