### ISSUE TITLE
Refactor of XUnit support

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#357]
As everyone else realises how _awesome_ XUnit support is with Jenkins, we need to refactor the code into something more sensible.

My plans are:
- an XUnitRerportBuilder class which has convenient methods like `.error()`, `.ok()`, `.skipped()`
- Proper XML construction rather than worrying about escaping various snippets.

XUnit and logging messages are increasingly filling very similar roles, so maybe there's a way we could handle both in one place? E.g. how `lint_ctx` gets tossed around, maybe we need to have a replacement `lint_ctx` which talks to TWO backends, the XURB backend and the `planemo.io` backend, dispatching messages to their appropriate locations.

Would that make sense @jmchilton? Are there places where this wouldn't be appropriate? Just wanted to have a short engineering discussion in this issue :)

**Comment by jmchilton** [comment]
This would be awesome.

If you look at the planemo/io.py changes in https://github.com/galaxyproject/planemo/commit/49c5c1e68901decc30ef5237ae31825999cef681 I'm also trying to figure out how to tame planemo's I/O for reasons unrelated to XUnit.

The XUnit abstraction would be great though, it would let us swap out the backend and build useful JSON APIs (REST/cli/etc...).

**Comment by erasche** [comment]
Okay, if that abstraction gets the jmchilton seal-of-approval then I'll go ahead an implement it in the next few weeks. :)

**Comment by erasche** [comment]
Not doing linting in jenkins anymore, uninteresting to current users.
