### ISSUE TITLE
Python 2.6 support broken in 3rd party dependencies

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#366]
Since Galaxy still supports Python 2.6 https://wiki.galaxyproject.org/Admin/Python I assumed this was a goal with Planemo as well?

Planemo now pulls in ``cwltool`` and ``schema_salad``, but they do not (yet?) support Python 2.6 with syntax errors at install time from their use of dictionary comprehensions.

This used ``cwltool-1.0.20151104062100.tar.gz`` and ``schema_salad-1.0.5.tar.gz``

**Comment by jmchilton** [comment]
CWL support will not be available for Python 2.6 or Python 3 at this time. Galaxy support in planemo should continue to work for Python 2.6.

**Comment by peterjc** [comment]
Great - that's a neat solution, thanks.
