### ISSUE TITLE
Issues with HTML output not reporting correct # of tests.

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#381]
![planemo](https://cloud.githubusercontent.com/assets/458683/11325578/f84ea192-9116-11e5-8067-a337663b6bc1.png)

https://gist.github.com/erasche/c771b550775f75aa59e9

**Comment by jmchilton** [comment]
You json file is invalid json - is it the raw contents or a copy and paste problem? fdce74cae2ba65df2f9e23025f15a4832e5ae12c will improve the error message for this if that gist is the actual file. Do you have the planemo test output, it should have had the older cryptic warning about Galaxy being too old...

**Comment by erasche** [comment]
Hmph! That may have been a copy and paste problem. Sorry about that.

"the planemo test output" = the html file? or ... ?

**Comment by jmchilton** [comment]
@erasche The json file.

**Comment by erasche** [comment]
@jmchilton will re-run and try and get you a valid one.
