### ISSUE TITLE
Target galaxy master instead of dev

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#383]
Thoughts?

xref: https://github.com/galaxyproject/planemo/issues/382#issuecomment-158974036

**Comment by erasche** [comment]
On the surface, from just the title and the barest bit of context from 382, this feels like the wrong way to solve the issue. I don't see why there should be a difference in testing against dev and master.

If I wanted to target one vs the other I can clone a copy locally.

**Comment by jmchilton** [comment]
So the pros and cons are:

Pros of targeting dev: Get the newest features (in planemo and in tools under test - e.g. datatypes, https://github.com/galaxyproject/galaxy/pull/1113, https://github.com/galaxyproject/galaxy/pull/1153)  fastest by default, more planemo users will find Galaxy bugs prior to releases.
Pros of targeting master: Planemo will be more stable by default.

Obviously planemo can be used to target either, but ``--install_galaxy`` (now implicit) has become so fast that I think most people do not actually ever configure a Galaxy.

**Comment by peterjc** [comment]
I'm still doing the Galaxy installation myself in ``.travis.yml``, targetting the ``dev`` and ``master`` branches via a build matrix. Replacing this boiler-place with a planemo call would be nice.

Could ``--install_galaxy`` be configurable with a Galaxy tag (i.e. release) or branch name to fetch?

**Comment by bgruening** [comment]
+1 for targeting a stable release by default. We should realise that planemo made tool development so easy that everyone can use it and we should deliver a stable experience to them and not expecting them to fix Galaxy bugs along the lines.
But we should point more advanced developers to the fact that you can run planemo against every Galaxy installation you want, including dev and your own patched version.
