### ISSUE TITLE
shed_lint does not work

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/planemo#385]
This seems to be a planemo bug:

https://travis-ci.org/galaxyproject/tools-iuc/builds/93060342

I hope I can look at it tomorrow. Late here ...

**Comment by bgruening** [comment]
Ok this one is due to a click update and this change:
https://github.com/mitsuhiko/click/blob/master/CHANGES#L34

We should consider to bind all dependencies <= a specific version, otherwise it will break all CI tests we have in all our repositories. Like it happened now.

**Comment by bgruening** [comment]
My assumption is that https://github.com/galaxyproject/planemo/blob/master/planemo/options.py#L272 should be removed to work nicely with the latest click version.
Or we remove the nargs=-1. I think a recursive flag would be better and with this we could have the nice 
`.` default.

@nsoranzo @erasche any opinions?

**Comment by erasche** [comment]
This might be more @jmchilton's area than anyone else's. I'm not as familiar with click or what that option stanza is supposed to be representing, but if you have alternatives that function the same that'd be great.

**Comment by jmchilton** [comment]
Seems like just removing the default would be fine, it looks like the callback will set up the correct behavior without an explicit default.

**Comment by jmchilton** [comment]
Tests seem to pass so I pushed out the update. I will cut a new release sometime before the hackathon starts - there are a lot of good enhancements in master that have yet to be released.

**Comment by bgruening** [comment]
Thanks @jmchilton. Please note that I have pinned the planemo version already to 0.19 for the hackathon. We need to revert this if you push a new release. Sorry. I don't wanted to bother you at the weekend.

**Comment by jmchilton** [comment]
I thought 0.19 doesn't work with Galaxy dev (https://github.com/galaxyproject/planemo/commit/25ef0d5), are you setting up Galaxy manually for the demo?

**Comment by bgruening** [comment]
I should get more sleep. I meant that I pinned click ... we can remove this if we want from tools-iuc.
