### ISSUE TITLE
Export workflow for publishing command

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#389]
This is awesome: https://github.com/bgruening/galaxytools/tree/master/workflows/ncbi_blast_plus/find_three_genes_located_nearby 

I think we can all agree. I'm lazy as heck, so I'd like to see a planemo command that does this (and maybe uploads to myexperiment as well?)
- [ ] extract some test data from a specified history?
- [ ] extract .ga file
- [ ] phantomjs to extract .png of workflow given your credentials
- [ ] citation section including all tools used
- [ ] various other sections (sample data, availability, etc)
- [ ] license
- [ ] dependencies, repository_dependencies.xml
- [ ] myExperiment integration
  - [ ] handle upload
  - [ ] copy citations
  - [ ] etc?

cc @bgruening

**Comment by bgruening** [comment]
I will see if I find my scripts.

**Comment by peterjc** [comment]
It was an nicely complicated workflow example - having planemo do some of this would help with sharing workflows between instances.
