### ISSUE TITLE
Planemo publishing .svn repository

### ISSUE THREAD

**Issue by gwenandres** [galaxyproject/planemo#391]
Hello, 

I don't know if it is a real bug...
It seems that when you publish your tool with planemo (at least shed_create), .svn directories (and their content) are not removed. Furthermore these directories are in a read-only state; so I have errors when I want to update my directory.

Maybe you can help me on this...
Thanks a lot, 

Gwendoline

**Comment by jmchilton** [comment]
@gwenandres thanks for the bug report, I think 99fa29e should fix it. Hopefully I'll find some time to publish a new version of planemo soon.
