### ISSUE TITLE
Planemo chokes with Python 2.7.11

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/planemo#409]
The current planemo version on pip does not work well with Python 2.7.11

The problem is quite easy to solve as it is caused by an old kombu dependency. Check https://github.com/celery/kombu/issues/545 for the problem

An upgrade of the kombu dependency to a newer version might work

Another option is to downgrade to 2.7.10 (which is what I did)

**Comment by jmchilton** [comment]
Kombu 3.0.30 shouldn't have this issue and it is what should be installed with Galaxy 16.01. I think this will be fixed when the new version of Galaxy is released.

**Comment by jmchilton** [comment]
With the release for 16.01, I believe this should be fixed. Please feel free to reopen if this is not the case.
