### ISSUE TITLE
test run creates an empty 'user' folder

### ISSUE THREAD

**Issue by martenson** [galaxyproject/planemo#41]
When a test is run with Planemo and the tool directory contains a `tool-data` folder I suspect that the test run will create an empty `user` directory under it.

**Comment by jmchilton** [comment]
Thanks for the bug report! Should be fixed with galaxy-central ff4e911 (https://bitbucket.org/galaxy/galaxy-central/commits/ff4e9117b39ddaff106d1c44792eb6fbcc7c0256).
