### ISSUE TITLE
Unwanted installation of cwltool under Python 2.6

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#411]
Filing this as a dedicated issue, previously raised as https://github.com/galaxyproject/galaxy/issues/1571 and discussed on https://github.com/galaxyproject/planemo/pull/405 

Planemo's ``setup.py`` does have this:

```python
# Only import cwltool for Python 2.7.
if sys.version_info[0] == 2 and sys.version_info[1] >= 7:
    requirements.append("cwltool")
```

Sadly sometimes ``cwltool`` is loaded anyway - and breaks with unsupported Python 2.6 syntax, e.g. https://travis-ci.org/peterjc/galaxy_blast/builds/107255015 or from https://travis-ci.org/peterjc/galaxy_mira/jobs/108283439

```
$ source ~/virtualenv/python2.6/bin/activate
$ python --version
Python 2.6.9
$ pip --version
pip 6.0.7 from /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages (python 2.6)
$ echo "Using planemo lint to check for obvious tool errors"
Using planemo lint to check for obvious tool errors
$ pip install planemo
Collecting planemo
  Downloading planemo-0.22.2-py2.py3-none-any.whl (213kB)
    100% |################################| 217kB 2.0MB/s 
Collecting cwltool (from planemo)
  Downloading cwltool-1.0.20160203221531.tar.gz (78kB)
    100% |################################| 81kB 4.3MB/s 
    /tmp/pip-build-sCleds/cwltool/setup.py:12: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
Collecting six>=1.7.0 (from planemo)
  Downloading six-1.10.0-py2.py3-none-any.whl
...
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/cwltool/main.py", line 391
    job_order_object.update({namemap[k]: v for k,v in cmd_line.items()})
                                             ^
SyntaxError: invalid syntax
```

So why did ``pip install planemo`` install ``cwltool``?

**Comment by jmchilton** [comment]
@peterjc I think https://github.com/galaxyproject/planemo/pull/405/files might fix this - it just hasn't been pushed to pypi yet. Is that possible?

**Comment by peterjc** [comment]
From my point of view trying #405 is worth a shot, and I can easily re-trigger the failed TravisCI builds to check if it fixed them. I don't know enough about the dependencies to judge if there could be unwanted side effects...

**Comment by jmchilton** [comment]
Merged and pushed a release, testing locally it seems like cwltool is no longer installed under Python 2.6.

xref https://github.com/common-workflow-language/galaxy/issues/19

**Comment by peterjc** [comment]
Confirming that this has fixed my TravisCI failures (re-running some now). Thanks!
