### ISSUE TITLE
Error on "Building Galaxy Tools Using Planemo"

### ISSUE THREAD

**Issue by methylome** [galaxyproject/planemo#417]
After adding the advanced menu, the following for the command line on [https://planemo.readthedocs.org/en/latest/writing_standalone.html](https://planemo.readthedocs.org/en/latest/writing_standalone.html) is wrong
``              $shift_quality``
``              #if $settings.advanced == "advanced"``
It should be changed to
``              #if $settings.advanced == "advanced"``
``              $settings.shift_quality``
Thanks,
Justin.

**Comment by jmchilton** [comment]
Fixed I believe, thanks Justin!
