### ISSUE TITLE
Cannot Create new Repos in a toolshed with more than one user

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/planemo#437]
since toolshed/api/users gives a list of all users, and the tsi.user just gives the first one off the list.

Broken in https://github.com/galaxyproject/planemo/pull/425

Locally in testing, I could have the toolshed put the current user at the top of the list and planemo will work correctly, but this is not ideal nor backwards compatible to older versions of ToolSheds.

**Comment by jmchilton** [comment]
Well this sucks... we need an API endpoint to fetch the username for an API key I guess.

**Comment by bgruening** [comment]
Can confirm this one. Uploading to the TS is broken.

**Comment by mvdbeek** [comment]
Well, I can't create any repos eithe. Let's revert #425 for the time being.

**Comment by martenson** [comment]
So Planemo can't create a TS repo for 27 days?

**Comment by jmchilton** [comment]
:( - I'll revert the change on th 0.24.1 and release a 0.24.2.

**Comment by jmchilton** [comment]
I think a botched the upload process in some ways but the final product might be fine - anyone want to check 0.24.2 https://pypi.python.org/pypi/planemo?

**Comment by mvdbeek** [comment]
@jmchilton 
Seems ok, new version installd fine and repo creation works.

**Comment by martenson** [comment]
thank you @jmchilton !

**Comment by bgruening** [comment]
Works for me as well! Thanks!
