### ISSUE TITLE
Conda to tool_dependencies.xml command

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/planemo#452]
I was thinking it would be pretty neat if planemo supported a workflow where it would let galaxy/conda resolve the tool dependencies, write a conda environment file (and/or a zip of the environment) and a tool_dependencies.xml file. This way tool authors could focus on conda dependencies, knowing that there is a single command to turn that into old-style tool_dependencies.xml.

Any thoughts on that?

**Comment by bgruening** [comment]
The conda environment file (requirements.txt) is on the roadmap for 16.07. The compressed environment is a great idea, I just don't think it's worth the effort. I really hope we can make the transition as fast as possible so that the IUC recommends the usage of conda by 16.07.

**Comment by jmchilton** [comment]
I'm with @bgruening here - if you want to the work @mvdbeek I'm sure Galaxy and planemo would love to have this - but even medium term I think conda is the way to go.

**Comment by nsoranzo** [comment]
@mvdbeek Close?

**Comment by mvdbeek** [comment]
Absolutely. Very happy how things have turned out.
