### ISSUE TITLE
Installation of planemo 0.25.0 via Homebrew fails

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/planemo#473]
Looks like this is really a problem with a dependency, but perhaps updating the requirements.txt could fix this?

```
Already downloaded: /Library/Caches/Homebrew/planemo--ruamel.yaml-0.11.11.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/planemo/0.25.0/libexec/vendor --single-version-externally-managed --record=installed.txt
Last 15 lines from /Users/lparsons/Library/Logs/Homebrew/planemo/23.python:
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2395, in require
    reqs = self.dist.requires(self.extras)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2640, in requires
    dm = self._dep_map
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2629, in _dep_map
    if invalid_marker(marker):
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1427, in is_invalid_marker
    cls.evaluate_marker(text)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1552, in _markerlib_evaluate
    env = cls._translate_metadata2(_markerlib.default_environment())
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1540, in _translate_metadata2
    for key, value in env
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1539, in <genexpr>
    (key.replace('.', '_'), value)
ValueError: too many values to unpack
```

**Comment by lparsons** [comment]
Wondering about the status of this issue... Is it recommended to install Planemo using Homebrew or simply in a virtualenv using pip?

**Comment by jmchilton** [comment]
I don't have a Mac so this is virtually impossible for me to test and fix. I guess I just need to take some time to rework the install recipe to make that dependency optional. Using pip in the mean time is an option - I'll try to get to this soon though.

**Comment by lparsons** [comment]
@jmchilton I'm not sure I understand how homebrew handles the installation of python deps. Who setup the homebrew formulas? Or can you point me to any docs followed, etc. I might be able to track things down, but it's odd that pip would work when homebrew install wouldn't... What's different?

**Comment by lparsons** [comment]
Looks like the Homebrew formula uses OS X's built in Python and setuptools. I believe there is a [bug in ruamel/yaml](https://bitbucket.org/ruamel/yaml/issues/32/cannot-run-setup-script-on-python-2710) that causes the install to fail. Perhaps require a specific (older) version until this is fixed?

**Comment by jmchilton** [comment]
Does the formula build with 0.10.23?

**Comment by jmchilton** [comment]
Just as a follow up on the other comment - I wrote the formula and based it off the ansible formula in in core (https://github.com/Homebrew/homebrew-core/blob/master/Formula/ansible.rb). I can't say as though I really understand how it works, I just sort of follow the pattern like a template.

**Comment by lparsons** [comment]
Yeah, I took a look at the ansible formula too, and I don't completely understand it (homebrew is oddly complex inside, at least to me), but it does seem to be using the built in Apple python, which is why a `pip` install seems to work and brew doesn't. I don't use the Apple python for anything. At least, that's my theory.
