### ISSUE TITLE
minor cruft to remove after test

### ISSUE THREAD

**Issue by fubar2** [galaxyproject/planemo#48]
After I run (eg)  
`planemo test  --test_output /tmp/foo/testout.html --galaxy_root /home/rlazarus/galaxy  htseqsams2mx.xml`
I see a new file
tool_test_output.json
appear after each test, along with a new test-data/ folder called
test-data/users

Since I test in my git directory :( I suppose I could add these to gitignore, but the directory is not wanted and the json wasn't requested - might as well not save?

**Comment by fubar2** [comment]
Ah whoops - partly duped sorry -> #41

**Comment by jmchilton** [comment]
About the `.json` file - it is awesome and you want it around :). It enables the [`share_test`](http://planemo.readthedocs.org/en/latest/commands.html#share-test-command) command which is great for publishing test reports with pull requests or in commit messages. My thought was both files could be added to a `.gitignore` with one line (and xUnit results as well) by doing `tool_test_outputs*`.

All that said - if you want them gone I have added an option in 21bb463ad6c321bcb669603049a5e89a69766ad9 to allow one to add `default_test_output_json: null` to `~/.planemo.yml` to disable this forever. Documentation updated in 6157d4c3a5fe9a0a5513074cc7a79894fd2a0120 to reflect this.

So I am going to close as a "duplicate" of #41 for the user thing and a "won't fix" on the JSON file. Hope this is okay and thanks for the bug report and for using planemo!
