### ISSUE TITLE
Cache files needed for --install_galaxy.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#49]

**Comment by mr-c** [comment]
+100

**Comment by jmchilton** [comment]
@mr-c I only respond to emoji - so I think you mean :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 

I'll try to find some time to get to this soon - in the meantime the workaround is to clone down galaxy once and setup a ``~/.planemo.yml`` (e.g. with ``planemo config_init``) file to point at it.

**Comment by erasche** [comment]
:+1:

**Comment by jmchilton** [comment]
Now caches Galaxy (https://github.com/galaxyproject/planemo/commit/d755fe7fe4d05b053d5b66603e46901d7d408c92). Not sure how to cache eggs without caching egg problems....

**Comment by erasche** [comment]
Could you leverage the eggless version of galaxy and virtualenvs to avoid dependency problems?

**Comment by jmchilton** [comment]
@erasche I don't know - ``pip install`` is considerably slower than @natefoo style egg fetching.

Nate - any advice on caching eggs across dynamic, transient Galaxy instances? Would pointing the egg directory at some place in home ``~/.planemo/gx_eggs`` work or is that asking for trouble?

**Comment by mr-c** [comment]
Newer versions of pip install use a cache by default and are quite quick.

**Comment by jmchilton** [comment]
@mr-c - Awesome, I'll close this issue and open a new, lower priority one just for the eggs then.
