### ISSUE TITLE
Error with <validator type="dataset_metadata_in_file"/>

### ISSUE THREAD

**Issue by yhoogstrate** [galaxyproject/planemo#490]
Dear Planemo maintainers,

I am testing a tool that makes use of a validator of type `dataset_metadata_in_file`. The idea is to let galaxy check whether a selected db key exists within "liftOver.loc":

```
<tool id="test" name="test" version="1.0">
    <command><![CDATA[
        echo "$input" > "$output"
    ]]></command>

    <inputs>

        <param format="bam" name="input" type="data" label="bam file file">
            <validator type="dataset_metadata_in_file"
                       filename="liftOver.loc"
                       metadata_name="dbkey"
                       metadata_column="0"
                       message="LiftOver mapping (chain file) is not available for the specified build." />
        </param>

    </inputs>

    <outputs>
        <data format="text" name="output" label="${tool.name} on ${on_string}"/>
    </outputs>
</tool>
```

When `planemo test` and `planemo serve` are initiated, it doesn't load the tool and gives the following error:
_galaxy.tools.toolbox.base ERROR 2016-05-28 13:46:33,556 Error reading tool configuration file from path: /path/to/err.xml._

I figured out that this is because the file '/path/to/planemo-galaxy-instace/test-data/liftOver.loc' does not exist and is not automatically derived from '/path/to/test-data/liftOver.loc.sample'. 

---

The direectory tree looks like this:

```
├── err.xml
├── test-data
│   ├── aToB.over.chain
├── tool-data
│   └── liftOver.loc.sample
└── tool_dependencies.xml

```

---

I hope there is an easy solution for this. Let me know if you need more details,

Youri

**Comment by peterjc** [comment]
I think this is what I later filed as issue #530.

**Comment by nsoranzo** [comment]
I think that a solution/workaround is to include `tool_data_table_conf.xml.sample` and `tool_data_table_conf.xml.test` files, where the latter can contain an entry for `${__HERE__}/test-data/liftOver.loc` . See e.g. https://github.com/galaxyproject/tools-devteam/tree/master/tools/bowtie_wrappers

**Comment by yhoogstrate** [comment]
Just to be on the same page, planemo seems to crash also if the test goes through a conditional that does not actually use the table/loc-file but makes only use of files in test-data.

**Comment by peterjc** [comment]
@nsoranzo Regarding the ``.loc`` files and tests (#490/#530), yes, I used a similar workaround in TravisCI for planemo test in another repository: https://github.com/peterjc/pico_galaxy/commit/f84c1f773b07fa1eeba0d0a432ed4c1d899740b1
