### ISSUE TITLE
planemo shed_update should not fail if there is nothing to update

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/planemo#494]
If the repository is already up-to-date the TS will return the following message:

```
Unexpected response from galaxy: 400: {"content_alert": "", "err_msg": "No changes to repository."}
```

This should not be an error as it breaks travis/jenkins integration.

**Comment by nsoranzo** [comment]
:+1: This an issue especially when uploading a suite of tools where not all tools are updated.
