### ISSUE TITLE
interpreter should be marked as deprecated on syntax wiki

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#504]

**Comment by peterjc** [comment]
https://wiki.galaxyproject.org/Admin/Tools/ToolConfigSyntax#A.3Ccommand.3E_tag_set already says "Not recommended anymore" but I must have missed the discussion leading up to this - why? What replaces it as best practice?

**Comment by gregvonkuster** [comment]
Putting it in the command line, so something like this in the case of a Python tool.
```
<![CDATA[
    python $__tool_directory__/my_tool.py
    ...
```
Here is a Java example.
```
<![CDATA[
    java -jar $__tool_directory__/myTool.jar
    ...
```

**Comment by peterjc** [comment]
Thanks. So is this issue resolved (I'm not sure why it was opened on the planemo repository)?

**Comment by jmchilton** [comment]
It just came up at a GCC training so I opened the issue while I was here - thought it would get lost on Galaxy issues. Thanks all!

**Comment by bgruening** [comment]
@jmchilton I think it was perfeclty fine to collect these here. We need to change the tutorial to fit more our standards. I also created a tracking issue here https://github.com/galaxyproject/planemo/issues/502 during the workshop.
