### ISSUE TITLE
planemo travis_init should use planemo lint

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#514]
The ``planemo travis_init`` command at its core will setup a TravisCI configuration which via ``.travis.yml`` will download and run https://github.com/galaxyproject/planemo/blob/master/scripts/travis_test.sh meaning any changes to the master script will immediately take effect on third party Galaxy tool testing.

Right now, apart from the Galaxy and Tool installation magic, the key command is ``planemo test``.

I am proposing that at the start of ``travis_test.sh`` we invoke ``planemo shed_lint`` with ``--fail_level error`` (rather than the more stringent default ``--fail_level warn`` which would likely cause many false positives) as already used in https://github.com/galaxyproject/tools-iuc/blob/master/.travis.yml and https://github.com/galaxyproject/tools-devteam/blob/master/.travis.yml

The lint command is quick, and will flush out problems which can be caught without wasting donated VM run-time on running the test suite.

**Comment by peterjc** [comment]
Would this be acceptable, or too stringent?

``` bash
planemo shed_lint --fail_level error --ensure_metadata --urls -r ${TRAVIS_BUILD_DIR}
```

**Comment by jmchilton** [comment]
Thanks @peterjc!
