### ISSUE TITLE
planemo TravisCI broken for over a month

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#523]
See https://travis-ci.org/galaxyproject/planemo/builds

For well over a month the Planemo TravisCI tests have been failing on the master branch, meaning that all the pull request checks are also failing which limits their usefulness.

https://travis-ci.org/galaxyproject/planemo/builds/146618162 is the current latest master branch tests and these 3 targets failed:

- [x] py27-lint-readme - filed as #524
- [x] py27-lint-docs
- [ ] py27

Going back a little while to https://travis-ci.org/galaxyproject/planemo/builds/139497893 for planemo v0.27.0 and only py27-lint-docs was failing

**Comment by jmchilton** [comment]
This has been fixed - I'll try to be better about this - I'm very sorry.

**Comment by peterjc** [comment]
Hi John - I know how much pain it can be when something external breaks the builds (e.g. update to a dependency), but its great we can use TravisCI again for checking planemo pull request - thank  you 👍
