### ISSUE TITLE
Automate the construction of tool_dependencies.xml Perl modules. 

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/planemo#53]
There is hope to create tool dependencies for Perl packages:

http://nbviewer.ipython.org/github/bgruening/notebooks/blob/master/Perl/perl_package_to_galaxy_tool_dependency.ipynb

Not sure how we can do this in planemo without a dependency on CPAN::FindDependencies.

**Comment by erasche** [comment]
There's now a single [perl script](https://github.com/bgruening/notebooks/blob/master/Perl/perl_modules_to_tool_dependencies.pl) to do [the above](http://nbviewer.ipython.org/github/bgruening/notebooks/blob/master/Perl/perl_package_to_galaxy_tool_dependency_v2.ipynb). Still depends on `CPAN::FindDependencies` which seems like a large dependency for planemo.

**Comment by jmchilton** [comment]
Closing in lieu of conda skeleton.
