### ISSUE TITLE
Planemo KO but TravisCI OK

### ISSUE THREAD

**Issue by lecorguille** [galaxyproject/planemo#533]
I observed this strange behaviour: 
https://travis-ci.org/workflow4metabolomics/nmr_bucketing/builds/142173170#L2795

Planemo return that the test failed but TravisCI return a green status.

It's no more the case. I have just relaunch the TravisCI test and now it return a fail status. Maybe this is fix now on the TravisCI side or on the Planemo one. But I think that I have to report this fact.

**Comment by jmchilton** [comment]
I believe this has been fixed with a bug fix to Galaxy from @nsoranzo  - see for instance https://github.com/galaxyproject/planemo/issues/516.

**Comment by lecorguille** [comment]
Oups! I missed this closed issued. Sorry for that!

**Comment by peterjc** [comment]
Yes, I had this too - see also #516.
