### ISSUE TITLE
`--xsd` should be the default and `--disable-xsd` an option

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/planemo#567]
I think the new xsd option should be the default behavior. @jmchilton any reason not to do so?

**Comment by jmchilton** [comment]
I think we would want to make lxml a required dependency then, which I was hesistant to do before because it required some libraries that weren't commonly installed on base systems but just the other day I did a pip install of it from pypi and got a binary manylinux wheel! It was very painless - so I'm up for this I think.

**Comment by nsoranzo** [comment]
Or even always enabled?

**Comment by bgruening** [comment]
;) I don't think there is any harm in offering a `disable` option for this, e..g if someone ships its own modifications to Galaxy. But the important part is to make it default :)
We can also leave out the disable option!

**Comment by peterjc** [comment]
👍  on making XSD validation the default for linting tool XML files.

**Comment by peterjc** [comment]
Enabling this has flagged all sorts of little things, proving very helpful:

 - https://github.com/peterjc/pico_galaxy/commit/ca5ee85c7efe402d05c02c42a570ce191006ab35
 - https://github.com/peterjc/pico_galaxy/commit/26c0b046e804d0525c4a7aa47b94a3869410d704
 - https://github.com/peterjc/galaxy_blast/commit/f68070f140c7a4811ac3a6e08e62e9b540e7b02a
 - https://github.com/peterjc/galaxy_blast/commit/b31248bf39f97caf0c01a9471dc71abfbf909cf5

**Comment by peterjc** [comment]
Another common error in my tools, using ``required=...`` rather than ``optional=..``,

 - https://github.com/peterjc/pico_galaxy/commit/f7dd42e4c5c0c5d8ec5d0bcbf1e9ff52a8270865
 - https://github.com/peterjc/galaxy_mira/commit/0b9ce339ce9a591da30603cde0fb5f993573a157

**Comment by peterjc** [comment]
There are a number of failures on https://github.com/galaxyproject/tools-iuc with the XSD validation, I will start filing issues...

**Comment by jmchilton** [comment]
@peterjc There is a WIP PR that I think covers all of them https://github.com/galaxyproject/tools-iuc/pull/939. Might be better just to break it up and get some traction on individual parts though.
