### ISSUE TITLE
Allow testing of a subset of tools

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#57]
I have cases where I have a huge directory of tools, and I make changes to a single one. Rather than testing the entire directory again, it'd be nice to run a one-off against a subset of those tools.

**Comment by jmchilton** [comment]
One can lint or test tools individually by supplying the path to the tool - but not yet an aribtrary subset and not the most interesting subset - namely stuff that failed last time.

**Comment by erasche** [comment]
Testing stuff that failed previously would be amazing!

Den 7. februar 2015 23.25.45 WET, skrev John Chilton <notifications@github.com>:
>One can lint or test tools individually by supplying the path to the
>tool - but not yet an aribtrary subset and not the most interesting
>subset - namely stuff that failed last time.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/galaxyproject/planemo/issues/57#issuecomment-73388535

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jmchilton** [comment]
Does 343902dcf08bf01dfbb95d98f4a7b9c32c30d777 satisfy the initial request? If yes, maybe we should make a new issue specifically for re-testing failed tests.

**Comment by erasche** [comment]
+1

søn. 26. apr. 2015, 20.41 skrev John Chilton <notifications@github.com>:
