### ISSUE TITLE
Idea: killing long running tests

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#58]
Not sure if this is a galaxy feature or a planemo feature (so feel free to close), but I've had tools that just hang when given unexpected inputs. Either the test framework or planemo should kill these long running tests rather than hanging forever when you know there's a bimodal distribution of runtimes between "<1 s" and "forever"

**Comment by jmchilton** [comment]
I believe that Galaxy will kill long running tests (maybe after 10 minutes?) - though the timeout should certainly be configurable and documented.

If you have evidence of a tool running truly indefinitely this is a bug and we should fix it in Galaxy.

**Comment by erasche** [comment]
Nah, just a tool that when passed two conflicting arguments would sit there indefinitely (really terrible behaviour). I was trying to get an if/else working in the command template and accidentally passed it the incompatible options a number of times, finding with some frustration I couldn't figure out how to configure timeouts.


Den 7. februar 2015 23.28.28 WET, skrev John Chilton <notifications@github.com>:
>I believe that Galaxy will kill long running tests (maybe after 10
>minutes?) - though the timeout should certainly be configurable and
>documented.
>
>If you have evidence of a tool running truly indefinitely this is a bug
>and we should fix it in Galaxy.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/galaxyproject/planemo/issues/58#issuecomment-73388636

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by erasche** [comment]
Since two years and no other interest, closing.
