### ISSUE TITLE
Mulled Support

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#583]
- [X] Implement linting of conda dependencies against best practice channels.
- [x] Implement flag in planemo (`--mulled_containers`)  to `planemo test` with mulled containers.
- [x] Implement `mull` command in planemo to build local mulled containers for a tool or tools.
  - [x] A planemo-ized variant of the `mulled-build-tool` command distributed with galaxy-lib.
  - [x] Extend with `InvolucroContext` with planemo-isms such as auto installing and prettier reporting.
- [x] Replace guts of mulled/auto-mulled with `mulled-build-channel`.
  - [x] First step is getting mulled scripts into conda... https://github.com/bioconda/bioconda-recipes/pull/2484/files
- [ ] Setup a composite recipes path in auto-mulled (e.g. `composite-recipes/`).
  - [ ] Use `mulled-build-files` to monitor that directory as part of the Travis build process for that repository.
  - [ ] Implement a check for existing published images in `mulled-build-files`.
- [ ] Implement `mulled_register` command to open a PR against `composite-recipes/` for a given tool or tools.
- [ ] Implement linting of mulled container's existence.

**Comment by bgruening** [comment]
Yes, sounds great. I would like to add a `planemo lint` features, which indicates if your tool is Conda and Galaxy ready.

**Comment by jmchilton** [comment]
@bgruening - per your request ``planemo lint --conda_requirements`` is available in https://github.com/galaxyproject/planemo/pull/584.

**Comment by jmchilton** [comment]
Just released planemo 0.34.0 with linting of conda availability, a command to build a mulled container for a tool, and an option to force use of mulled containers with Galaxy for ``test``, ``serve``, ``run``.

**Comment by jmchilton** [comment]
Closing this to continue work in a newer ticket focused on enhancements.
