### ISSUE TITLE
planemo test hangs when test file does not exist

### ISSUE THREAD

**Issue by dwightkuo** [galaxyproject/planemo#587]
planemo test does not return an error (just hangs) to the command line when one of the files required to run the test does not exist (e.g. if HPV.fasta does not exist in the example below):

```
<tests>
   <test>
         <param name="input" value="HPV.fasta"/>
         <output name="output" file="HPV.out"/>
   </test>
<tests>
```

**Comment by jmchilton** [comment]
I just tested this and it didn't do that for me. I got a fairly clear error and the test failed. Is it possible the input is misnamed in your test case there and the input is optional and on an empty input your program hangs (like waiting on stdin for instance)? I guess that is the closet thing I've seen to this before.

**Comment by dwightkuo** [comment]
I've since moved to a newer version of planemo and can no longer replicate this behavior
