### ISSUE TITLE
Inputs in repeat blocks are not recognized in some tools.

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/planemo#589]
Consider the snipped below. If we remove the foo parameter planemo will not test this tool as no dataset could be found in the history. But this tool has as primary element an repeat block and all inputs are nested. With such a tool planemo testing does not seem to be possible. 

```
       <test>
            <param name="foo" value="hicCorrectMatrix_result1.npz.h5" ftype="h5" />
            <param name="region" value="chr3LHet"/>
            <repeat name="tracks">
                <param name="tack_input" value="hicCorrectMatrix_result1.npz.h5" ftype="h5" />
                <param name="title" value="plot_tads_test_1"/>
            </repeat>
            <repeat name="tracks">
                <param name="tack_input" value="hicCorrectMatrix_result1.npz.h5" ftype="h5" />
                <param name="title" value="plot_tads_test_1"/>
            </repeat>
            <output name="outFileName" file="hicPlotTADs_result1.png" ftype="png" compare="sim_size"/>
        </test>
```

**Comment by jmchilton** [comment]
If you use a repeat block in the test param - and there conditionals below the repeat block - you must specify those as well. It is a bit counter-intuitive. Do you have a link for this tool?

**Comment by jmchilton** [comment]
Closing for now - reopen with a link :wink:.
