### ISSUE TITLE
Flag for keeping Galaxy process alive after testing is complete

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#59]
I have a test that's failing with "History does not include a dataset of the required format / build". It would be nice for planemo to offer the ability to keep the galaxy process alive for "interactive" debugging after tests have run and results have printed.

**Comment by erasche** [comment]
Planemo has changed in intervening months, I no longer really need this feature. If anyone else chimes in I'll re-open it, otherwise it seems like I'm the only person who wanted it.

**Comment by erasche** [comment]
I don't remember closing this, but in retrospect it'd still be useful. Sorry! :)

**Comment by jmchilton** [comment]
I'd like to kill and cleanup servers by default, but if you know you will want this functionality ahead of time you can do it:

```
planemo serve <aritfact>
planemo test --engine external_galaxy --galaxy_url http://localhost:9090 <artifact>
```

Feel free to re-open if you want a more comprehensive approach.
