### ISSUE TITLE
Ability to run tests against existing galaxy instances

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#592]
Planemo testing of standalone tools is great and useful, but sometimes production behaves slightly differently due to `$reasons`.

Thus, it would be nice to be able to:
1. Take a tool XML
2. Figure out the test cases and the tool ID
3. Run those tests against a specified galaxy instance via API, for that given tool ID
4. Output JUnit XML

I know run_tests.sh does support this to some extent but planemo is the place I look to for all my tool testing needs, and I haven't had great success with using run_tests.sh in the past.

**Comment by jmchilton** [comment]
I feel like it should be possible to run the tests from the Galaxy GUI. I want to extend the tool-centric UI like in https://github.com/galaxyproject/galaxy/pull/3479 to allow tool testing. I'll try to get to this before the GCC but no promises.

**Comment by bgruening** [comment]
One use case are the imagej wrapper, that needs to have a real job runner, because the local one is sufficient enough. @jmchilton I thought this is already partially implemented with `engines` but needs some fixes ...? Or is this different?

**Comment by peterjc** [comment]
Regarding @jmchilton's comment, see also https://github.com/galaxyproject/galaxy/issues/3136 and https://github.com/galaxyproject/galaxy/issues/3137 for running the tests from the Galaxy UI.

**Comment by jmchilton** [comment]
@bgruening I suspect running tool tests against a stand alone Galaxy isn't possible currently - xref #508 maybe.

Thanks for the links @peterjc!

**Comment by jmchilton** [comment]
Yeah - see #508 - not quite possible with Planemo yet and not quite convenient with Galaxy alone yet. Given the tool describing tours work and the desire for this feature coming up over and over - this GCC Hackathon might be a good time to sit down and hack on features in Planemo/Galaxy that get us there and updates to the tool format to make tests more descriptive.

Still I don't think this will be done before GCC 2017 - so I'm pushing off the milestone - hope that is okay.

**Comment by jmchilton** [comment]
Done!

**Comment by erasche** [comment]
:heart: !!!!

**Comment by martenson** [comment]
Hot Damn! Let's get their consent and test all public servers? 🕺
