### ISSUE TITLE
unable to connect 

### ISSUE THREAD

**Issue by bioinformatics-deakin** [galaxyproject/planemo#596]
When I run Galaxy in VM I get 'unable to connect - Firefox can’t establish a connection to the server at localhost.'

**Comment by Slugger70** [comment]
You need to tell the Galaxy server on the VM to listen on all interfaces. Edit the galaxy.ini file in the galaxy/config directory and set the listen ip to 0.0.0.0 instead of 127.0.0.1.

**Comment by bioinformatics-deakin** [comment]
for info.. that file is here:
/opt/galaxy/galaxy-app/config/galaxy.ini

**Comment by bioinformatics-deakin** [comment]
also, couldn't see a 'listen' IP, I assume you mean: [uwsgi] ?

**Comment by bioinformatics-deakin** [comment]
same error

**Comment by bgruening** [comment]
@bioinformatics-deakin I hope you could solve this. However this does not seem to be an planemo issue and I will close this. Please get in touch with us on gitter or IRC if you need any help.
