### ISSUE TITLE
Planemo and the last conda version?

### ISSUE THREAD

**Issue by lecorguille** [galaxyproject/planemo#604]
Hi,

I have an issue with the version of conda needed by Galaxy 3.19.3. (in a first place with my travis test and in a second place with Galaxy itself).
One of my dependency `bioconductor-camera` take ages to `Solving package specifications: ...............................................` to finally reach the TravisCI time out. I think it's a problem with conflict between R versions.

- To investiguate, I choose a really easy package `r-batch`
```bash
./miniconda2-conda3.19.3/bin/conda create --name __r-batch@1.1_4 r-batch=1.1_4 --override-channels --channel bioconda --channel r --channel defaults --channel conda-forge
```
Installation the `r3.2.2` version
`r-batch:       1.1_4-r3.2.2_0`

- I  have to remove the conda-forge channel
```bash
./miniconda2-conda3.19.3/bin/conda create --name __r-batch@1.1_4 r-batch=1.1_4 --override-channels --channel bioconda --channel r --channel defaults
```
Installation
`r-batch:       1.1_4-r3.3.1_0`

- No  problemo with the last 4.2.12
```bash
./miniconda2-conda4.2.12/bin/conda create --name __r-batch@1.1_4 r-batch=1.1_4 --override-channels --channel bioconda --channel r --channel defaults --channel conda-forge
```
Installation
`r-batch:       1.1_4-r3.3.1_0   bioconda`

I know that there is an issue with the `offline` option needed by Galaxy or something like that.

My question is: is it possible to use the last version of conda now with planemo, or is it still mandatory? According to https://github.com/galaxyproject/galaxy/pull/3227 ?

My last possibility is to alter this file : `.planemo/condarc` and maybe the galaxy.ini `conda_ensure_channels`of my docker image

**Comment by mvdbeek** [comment]
Yeah, I think this has silently been fixed ... I will open a PR.
FYI, the broken series of command used to be (if you have a samtools environment):
```
conda list --name __samtools@1.3.1 --export > env.txt
conda create --name test --unknown --offline --file env.txt
```
That seems to work with conda 4.2.13.

I'm going do some more testing, but we may finally be abe to move on!

**Comment by bgruening** [comment]
xref: https://github.com/conda/conda/issues/2035#issuecomment-220770873

**Comment by abretaud** [comment]
While updating the conda version, it would be cool that `planemo conda_init` installs miniconda3, because it is required by the ./simulate-travis.py script in bioconda.
xref: https://github.com/bioconda/bioconda-recipes/issues/3275
