### ISSUE TITLE
Issue on planemo test for a galaxy tool with many scripts.

### ISSUE THREAD

**Issue by Mataivic** [galaxyproject/planemo#611]
Hello,

I am currently trying to implements some functional tests in several wrappers for galaxy tools. Each tool is run by a main script (in the command section of the wrapper). Then, this script runs other sub-scripts (which do not figure in the wrapper, they are run by python commands with the os module) according to the settled parameters. 

They are written in python and bash but I keep getting a "job in error state", as indicated by the tool_test_output.html, which precises "No such file or directory" errors when it comes to the sub-scripts. Yet, all the scripts are in the same directory and their names are correct.

is it possible that planemo test does not automatically take into account all the scripts of the tool ? Like, only the main script is taken into the virtual environment of the test ? How do I resolve that ? I'm a beginner bioinformatician, not used to planemo and conda yet, so I have trouble to figure that out.

I'd be grateful for some help :)

n.b. : 
  - I use the option --conda_dependencies_resolution with the planemo test command
  - I've got some other bugs, like still missing dependencies for the first tool, but I do not worry about that for now, and another strange error for the third tool :" 'module' object has no attribute 'fromstring' "

**Comment by bgruening** [comment]
Hi @Mataivic,

without having seen your code I would guess that your python scripts assume each other in the same directory? Galaxy executes your tool in it's own temporary directory, for example on some cluster. The python file next to your Galaxy tool XML file you need to reference with `$__tool_directory__` this is the location where the XML is stored and therefore also your python file.

Now this would work for a single python file, but if this python file calls an other python file you need to now the location where it is stored this  `$__tool_directory__` ...

Does this makes sense?
You can hack it by allowing the first python file a parameter where you can specify the  `$__tool_directory__` dir and than take this inside of you code to call the other file or, what I would recommend ... separate your Code from your Galaxy tool. That is create a bioconda package for your perl & bash scripts and depend simply on this package.

Hope this helps,
Bjoern

**Comment by Mataivic** [comment]
Yes, all the scripts are in he same directory, as symbolic links are in the same directory (I also tried without links, it does not work too).

**Comment by jmchilton** [comment]
Yeah - you may have to modify the ``sys.path`` inside of the main Python script so that the dependent scripts are available at the Python level.
