### ISSUE TITLE
Planemo Tool Test Result - 'module' object has no attribute 'fromstring'

### ISSUE THREAD

**Issue by Mataivic** [galaxyproject/planemo#613]
Hello,

I was working on some errors about a functional test on a galaxy wrapper, then suddenly, the error
` " 'module' object has no attribute 'fromstring' " `seemed to came out of nowhere.

How can I fix that please ? I remember it happened after cleaning the tmp directory (needed because I used many times the --no_cleanup option in the planemo test command).

Here is the beginning of my log : 

```
`File "/usr/lib/python2.7/unittest/case.py", line 327, in run
    testMethod()
  File "/tmp/tmpvqWN3H/galaxy-dev/test/functional/test_toolbox.py", line 299, in test_tool
    self.do_it( td )
  File "/tmp/tmpvqWN3H/galaxy-dev/test/functional/test_toolbox.py", line 75, in do_it
    raise e
'\'module\' object has no attribute \'fromstring\'\n-------------------- >> begin captured logging << 
```

**Comment by jmchilton** [comment]
I don't know how replicate this and I have never seen it. I'm sorry. Is there a simple test tool that exhibits this behavior with are a particular version of planemo and Galaxy?

**Comment by Mataivic** [comment]
Hello, we figured it out only a few days ago ! It was a mistake in the xml wrapper, but not detected by planemo lint.
