### ISSUE TITLE
Failed linting: `help` within `<section>` tags

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/planemo#618]
`help` tag is allowed within `<section>`:
https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-inputs-section

However, when linting tools containing `<section name="..." help="..."></>` planemo raises the following error:

```
Applying linter tool_xsd... FAIL
.. ERROR: Invalid tmpjU6IeQ found. Errors [/tmp/tmpjU6IeQ:233: element section: Schemas validity error : Element 'section', attribute 'help': The attribute 'help' is not allowed.
```

**Comment by nsoranzo** [comment]
It has been added to the schema in https://github.com/galaxyproject/galaxy/pull/3131 , maybe planemo is not updated.

**Comment by jmchilton** [comment]
Yes - @nsoranzo is correct. I just tested the latest release of planemo - 0.36.1 - and it recognizes this and lints appropriately. Is it possible your version of planemo needs to be upgraded?
