### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#62]
Didn't really wan to do this when this project contained a subset of Galaxy that could conflict with Galaxy, but I think the work arounds in place now should provide sufficient separation that I think `pip install planemo` would be great.

**Comment by jmchilton** [comment]
Done by @natefoo see https://pypi.python.org/pypi/planemo. Still need to update documentation.

**Comment by jmchilton** [comment]
- Updated `pip` calls in end-user documentation.
 - Added release checklist - http://planemo.readthedocs.org/en/latest/developing.html#release-checklist describing how to release to PyPI.

**Comment by natefoo** [comment]
Minor point, [twine](https://pypi.python.org/pypi/twine) is currently [the recommended tool](https://packaging.python.org/en/latest/current.html#packaging-tool-recommendations) for uploading to PyPI:

**Comment by erasche** [comment]
`O_O`. Time to change my pypi password.
