### ISSUE TITLE
Cannot tap galaxyproject/tap: invalid syntax in tap!

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/planemo#621]
Hi Planemo, 
I was seeking to download this with homebrew, when I got the following error: 

```
==> Tapping galaxyproject/tap
Cloning into '/usr/local/Homebrew/Library/Taps/galaxyproject/homebrew-tap'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/galaxyproject/homebrew-tap/shed-brew.rb
Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/galaxyproject/homebrew-tap/shed-brew.rb:6:in `<class:ShedBrew>'
Please report this to the galaxyproject/tap tap!
Error: Cannot tap galaxyproject/tap: invalid syntax in tap!
```

I suspect either the [installation docs](https://planemo.readthedocs.io/en/latest/readme.html#obtaining-planemo) need updating, or someone needs to do some maintenance on the `galaxyproject/tap`

(I've installed using venv, so I'm not blocked by this. Just thought you ought to know)

**Comment by albert500** [comment]
This might be related:
https://github.com/Homebrew/homebrew-core/issues/6693#issuecomment-258965843

**Comment by jmchilton** [comment]
I just removed the offending recipe - thanks for the heads up!
