### ISSUE TITLE
Schemas validity error with lint

### ISSUE THREAD

**Issue by pierrickrogermele** [galaxyproject/planemo#622]
When running `planemo lint` on my tool XML, I got this error:
`element param: Schemas validity error : Element 'param', attribute 'refresh_on_change': The attribute 'refresh_on_change' is not allowed.`
It seems the current galaxy.xsd does not define `refresh_on_change` as a valid attribute for `param` element.

**Comment by pierrickrogermele** [comment]
After running the tests of the project Galaxy-XSD, I see that there are many errors.
Maybe it would be better to turn off `xsd` by default in `planemo lint`.

**Comment by pierrickrogermele** [comment]
I've seen that Galaxy-XSD has been move into Galaxy.
However even here the `galaxy.xsd` file does not contain definition for `refresh_on_change `.

**Comment by peterjc** [comment]
In this case, we need to file a bug on Galaxy itself for missing ``refresh_on_change`` in the XSD file https://github.com/galaxyproject/galaxy/tree/dev/lib/galaxy/tools/xsd (Planemo just bundles a copy of this file).

Please do report any other XSD issues as given how the tool XML format evolved there are potentially other rarely used tags which have not been defined.

You can turn off the XSD changing with ``planemo lint --no_xsd``.

**Comment by bgruening** [comment]
I'm not sure, but it can be that `refresh_on_change` has no effect anymore? @pierrickrogermele are you sure you still need it?

**Comment by pierrickrogermele** [comment]
@bgruening, I use this `refresh_on_change` attribute in coordination with the [`code`](https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-code) tag, which is deprecated.
However I've not seen any replacement for the `code` tag, and I really need it in order to display choice list from a database or a file.
The `refresh_on_change` attribute is not listed itself in the schema, but it is used inside an [example](https://docs.galaxyproject.org/en/latest/dev/schema.html#id82).

**Comment by jmchilton** [comment]
I'll update the schema to include ``refresh_on_change`` - it does seem to do something.

```
⚡ grep -r "refresh_on_change" client/galaxy 
...
client/galaxy/scripts/mvc/form/form-view.js:                if ( !input || input.refresh_on_change || self.options.always_refresh ) {
```
