### ISSUE TITLE
Disabling conda dependency resolver

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/planemo#633]
So it seems that's currently not possible. The closest thing to disabling
conda would be providing you're own job_conf.xml.
A flag like `--no_conda_dependency_resolution` analogous to `--no_conda_auto_install` would be nice. 
Usecase is if you're developing a python package, and you would like to test it with planemo before packing it up in pypi followed by creating a conda package from pypi. 
You can also work around it by removing the conda package or the requirements tag, but it would still be nice if planemo could be used in that scenario.

**Comment by peterjc** [comment]
What happens if the (proposed) requirements tag is present (but does not yet resolve)? Error from Galaxy?

Maybe I've been lucky so far...

**Comment by mvdbeek** [comment]
> What happens if the (proposed) requirements tag is present (but does not yet resolve)? Error from Galaxy?

That will work as well.
