### ISSUE TITLE
Write a manuscript for BioConda and BioContainers on Computational Platforms

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#651]
### Outline

The problems associated with reproducibility of web services has been well documented [citation needed], so reproducible informatics requires reproducible software installation. There are many approaches to reproducible software installation for informatics - DebianMed, Docker, EasyInstall, software modules, and so on. Many work great in cloud and container environments - where the researcher has full control of a virtual machine or container and may choose whatever software installation mechanism makes sense, but are less appropriate at high performance computing (HPC) centers where large centralized resources make such freedom impossible. On the other hand, the HPC centric approaches don't provide options such as ready-to-run software containers ideal for the cloud. Futhermore, some approaches are built to work with command-line scripting while others are built for specific computational platforms such as the Galaxy Tool Shed or Dockstore. This paper outlines an approach that fits all of these scenarios. Combing a popular binary package manager containing thousands of bioinformatics and general purpose scientific software recipes and container environments built using these binaries for various technologies such as Docker, rtk, and Singularity and then making these packages and containers available on command-line and inside computational platforms such as Galaxy and workflow platforms such as Toil we believe we provide a pervasive approach to reproducibility that works regardless of the technologies used.

We will recreate the analysis in PAPER X four different ways. Using customized shell scripts at an HPC facility, an IPython notebook on a Mac OS X laptop, in a Galaxy history on usegalaxy.org, and deployed on Amazon EC 2 with Toil using the Common Workflow Language. We will use the same binaries seamlessly across these environments leveraging the technologies that make the most sense for each environment.

**Comment by bgruening** [comment]
If we are really going to try BioConda packages and not only Containers can we use snakemake instead of toil? It's much more used and has a strong community behind BioConda.

**Comment by jmchilton** [comment]
I wanted to highlight and frankly push the already WIP CWL efforts to make the claim of supporting multi-platforms for the galaxy-lib and mulled parts. Toil seemed like the lowest hanging fruit there.

I'm certainly not opposed to extending this to snakemake - does its computational model make sense mulled containers or just the bioconda half of this?

**Comment by jmchilton** [comment]
@bgruening Also I should make clear I haven't run this by the PIs at all and I'm fairly open to whatever - this was just a random idea. I just wanted to put together a proposal for something to work on to try to convince people this was worth spending time on - it may not be.

**Comment by bgruening** [comment]
@jmchilton I have 3 manuscripts started to get this out and never finishend any of them, so any help and coordination is welcome. Your idea has a slightly different touch, but I feel we have some overlapping parts. Talking to @jxtx is probably a good idea as he is aware of my ideas and already tried to push me in writing this down :(

Regarding the CWL PR ... mh ... if they do not care why bother? I guess we have strong cases and many examples including snakemake, cyverse, OSG to make this really nice. If you want to push toil thats ok, just wanted to point out that there are communities already in this loop which might be interested in this even more.
