### ISSUE TITLE
Different default directory for conda?

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#658]
Any opposition to changing `~/miniconda2/` to `~/.planemo/miniconda2`? I really don't like things cluttering my ~

**Comment by nsoranzo** [comment]
That should be miniconda**3** anyway now.

**Comment by nsoranzo** [comment]
No strong feelings as long changing the default doesn't make planemo download everything again for people that have already everything in `~/miniconda2/`

**Comment by jmchilton** [comment]
Closing because I provided a workaround - hope this is good enough if not please re-open and we can discuss this further.

**Comment by erasche** [comment]
Nope, more than sufficient. Thanks @jmchilton
