### ISSUE TITLE
planemo test should handle tools that accept input.extra_files_path

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/planemo#671]
I have several tools (e.g., https://github.com/gregvonkuster/galaxy_tools/tree/master/tools/plant_tribes/gene_family_integrator) that take as input a dataset that includes associated files contained within its extra_files_path directory.  The datatype for these various tool inputs is a subclass of the html Galaxy datatype.

planemo test works fine for tools that produce outputs like this since it can check the contents of the primary dataset and ignore the contents of the extra_files_path.  As long as the primary dataset contains information that can verify the contents of the extra_files_path, the tests work well.  An example of this kind of tool is here https://github.com/gregvonkuster/galaxy_tools/tree/master/tools/plant_tribes/gene_family_classifier.

However, using the current planemo test features on this tool https://github.com/gregvonkuster/galaxy_tools/tree/master/tools/plant_tribes/gene_family_integrator produces this error:
```
======================================================================
ERROR: GeneFamilyIntegrator ( plant_tribes_gene_family_integrator ) > Test-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/biotools/galaxy/test/galaxy/test/functional/test_toolbox.py", line 302, in test_tool
    self.do_it( td )
  File "/scratch/biotools/galaxy/test/galaxy/test/functional/test_toolbox.py", line 63, in do_it
    raise e
RunToolException: Error creating a job for these tool inputs - The selected dataset's extra_files_path directory is empty or does not exist, this tool expects non-empty extra_files_path directories associated with the selected input.
```
I'm willing to work on this enhancement, but I'd need some direction.  The code in ~/planemo/engine/interface looks promising, but....

**Comment by jmchilton** [comment]
I believe this is a Galaxy issue - Galaxy can handle composite inputs the syntax for the uploads is https://github.com/galaxyproject/galaxy/blob/dev/test/functional/tools/composite.xml. That might only work for composite uploads with known files - I don't know if it is possible to upload unstructured composite datatypes in this way.

**Comment by gregvonkuster** [comment]
Thanks for the pointer on this @jmchilton - I discussed this in depth with @blankenberg and will go in a different direction for testing these tools since Galaxy framework enhancements needed to upload the "light-weight" composite datatype I'm using would be non-trivial.
