### ISSUE TITLE
planemo lint might fail on conda

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/planemo#673]
When doing planemo lint with the conda version, rst will not be processed. This is simply because docutils is not on the dependency list.

Solution is then quite simple: include docutils on the dependency.

Thanks

**Comment by bgruening** [comment]
@tiagoantao https://github.com/bioconda/bioconda-recipes/pull/4743

**Comment by bgruening** [comment]
@tiagoantao I hope this is fixed with the latest planemo version. Thanks for the catch!
