### ISSUE TITLE
Creating tool_dependencies and tools automatically

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/planemo#69]
We can build various pieces of your stack now automatically. 
For example we can generate Perl and R tool_dependencies given an package name. We can convert `CDT`, argparse or soon `JavaDoc` to Galaxy tools.
It would be awesome if we could get this functionality integrated into planemo.

The biggest problem is probably the large dependency list of every converter. But hey we have Docker right. So I will try to work on the following over the next week(s).
- [ ] create a docker container with all dependencies that are needed to create such a `galaxy-converter-box`
- [ ] write a nice entrypoint script so that planemo can easily use it
- [ ] hook it into planmo (optionally)

Any concerns? Any other plans?

**Comment by erasche** [comment]
Oooh, can't wait!

**Comment by jmchilton** [comment]
Love it!

We already have recipes to build [planemo appliances](http://planemo.readthedocs.org/en/latest/appliance.html) (Docker, but also Vagrant, GCE, Amazon, etc...) so I think it would be best to add dependency descriptions as part of the of [devbox](https://github.com/galaxyproject/planemo-machine/tree/master/roles/galaxyprojectdotorg.devbox) ansible role in [planemo-machine](https://github.com/galaxyproject/planemo-machine) and then all of these appliances would get this functionality (including the auto-updating `docker fetch planemo/box`). Let me know if this is a problem.

**Comment by jmchilton** [comment]
Closing in lieu of Conda, we do this better now than ever I would say. Feel free to re-open if there is something to revisit here.
