### ISSUE TITLE
Updates to recursive uploads

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#71]
I'd like to implement a specific update to the recently added recursive uploads, namely dependency resolution.

What sort of assumptions seem reasonable? E.g.
- if we're running a recursive upload, can we assume we're running from the root of the repository (and can just enumerate everything with a .shed.yml and build a dependency tree with some tool_dependencies.xml parsing? (This seems like a reasonable assumption, e.g. if we're running in a folder and we detect 1 tool, then see bullet point 2, if we detect >1 tool, then assume packages are included)
- if we're running in a single directory and have already detected it as a tool to be upload, is 1, 2 paths up the directory tree reasonable to go to look for the associated package? (thinking of the IUC's tool repo)

Feel free to add any more wishlist items to this issue that seem relevant to this ticket.
- [ ] Recursive uploads could use a progress bar #115

**Comment by peterjc** [comment]
Does this mean currently planemo does not do anything clever about ordering multiple tool updates - e.g. update tool dependency and datatype only repositories first? As a workaround you could separately call the recursive ``planemo shed_update`` first on ``datatypes/`` and ``packages/``, and only later on ``tools/`` etc?

**Comment by jmchilton** [comment]
@peterjc Yeah - no clever ordering of things has been implemented yet.

**Comment by erasche** [comment]
@peterjc yep, sorry I haven't gotten around to this yet. Anyone is welcome to work on it, but hopefully I'll find time soon.

**Comment by erasche** [comment]
Not interesting in 3 years
