### ISSUE TITLE
planemo serve: ModuleNotFoundError: No module named 'conda'

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/planemo#713]
Hello, 

I've installed planemo via pip in a virtualenv. I'm trying to test out a tool which has a conda dependency. 

```
planemo s
[.........]
ModuleNotFoundError: No module named 'conda'
```
But then I also can't do:
```
planemo conda_init
conda_init failed - Conda appears to already be installed at '/Users/alex/miniconda3/bin/conda'
```

Could someone point me to the right part of the documentation for this scenario? I haven't found it.

**Comment by jmchilton** [comment]
Can you expand out what is happening in:

```[.........]```

after you do ```planemo s``` - I don't know what is happening here. You can send it to jmchilton@gmail.com if you don't want to publish paths and such publicly.

**Comment by zfrenchee** [comment]
It's 1200 lines or so. I've sent it.

**Comment by jmchilton** [comment]
There is something wrong with your miniconda setup I think - your conda binary doesn't seem to work correctly. Have you used conda outside of Galaxy on this machine before?

Maybe try moving ```mv ~/miniconda3 ~/miniconda3-bkup``` and rerunning ``planemo conda_init``?

**Comment by zfrenchee** [comment]
Hi @jmchilton thanks for getting back to me. 

```
~/Documents/GarNet(master*) » planemo conda_init                                                          [venv]alex@Alexs-MacBook-Pro
wget -q --recursive -O '/var/folders/0w/fzyy4qz93l56_bh1jyn3vgp00000gn/T/conda_installcbfjv5d_.sh' 'https://repo.continuum.io/miniconda/Miniconda3-4.2.12-MacOSX-x86_64.sh' && bash '/var/folders/0w/fzyy4qz93l56_bh1jyn3vgp00000gn/T/conda_installcbfjv5d_.sh' -b -p '/Users/alex/miniconda3' && /Users/alex/miniconda3/bin/conda install -y -q conda=4.2.13 conda-build=2.1.4
PREFIX=/Users/alex/miniconda3
installing: python-3.5.2-0 ...
installing: conda-env-2.6.0-0 ...
installing: openssl-1.0.2j-0 ...
installing: pycosat-0.6.1-py35_1 ...
installing: readline-6.2-2 ...
installing: requests-2.11.1-py35_0 ...
installing: ruamel_yaml-0.11.14-py35_0 ...
installing: sqlite-3.13.0-0 ...
installing: tk-8.5.18-0 ...
installing: xz-5.2.2-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-3 ...
installing: conda-4.2.12-py35_0 ...
installing: pycrypto-2.6.1-py35_4 ...
installing: pip-8.1.2-py35_0 ...
installing: wheel-0.29.0-py35_0 ...
installing: setuptools-27.2.0-py35_0 ...
Python 3.5.2 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
Traceback (most recent call last):
  File "/Users/alex/miniconda3/bin/conda", line 4, in <module>
    import conda.cli
ImportError: No module named 'conda'
conda_init failed - failed to install to '/Users/alex/miniconda3/bin/conda'
```

I have a feeling you might be right and this is a problem with my local machine, but not quite sure what it might be... Let me know what you think!

**Comment by jmchilton** [comment]
Want to try to remove Conda again and try to install it from scratch outside of Planemo? 

Maybe try the instructions here- https://conda.io/docs/install/quick.html#os-x-miniconda-install and then run a few Conda commands and see if they work?

**Comment by zfrenchee** [comment]
Hi @jmchilton 

Quick note: conda seemed to work fine before. I've uninstalled miniconda anyhow (`rm -rf ~/miniconda3/`) and re-installed using the instructions you linked. `conda` commands still work now. 

- `planemo s` still fails with 
```
Traceback (most recent call last):
  File "/Users/alex/miniconda3/bin/conda", line 4, in <module>
    import conda.cli
ModuleNotFoundError: No module named 'conda'
```

- `planemo conda_init` now just throws
```
conda_init failed - Conda appears to already be installed at '/Users/alex/miniconda3/bin/conda'
```

Note: I installed and am running planemo from a virtualenv

Let me know what you think I should do =0
