### ISSUE TITLE
`planemo lint` wrongly warns about `strict` attribute of `<command>`

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/planemo#726]
```
$ planemo lint ~/galaxy_blast/tools/ncbi_blast_plus/ncbi_makeprofiledb.xml
...
Applying linter command... WARNING
.. WARNING: Unknown attribute [strict] encountered on command tag.
```
The `strict` attribute is documented at https://docs.galaxyproject.org/en/latest/dev/schema.html#strict

May be of interest for @peterjc .

**Comment by peterjc** [comment]
This is odd - planemo's copy of the XSD is up to date and have had the strict entry since a086f364151b1c55ffe6c38078b4be8f22cb829b

**Comment by nsoranzo** [comment]
That's not in the `tool_xsd` linter, but in the `command` one.

**Comment by jmchilton** [comment]
Yeah - the is a remanent from pre-XSD days. Probably should just remove the check all together rather than updating it with new attributes.

**Comment by peterjc** [comment]
So its an out-of-date and now redundant check, on top of the XSD validation?

**Comment by jmchilton** [comment]
Yup it should be fixed by https://github.com/galaxyproject/galaxy-lib/pull/76.
