### ISSUE TITLE
conda install in Mac OS X

### ISSUE THREAD

**Issue by hmkim** [galaxyproject/planemo#741]
I try to install planemo using conda.

https://planemo.readthedocs.io/en/latest/installation.html

> $ conda install -c bioconda planemo
> 
> Fetching package metadata .............
> Solving package specifications:
> 
> PackageNotFoundError: Dependency missing in current osx-64 channels:
>   - planemo -> pyaml
> 
> Close matches found; did you mean one of these?
> 
>     pyaml: pyyaml, yaml, paml

Please  check this issue.

**Comment by nsoranzo** [comment]
pyaml is in the `conda-forge` channel, which unfortunately is missing from the mentioned webpage. Can you try with:
```
conda install -c bioconda -c conda-forge planemo
```
?

**Comment by hmkim** [comment]
Thanks ^^!
