### ISSUE TITLE
Problem loading command bioc_conda_recipe_init, exception No module named 'urlparse'

### ISSUE THREAD

**Issue by tseemann** [galaxyproject/planemo#749]
```
pip3 install planemo
planemo
```
gives
```
Problem loading command bioc_conda_recipe_init, exception No module named 'urlparse'
Problem loading command bioc_tool_init, exception No module named 'urlparse'
Usage: planemo [OPTIONS] COMMAND [ARGS]...
```
on linux , python 3.6

**Comment by jmchilton** [comment]
Thanks for the bug report @tseemann - unfortunately I don't think Planemo works consistently on Python 3 yet ... I recommend using Python 2 for now. Though there are some open bugs related to bioc_conda_recipe_init I think - I'm not sure it is really supported well. Sorry :(

**Comment by nsoranzo** [comment]
That should work now, please reopen if it's still an issue.
