### ISSUE TITLE
Cannot upload files (planemo serve, OSX)

### ISSUE THREAD

**Issue by AnnaSyme** [galaxyproject/planemo#751]
(Filed by @erasche)

<img width="1079" alt="screen shot 2018-01-19 at 11 50 17 am" src="https://user-images.githubusercontent.com/13082854/35129590-6a97eb70-fd10-11e7-8eab-1b120a55a310.png">

Clearly works, failing due to stdout warning message? Happens across 4/5 OSX machines in our workshop

**Comment by AnnaSyme** [comment]
(Again, @erasche speaking)

Every mac user who wishes to upload things should comment out line 74 ~/.planemo/gx_venv/lib/python2.7/site-packages/watchdog/observers/__init__.py

```python
            #warnings.warn("Failed to import fsevents. Fall back to kqueue")
```

**Comment by erasche** [comment]
I guess I'll close this and re-file against galaxy? Not sure when this changed but it made the workshop super fun.
