### ISSUE TITLE
Issues running planemo test on Mac

### ISSUE THREAD

**Issue by mblue9** [galaxyproject/planemo#752]
We're trying to get planemo working on Mac. Thanks to @erasche and https://github.com/galaxyproject/galaxy/issues/5341, planemo serve is working now but with planemo test no tests are being run. We're getting a similar error with El Capitan and High Sierra. Output is:

```
2018-01-19 13:26:51,909 INFO  [galaxy.model.migrate.check] Migrating 134 -> 135... 
2018-01-19 13:26:52,372 INFO  [galaxy.model.migrate.check] 
2018-01-19 13:26:52,372 INFO  [galaxy.model.migrate.check] This migration script adds support for storing tags in the context of a dataset in a library
2018-01-19 13:26:52,373 INFO  [galaxy.model.migrate.check] 
2018-01-19 13:26:52,373 INFO  [galaxy.model.migrate.check] 
2018-01-19 13:26:52,389 INFO  [galaxy.config] Install database targetting Galaxy's database configuration.
2018-01-19 13:26:53,195 ERROR [galaxy.visualization.genomes] Error reading twobit.loc
Traceback (most recent call last):
  File "/Users/maria/Desktop/galaxy/lib/galaxy/visualization/genomes.py", line 211, in reload_genomes
    for line in open(os.path.join(self.app.config.tool_data_path, "twobit.loc")):
IOError: [Errno 2] No such file or directory: '/Users/maria/Desktop/galaxy/tool-data/twobit.loc'
2018-01-19 13:26:53,238 INFO  [galaxy.util.handlers] Setting <handlers> default to child with id 'main'
2018-01-19 13:26:53,436 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpbxs0823k/tool_conf.xml
2018-01-19 13:26:53,687 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpbxs0823k/shed_tools_conf.xml
2018-01-19 13:26:53,687 INFO  [galaxy.tools.toolbox.base] Parsing the tool configuration /private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpbxs0823k/empty_tool_conf.xml
No handlers could be found for logger "galaxy.datatypes.display_applications.application"
2018-01-19 13:26:54,223 INFO  [galaxy.jobs] Handler 'main' will load all configured runner plugins
2018-01-19 13:26:54,231 INFO  [galaxy.jobs.handler] job handler stop queue started
2018-01-19 13:26:54,250 INFO  [galaxy.jobs.handler] job handler queue started
2018-01-19 13:26:54,285 INFO  [galaxy.app] Galaxy app startup finished (5440.689 ms)
2018-01-19 13:26:55,230 INFO  [galaxy.queue_worker] Binding and starting galaxy control worker for main
/Users/maria/.planemo/gx_venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:562: SAWarning: Dialect sqlite+pysqlite does *not* support Decimal objects natively, and SQLAlchemy must convert from floating point - rounding errors and other issues may occur. Please consider storing Decimal numbers as strings or integers on this platform for lossless storage.
  'storage.' % (dialect.name, dialect.driver))
/Users/maria/.planemo/gx_venv/lib/python2.7/site-packages/sqlalchemy/sql/default_comparator.py:153: SAWarning: The IN-predicate on "request_type.id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
  'strategies for improved performance.' % expr)

----------------------------------------------------------------------
XML: /private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpbxs0823k/xunit.xml
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
2018-01-19 13:26:55,870 INFO  [test_driver] Shutting down
2018-01-19 13:26:55,870 INFO  [test_driver] Shutting down embedded galaxy web server
2018-01-19 13:26:55,873 INFO  [test_driver] Embedded web server galaxy stopped
2018-01-19 13:26:55,873 INFO  [test_driver] Stopping application galaxy
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/maria/.planemo/gx_venv/lib/python2.7/site-packages/paste/httpserver.py", line 1101, in serve_forever
    self.handle_request()
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 271, in handle_request
    fd_sets = _eintr_retry(select.select, [self], [], [], timeout)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 150, in _eintr_retry
    return func(*args)
error: (9, 'Bad file descriptor')

2018-01-19 13:26:57,920 INFO  [galaxy.jobs.handler] sending stop signal to worker thread
2018-01-19 13:26:57,920 INFO  [galaxy.jobs.handler] job handler queue stopped
2018-01-19 13:26:57,920 INFO  [galaxy.jobs.runners] TaskRunner: Sending stop signal to 2 worker threads
2018-01-19 13:26:57,920 INFO  [galaxy.jobs.runners] LocalRunner: Sending stop signal to 4 worker threads
2018-01-19 13:26:57,920 INFO  [galaxy.jobs.handler] sending stop signal to worker thread
2018-01-19 13:26:57,921 INFO  [galaxy.jobs.handler] job handler stop queue stopped
2018-01-19 13:26:57,921 INFO  [test_driver] Application galaxy stopped.
2018-01-19 13:26:57,926 INFO  [galaxy.jobs.handler] sending stop signal to worker thread
2018-01-19 13:26:57,926 INFO  [galaxy.jobs.handler] job handler queue stopped
2018-01-19 13:26:57,926 INFO  [galaxy.jobs.runners] TaskRunner: Sending stop signal to 2 worker threads
2018-01-19 13:26:57,926 INFO  [galaxy.jobs.runners] LocalRunner: Sending stop signal to 4 worker threads
2018-01-19 13:26:57,926 INFO  [galaxy.jobs.handler] sending stop signal to worker thread
2018-01-19 13:26:57,926 INFO  [galaxy.jobs.handler] job handler stop queue stopped
Testing complete. HTML report is in "/Users/maria/galaxy/tools-iuc/tools/annotatemyids/tool_test_output.html".
No tests were executed - see Galaxy output for details.
```

**Comment by mvdbeek** [comment]
Could be connected to #751 / https://github.com/galaxyproject/galaxy/issues/5341, can you try removing ~/.planemo/gx_venv and try it again ? I am able to run tests, so this should hopefully be all that is necessary.

**Comment by mblue9** [comment]
Thanks @mvdbeek, I tried removing ~/.planemo/gx_venv and rerunning but am just getting same cryptic error `error: (9, 'Bad file descriptor')` :(

**Comment by mvdbeek** [comment]
Alright, that's for a tool that is known to pass tests, like any of the iuc tools ?
How did you call planemo ? Can you share the tool in question ?

**Comment by mvdbeek** [comment]
Ah, and planemo installs, but can't run in python3 environments, so if you have conda around make sure it's not in your PATH. That does actually fail like this:
```
2018-01-21 10:05:17,983 INFO  [galaxy.app] Galaxy app startup finished (5140.795 ms)
2018-01-21 10:05:18,941 INFO  [galaxy.queue_worker] Binding and starting galaxy control worker for main
/Users/mvandenb/.planemo/gx_venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:562: SAWarning: Dialect sqlite+pysqlite does *not* support Decimal objects natively, and SQLAlchemy must convert from floating point - rounding errors and other issues may occur. Please consider storing Decimal numbers as strings or integers on this platform for lossless storage.
  'storage.' % (dialect.name, dialect.driver))
/Users/mvandenb/.planemo/gx_venv/lib/python2.7/site-packages/sqlalchemy/sql/default_comparator.py:153: SAWarning: The IN-predicate on "request_type.id" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
  'strategies for improved performance.' % expr)

----------------------------------------------------------------------
XML: /private/var/folders/df/6xqpqpcd7h73b6jpx9t6cwhw0000gn/T/tmpuh1t2ons/xunit.xml
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by mblue9** [comment]
Thanks @mvdbeek but unfortunately it looks like it's just not going to work for me @erasche took a look. I'll stick with the VM until I can figure out a better solution (although the VM is now unfortunately crashing multiple times a day. I am not having a good run at the moment 😞 )

**Comment by mvdbeek** [comment]
Can you check what the output of `command -v conda`, `command -v python` and `python -c 'import sys; print(sys.version)'` is ?

**Comment by mblue9** [comment]
Ok, that gives below

`$ command -v conda`
/Users/maria/miniconda3/bin/conda

`$ command -v python`
/Users/maria/miniconda3/bin/python

`$ python -c 'import sys; print(sys.version)'`
3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by mvdbeek** [comment]
Right, that's the headache combination that you don't want. When you install miniconda by hand it asks you whether to add the PATH to your ~/.bash_profile, you would want to say no there, but the default is yes. A global conda causes more trouble than it solves in my opinion.

So what I'd recommend is remove the line that says `export PATH="/Users/maria/miniconda3/bin:$PATH"` in your `~/.bash_profile` file and launch another shell. 

If you run those commands again you should not have conda on PATH, and your PYTHON should be your system's python or the python from your virtualenv, if you have activated one.
From there on planemo should work (you may need to reinstall it if it was installed in the conda environment).

**Comment by mblue9** [comment]
@mvdbeek thanks for your help on this one but we may have to accept defeat here as I've tried what you said and am still getting that same error. Or maybe I did something wrong, here's what I tried: 

I had already tried removing conda from my PATH before but when I got the planemo not found I didn't reinstall Planemo!! But that makes sense! (I get pretty confused with what-has-installed-what-and-where and what the setup is supposed to look like with conda-planemo planemo-conda pythons...)

And I'm not sure if this is the way I'm supposed to do this, but after removing conda from the path I then did:

`virtualenv .venv; . .venv/bin/activate`
`pip install "pip>=7"`
`pip install planemo`

Removed the virtualenv bin folder from PATH (as I was now in the activated virtualenv)
`/Users/maria/venvs/.venv/bin/planemo conda_init`
`/Users/maria/venvs/.venv/bin/planemo conda_install .`

Added a # to line 74 of  ~/.planemo/gx_venv/lib/python2.7/site-packages/watchdog/observers/__init__.py (because of  https://github.com/galaxyproject/galaxy/issues/740)

Then when I try to run planemo test (either with or without --galaxy_root pointing to my laptop's Galaxy) I still get that same error `(9, 'Bad file descriptor')`.

But in the .venv I do now get:
`command -v conda`

`command -v python`
/usr/bin/python

`python -c 'import sys; print(sys.version)'`
2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

Did I do something wrong? Or should we just forget about this one and move on with our lives? 
This is an oldish Mac and who knows, I may well have done something at some point that messed up something that Planemo expects to be there.

**Comment by mvdbeek** [comment]
> (I get pretty confused with what-has-installed-what-and-where and what the setup is supposed to look like with conda-planemo planemo-conda pythons...)

So (at the moment, this may change in the future) you basically never want to use conda in the galaxy world, unless you develop a conda package or you're really sure what you're doing, in which case you probably still don't want a global conda, but one that you put on your PATH whenever you need it. `planemo conda_init` for instance installs conda but doesn't put it on PATH.

As long as conda is not on your PATH you should use your regular virtualenv workflow.

> Removed the virtualenv bin folder from PATH (as I was now in the activated virtualenv)

You'll want to be in your virtualenv to run planemo, so that wasn't necessary (but it shouldn't hurt either)

> Added a # to line 74 of ~/.planemo/gx_venv/lib/python2.7/site-packages/watchdog/observers/init.py (because of galaxyproject/galaxy#740)

We've fixed this (assuming you meant https://github.com/galaxyproject/galaxy/issues/5341), and the workaround is not a good one, because if you do need it you're still using a watchdog that is broken. If you still get an error on upload you can manually activate the virtualenv and remove and re-install watchdog.

> (either with or without --galaxy_root pointing to my laptop's Galaxy

I think you'd want to not use `--galaxy_root` unless you manually modifed Galaxy. If you do want to use `--galaxy_root` make sure that the virtualenv in `<galaxy_root>/.venv` does not contain the broken watchdog (re-installing is an easy way to be sure of that).

Though that's also not the issue at hand.

> But in the .venv I do now get:
> command -v conda
> 
> command -v python
> /usr/bin/python

Well it looks like the virtualenv is not activated, other wise python should come from <path_to_your_venv/bin/python>

> I still get that same error (9, 'Bad file descriptor').

That's not really an error, you can see this on successful planemo runs as well.

Now I was about to type out some more instructions and realised that when you setup a clean new virtualenv and reinstall planemo I get the same behaviour as you, which makes me think that a dependency update happened somewhere that breaks `planemo test`. Interestingly I can switch to my old virtualenv and it still works with the same ~/.venv, so this should be something planemo-specific

**Comment by mvdbeek** [comment]
Urgs, it's actually planemo that seems to be broken, 0.46.1 works.
Can you try installing 0.46.1 ?

**Comment by mvdbeek** [comment]
Also the current master branch of planemo works -- @jmchilton could we get a new planemo release ?

**Comment by mblue9** [comment]
Oh this is looking very promising!!!! Thanks so much for all that info and your effort on this @mvdbeek!!!

**Comment by mvdbeek** [comment]
I can't reproduce this anymore, and also on a quick glance there doesn't seem to be any change between 0.46.1 and 0.47.0 that could cause a failure in 0.47.0

**Comment by jmchilton** [comment]
@mvdbeek Are you saying we do need a release or we don't? Thanks for helping @mblue9 debug this - you seem to understand Planemo and its runtime environment better than me somehow 😆.

**Comment by mvdbeek** [comment]
Hah! Well I'm not sure, at first I thought so, but now I'm doubting if I can even computer :/.
I've definitely seen this bug, but scratching everything (~/.planemo and the virtualenv) it seems to work ... now.

**Comment by jmchilton** [comment]
@mvdbeek Maybe https://github.com/galaxyproject/planemo/issues/721 would address this if wiping virtualenv helps. Anyway - you computer better than anyone I know - don't doubt yourself.

**Comment by mblue9** [comment]
Well I am certainly doubting if I can computer because I have gone backwards here. I tried removing ~/.planemo and the virtualenv and starting again and now I can't get the conda_init command to work and that one had worked yesterday! I get `conda_init failed - failed to install to '/Users/maria/miniconda3/bin/conda'`

**Comment by mvdbeek** [comment]
If you still got a conda environment there that shouldn't be a problem

**Comment by mblue9** [comment]
@mvdbeek I don't seem to have a conda environment here so I guess it might be a problem? or how can I check? do you mean I should have conda installed somewhere in this virtualenv? because I don't seem to. 

Btw this is an example of the conda confusion I still have. Because I removed miniconda from my path and deleted the previous ~/.planemo and virtualenv I had, and I thought it was this planemo conda_init command that would get me conda, so where would I now be getting this conda environment that you speak of? 😕 

(I'm happy to keep trying here if you think it's worth it especially as my VM just crashed on me yet again. I'm also happy to walk anyway (or for you to!) at any point if this is just not worth spending more time on)

**Comment by mblue9** [comment]
To update (and please feel free to close this issue now) I just had another go and this and it finally works for me on my Mac!! :astonished: I have tried this so many times since May I cannot believe it!!!  

HUGE THANKS to @bebatut! :raised_hands: as I followed her pointers and, while it didn't work for me a few weeks ago, for some magical reason it works today!!!! :joy: :joy: :joy:

In case this helps anyone else, I installed Planemo like this:

/Users/maria/miniconda3/bin/conda create -n planemo planemo
source /Users/maria/miniconda3/bin/activate planemo

Then moving into the tool directory - all these commands just worked! at last!!:

planemo l .
planemo t .
planemo s .

This is so great as this is going to save me SO MUCH TIME!!!!!!!!!!!! (and also sanity - waiting for that Ubuntu startup after every freeze-reboot was starting to drive me a little crazy) Thanks so much to everyone who helped!!! ❤️ 👏 👏 👏

**Comment by mblue9** [comment]
This is working so well for me now I'm going to close this issue. Other than getting the little `error: (9, 'Bad file descriptor')`, which doesn't impact the tests, it works like a DREAM compared to the VM way I had 😄 Thanks again!!
