### ISSUE TITLE
planemo serve works if conda is on PATH, planemo test fails

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/planemo#754]
This is a bit messy, and I suspect the difference is that planemo serve launches `run.sh`, while planemo test works via `run_tests.sh`.

I suppose that in principle this could work.

**Comment by erasche** [comment]
It'd be nice if it did. We'd been training our users on making conda packages of their software before writing a tool for that new package and this tripped us up.

**Comment by jmchilton** [comment]
Ugh - it worked at some point right? Like during our last GCC training - this is disturbing.

**Comment by mvdbeek** [comment]
I guess we've unified that path recently, so maybe it's fixed?
