### ISSUE TITLE
Run a subset of tests against Postgres or docker-galaxy-stable

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#772]
xref #770 
xref e4b028d21e66a656650f65203d1eea7e7e5de371

**Comment by jmchilton** [comment]
xref https://github.com/galaxyproject/galaxy/pull/4887/. It'd be nice to leverage postgres database templates for speed.

**Comment by bgruening** [comment]
Database templates for postgresql are here. https://github.com/bgruening/docker-galaxy-stable/tree/master/compose/galaxy-postgres

**Comment by mvdbeek** [comment]
I think we're doing that now.
