### ISSUE TITLE
Option for Running and Testing Against Pre-populated Postgres

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#778]
https://github.com/bgruening/docker-galaxy-stable/tree/master/compose/galaxy-postgres

**Comment by mvdbeek** [comment]
Galaxy skips the migrations for a while now, and with https://github.com/galaxyproject/planemo/pull/985 and https://github.com/galaxyproject/planemo/pull/986 this works now in planemo as well, so I think this isn't needed anymore.
