### ISSUE TITLE
Improve bioconda Recipe

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#794]
- [x] Upgrade Planemo recipe to latest.
- [x] Upgrade galaxy-lib recipe to latest.
- [x] Certain optional-ish but important dependencies don't even exist in Conda yet:
  - [x] ephemeris
  - [x] gxformat2

**Comment by nsoranzo** [comment]
`galaxy-lib` has been updated already by @mbargull in https://github.com/bioconda/bioconda-recipes/pull/8184

**Comment by jmchilton** [comment]
@nsoranzo Oh yeah - I suppose. I forget people use it 😄, thanks!

**Comment by jmchilton** [comment]
xref https://github.com/bioconda/bioconda-recipes/pull/8208 thanks to the always amazing @bgruening.
