### ISSUE TITLE
/ missing in files path when testing with --install_galaxy

### ISSUE THREAD

**Issue by messersc** [galaxyproject/planemo#80]
I noticed a strange thing when debugging my tool.
There is a / missing, so the directory structure gets screwed up and there is unwanted behaviour like left-over tmp directories.

Example
=======

output files:
/tmp/tmp4NvYcRfiles/000/dataset_10.dat
/tmp/tmp4NvYcRfiles/000/dataset_11.dat
current working dir:
/tmp/tmp4NvYcR/job_working_directory/000/9

where /tmp/tmp4NvYcR/galaxy-central-master/ is the tmp Galaxy root.
tmp4NvYcRfiles should (obviously?) be tmp4NvYcR/files/ 

Is this a bug in Galaxy or planemo?

**Comment by erasche** [comment]
(I'm not an official source of truth) 
I've actually been using that as a feature during my test iterations--I've actually enjoyed being able to back and check the output of commands and when I have tests that fail, compare outputs.

**Comment by jmchilton** [comment]
@messersc thanks for the bug report, should be fixed now and I will do a new release with the fix soon.

**Comment by erasche** [comment]
@jmchilton thanks for adding the `--no-cleanup` option to support my use case :)
