### ISSUE TITLE
Planemo test with one of the params only accepting zip files

### ISSUE THREAD

**Issue by selten** [galaxyproject/planemo#804]
When running a planemo test, where one of the parameters requires a zip file to be added, the test will fail because the zip file will be extracted. This is problematic if the .zip file contains multiple files that are needed by a tool to run the test.

**Comment by jmchilton** [comment]
Is the target datatype in Galaxy? You'll need to add ``ftype="XXX"`` for the datatype on the upload parameter I think. Does that fix it?

**Comment by selten** [comment]
It is not related to uploading on Galaxy. I realize that I have to add the datatype on the upload parameter for Galaxy. This is when running planemo tests.   
   
The inputs are as such:
```
<inputs>
    <param name="shp_file_loc" type="data" format="zip"/>
</inputs>
```   
   
The test is as such:
```
<tests>
        <test>
            <param name="shp_file_loc" value="geoinfo2.zip"/>

            <output name="OUTPUT" file="output.csv" ftype="csv" />
        </test>
</tests>
```

This issue is specifically related to having an input to a tool as a zip file, planemo will unpack the zip file. Even though the tool requires a zip file to be used. Expected behaviour in my opinion would be for planemo not to unpack the zip file I submit. I don't upload anything myself as I specify the files in the test.

**Comment by bgruening** [comment]
Please try `<param name="shp_file_loc" value="geoinfo2.zip" ftype="zip"/>` to tell Galaxy this is a zip file during upload.

**Comment by selten** [comment]
That indeed fixes the issue, thanks for that. However it's unexpected behaviour to me that planemo tries to unzip it first.

**Comment by jmchilton** [comment]
It isn't Planemo I don't think, the Galaxy upload API does this if you don't specify a type for the upload I believe. I think researchers experience the same thing using the UI. I agree it is a bit unexpected, but we are iterating toward better behaviors for upload I think in recent big PRs. All that said it is best practice to always label upload types in tool tests this way.
