### ISSUE TITLE
Missing docutils_template.txt ?

### ISSUE THREAD

**Issue by ddooley** [galaxyproject/planemo#83]
Great tool - I'm setting up a training workshop around using it to help develop Galaxy tools here at the BCCDC.
Sort of a cosmetic error: When I run "planemo linter" on the demo template project, I get: 

Applying linter lint_help... WARNING
.. WARNING: Invalid reStructuredText found in help - [[Errno 2] No such file or directory: '/usr/lib/python2.6/site-packages/planemo_ext/galaxy/util/docutils_template.txt'].
.. CHECK: Tool contains help section.

I see some galaxies (branches?) out there hava a docutils_template.txt file that simply contains "%(body)s".  Is that related to this? 
Regards,
Damion

**Comment by ddooley** [comment]
Ah I see it is in an update from 5 days ago.  I'll pull ...

**Comment by jmchilton** [comment]
Thanks for the bug report. There is a definitely some different behavior related to non-Python source files when installed via `pip`. I should have a fix out and PyPI updated within the next couple days.

**Comment by jmchilton** [comment]
Thanks again for the bug report - I think the latest version from PyPI shouldn't have this problem anymore (https://pypi.python.org/pypi/planemo) - let me know if you encounter the problem again though.
