### ISSUE TITLE
tool definition misses fatal_oom level for regex

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/planemo#844]
We just realised that the tool definition used by planemo seems to be out of date and the fatal_oom level makes linting fail: 

https://github.com/galaxyproteomics/tools-galaxyp/pull/283#issuecomment-391336072

How about using the galaxies tool definition (e.g. of the galaxy that is used for testing), instead of shipping it separately with planemo?

**Comment by mvdbeek** [comment]
I think that's just what we're doing now!
