### ISSUE TITLE
Planemo serve doesn't serve up static contents with default command line invocation

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/planemo#845]
`planemo serve <tool_xml>`. Using `--galaxy_branch release_18.05` works fine. Possibly we just need to update ~~the~~ galaxy's master branch ?

**Comment by nsoranzo** [comment]
To fix this we need to not set `GALAXY_SKIP_CLIENT_BUILD` in `planemo.galaxy.config.local_galaxy_config()` when running the `serve` command.

**Comment by scholtalbers** [comment]
This just now prevented me from seeing the new interface with ``planemo serve --galaxy_branch dev --no_cache_galaxy`` 😉
