### ISSUE TITLE
Ability to install from tool_dependencies.xml

### ISSUE THREAD

**Issue by erasche** [galaxyproject/planemo#86]
Didn't see this elsewhere, just want to track this issue on GH.

- want ability to test tools with everything in `tool_dependencies.xml` installed in the target galaxy.
- should this try and find the packages locally (e.g. ../../packages/###) or install from toolshed?

**Comment by jmchilton** [comment]
Maybe comment on https://github.com/galaxyproject/planemo/issues/19 instead?

**Comment by erasche** [comment]
Hey, look at that, I'm blind.
