### ISSUE TITLE
linting: Check for suitable README file

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#89]
Occasionally tool authors use ``README.md`` or similar.

Planemo lint could warn if the preferred form ``README.rst`` is not present (is that the IUC preference? We should say so on https://wiki.galaxyproject.org/Tools/BestPractices if so)

Planemo lint could error in there is no recognised readme file at all (``README.txt``, ``repository_name.txt``, or ``README.rst``, etc - using same listing as the Tool Shed code).

**Comment by jmchilton** [comment]
Relevant Tool Shed code:

```
def get_readme_file_names( repository_name ):
    """Return a list of file names that will be categorized as README files for the received repository_name."""
    readme_files = [ 'readme', 'read_me', 'install' ]
    valid_filenames = map( lambda f: '%s.txt' % f, readme_files )
    valid_filenames.extend( map( lambda f: '%s.rst' % f, readme_files ) )
    valid_filenames.extend( readme_files )
    valid_filenames.append( '%s.txt' % repository_name )
    valid_filenames.append( '%s.rst' % repository_name )
    return valid_filenames
```

There is a couple there - probably the IUC should specify a best practice of just ``README``, ``README.txt``, or ``README.rst``.

**Comment by jmchilton** [comment]
Also along the same lines soon ``shed_upload`` will automatically filter out readmes for package and suite definitions so the best practice should just be every repository has a readme in github I suppose.

https://github.com/jmchilton/planemo/commit/19e304cd463bc28f8cf0360e8396945754b33877
