### ISSUE TITLE
owner names in shed.yml files

### ISSUE THREAD

**Issue by ppouchin** [galaxyproject/planemo#898]
A team I know has a toolshed account with a public name containing an underscore, but planemo says that:
> Owner must contain only lower-case letters, numbers and '-'

However, the toolshed states that:
> Public names must be at least three characters in length and contain only lower-case letters, numbers, dots, underscores, and dashes ('.', '_', '-').

Is it normal?

**Comment by martenson** [comment]
Underscores in usernames are allowed since 16.10 (https://github.com/galaxyproject/galaxy/commit/0e0b773edc85c3e36ae25f38ee929e8a95cc520b)

Planemo needs to update docs.

**Comment by ppouchin** [comment]
And this line too, right?
https://github.com/galaxyproject/planemo/blob/b3345015a8b89f0e4df736cb0b061e89d225fbc2/planemo/shed/__init__.py#L99

**Comment by martenson** [comment]
@ppouchin the validation in planemo is wrong too, fixing it right now
