### ISSUE TITLE
linting: Check tool_dependencies.xml consistent with requirement tags

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#90]
Check the tool/versions in any `tool_dependencies.xml` file and the individual tool's `<requirement>` tags are consistent (already done by the Tool Shed on upload)

**Comment by erasche** [comment]
*cough* XSDs+DTDs *cough*

**Comment by jmchilton** [comment]
In terms of log levels - how about:

* INFO: on each tool - number of matched and unmatched dependencies? (I don't think it should be a warning to have unmet requirements.)
* WARN: on tool_dependencies.xml if any of the packages are unused across all of repo's tools?

**Comment by jmchilton** [comment]
Closing in lieu of ``planemo lint --conda_requirements`` - hope that is okay.
