### ISSUE TITLE
update_test_data does not use subdirectories

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/planemo#901]
For larger tool suites I often use subdirectories in `test-data`. `--update_test_data` puts updated files into the main `test-data`

**Comment by bernt-matthias** [comment]
Hey @nsoranzo seems that I accidentally fixed this: https://github.com/galaxyproject/galaxy/pull/7372

Reason is here: 

https://github.com/galaxyproject/planemo/blob/eba1aa0af896889ea51aa4855d486b23214d18da/planemo/galaxy/test/actions.py#L98

which copies everything recursively from: `TEMPDIR/jobfiles` to `...../test-data`. 

Originally the `TEMPDIR/jobfiles` had seemingly no structure, hence the behavior addressed in this issue.

**Comment by bernt-matthias** [comment]
Should be solved by https://github.com/galaxyproject/galaxy/pull/7519 .. or @pvanheus ?

**Comment by pvanheus** [comment]
yes, so we can expect this to be fixed in the next Galaxy release

**Comment by bernt-matthias** [comment]
One could think about backporting .. then its fixed now :)

**Comment by pvanheus** [comment]
Ok I created #7627 on the 19.01 branch.

**Comment by pvanheus** [comment]
Which has now been merged so consider the fix backported (only 19.01 was
affected by this bug).

**Comment by bernt-matthias** [comment]
Thanks a lot.

**Comment by bernt-matthias** [comment]
Hey @nsoranzo . Since planemo seems to use Galaxy's master branch this seems not to work yet. How and when is the master branch updated?

**Comment by mvdbeek** [comment]
We manually merge forward, can do that later. We probably need to also need a new galaxy-lib release (this was affecting verify.py, right ?)

**Comment by bernt-matthias** [comment]
Exactly. Just to be sure here the traceback:

```
Traceback (most recent call last):
  File "/tmp/tmpo6HFPr/galaxy-dev/lib/galaxy/tools/verify/__init__.py", line 95, in verify
    shutil.copy(temp_name, ofn)
  File "/usr/lib/python2.7/shutil.py", line 133, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
```

**Comment by mvdbeek** [comment]
Alright, merged 19.01 into master if you want to give it a try

**Comment by bernt-matthias** [comment]
Wonderful. Seems to work.

**Comment by nsoranzo** [comment]
@bernt-matthias Also you can specify `--galaxy_branch` as an option to Planemo, which we always use for tools-iuc Travis tests.
