### ISSUE TITLE
planemo not working with Galaxy 18.09 and OSX?

### ISSUE THREAD

**Issue by mblue9** [galaxyproject/planemo#905]
Hello,

I can't get planemo to work with Galaxy 18.09 and OSX was wondering if anyone can help?

I tried what was suggested here: https://biostar.usegalaxy.org/p/30076/ but I'm just getting errors.

The `make client-production` first gave an error about needing yarn so installed that but then it gave the error:

```
make client-production
cd client && yarn install --network-timeout 120000 --check-files
yarn install v1.12.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @handsontable/vue@2.0.0-beta1" has incorrect peer dependency "handsontable@^0.38.1".
[4/4] 📃  Building fresh packages...
✨  Done in 329.07s.
cd client && yarn run build-production
yarn run v1.12.3
$ NODE_ENV=production gulp staging && concurrently "yarn run style" "yarn run webpack-production" "yarn run gulp clean && yarn run gulp-production" && yarn run save-build-hash
gulp[7851]: ../src/node_contextify.cc:627:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: 0x10003d0dc node::Abort() [/usr/local/Cellar/node/11.1.0/bin/node]
 2: 0x10003c107 node::AddEnvironmentCleanupHook(v8::Isolate*, void (*)(void*), void*) [/usr/local/Cellar/node/11.1.0/bin/node]
 3: 0x1000613c1 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/Cellar/node/11.1.0/bin/node]
 4: 0x1004e3e75 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/Cellar/node/11.1.0/bin/node]
 5: 0x1001f2f74 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/Cellar/node/11.1.0/bin/node]
 6: 0x1001f29f1 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/Cellar/node/11.1.0/bin/node]
 7: 0x218119c4fb7d 
/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/yarn--1545535570846-0.9608718390336966/node: line 3:  7851 Abort trap: 6           "/usr/local/Cellar/node/11.1.0/bin/node" "$@"
error Command failed with exit code 134.
```

The `pip install https://github.com/galaxyproject/planemo/archive/master.zip` method first gave an error:

`SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)`

Then I found this [suggestion](https://stackoverflow.com/questions/44316292/ssl-sslerror-tlsv1-alert-protocol-version) that said Mac has an old openssl so I updated openssl which apparently needs a python 3 so I also updated to python 3.7 and on trying to run planemo test I get:
```
.venv/lib/python3.7/site-packages/galaxy/tools/verify/interactor.py", line 268
    def stage_data_async(self, test_data, history_id, tool_id, async=True):
                                                                   ^
SyntaxError: invalid syntax
```

I know using a Mac makes things painful here but wondering if there's any way around this or am I out of luck? 

Any help appreciated.

**Comment by bgruening** [comment]
@dannon do you have an idea about the client side error?

**Comment by mvdbeek** [comment]
Hmm, the client error is strange because the build uses a globally installed node
```
/usr/local/Cellar/node/11.1.0/bin/node
```

We normally install a compatible node and yarn into the galaxy virtualenv -- if galaxy is using a virtualenv. I'm not 100% certain what happens with an activated conda environment on 18.09. On dev it will create a virtualenv anyway.

The python error has been fixed 3 months ago, this should be included with a recent checkout of 18.09. Old planemo had a problem upgrading to the last commit, this should normally have been fixed if you install planemo from the current master branch as you did(@jmchilton if you have some time a new release with https://github.com/galaxyproject/planemo/pull/895 would be great).

You might want to try again after removing ~/.planemo/gx_repo, this should at the very least resolve the syntax error issue.

**Comment by mblue9** [comment]
Thanks for the suggestions.  I had already tried deleting ~/.planemo/gx_repo (and now I don't have that folder, don't know if I should). Now I've tried:

```
virtualenv .venv --python=python3.7
. .venv/bin/activate
pip install https://github.com/galaxyproject/planemo/archive/master.zip
```
Then on running: `planemo t --galaxy_root ~/galaxy/galaxy .` I get that same async error again.

The galaxy I'm pointing to with `--galaxy_root ~/galaxy/galaxy ` is 18.09 on commit `65ca25e` from Dec 16th (says it's up-to-date) but if I try without the `--galaxy_root ~/galaxy/galaxy` I also get the same async error.

Should I try this without using the .venv?

**Comment by mvdbeek** [comment]
Ohh, I see. We need to also update galaxy-lib, this is actually planemo, not galaxy, that is failing here.
Short term fix would be `pip install https://github.com/galaxyproject/galaxy-lib/archive/master.zip` in the virtualenv in which planemo is running.

**Comment by mblue9** [comment]
Thanks a lot @mvdbeek! installing galaxy-lib seems to have fixed it 👍

**Comment by mvdbeek** [comment]
Yep, I think so, if we want to support python 3.7

**Comment by nsoranzo** [comment]
I've released galaxy-lib 18.9.2.

**Comment by dannon** [comment]
@bgruening Sorry I missed the ping, have been away on vacation.  But, yeah, as @mvdbeek mentions it's using an incompatible node version -- that said, folks shouldn't need to run these scripts as of 18.09, it should all be automatic on startup.  Looking at https://biostar.usegalaxy.org/p/30076/, I'm not sure how the client is involved in that (and thus, this) error, though?  Maybe I missed something.

**Comment by mblue9** [comment]
Closing this as I've now tested with just:

```
virtualenv .venv --python=python3.7
. .venv/bin/activate
pip install planemo
```

and planemo test and serve both work well again.

Thanks everyone!!
