### ISSUE TITLE
linting: Check reStructuredText markup in tool help tag

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#92]
Galaxy will sometimes show a syntax error in the rendered tool ``<help>`` tag, e.g.

https://github.com/peterjc/pico_galaxy/commit/2c379779a47d6a5bc5993af6833f36cb6117c0c0

It would be nice for planemo linting to extract the ``<help>`` tag (after macro processing) and run it though an RST markup parser (ideally the same one used in Galaxy) to spot any errors.

**Comment by jmchilton** [comment]
Planemo has done this since version 0.4.0 - https://github.com/galaxyproject/planemo/blob/master/HISTORY.rst#040-2015-02-16. Any clue if you were behind or if there is some inconsistency between Galaxy and Planemo?

**Comment by peterjc** [comment]
Confession: I'd not run planemo on that tool, and didn't check your feature log. You're several steps ahead of me here :)
