### ISSUE TITLE
planemo lint: empty citation tag is likely valid

### ISSUE THREAD

**Issue by stephanflemming** [galaxyproject/planemo#929]
An empty citation tag is "likely valid" with planemo lint, but planemo serve does not load that specific tool due tue a "NoneType object has no attribute strip" error

`<citation type="doi"></citation>`

**Comment by nsoranzo** [comment]
To close this we still need a new PyPI release of galaxy-lib including https://github.com/galaxyproject/galaxy-lib/pull/151 , followed by an update to the galaxy-lib pin in `requirements.txt` .

**Comment by nsoranzo** [comment]
Finally fully fixed on the `master` branch by depending on `galaxy-tool-util>=20.1.0.dev0` .
