### ISSUE TITLE
linting: Validate XML files before and after macro processing

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#93]
Usually I discover I've made an XML error (like failing to close a tag, or even a quote) when the tool fails to load in my development server (either for interactive testing, or more usually via ``run_tests.sh``).

Checking this in a planemo lint command would be useful.

**Comment by jmchilton** [comment]
This is what ``planemo lint`` does? It will definitely report XML problems.

```
% planemo l cat.xml
Error loading tool with path /home/john/workspace/planemo/project_templates/demo/cat.xml
Traceback (most recent call last):
  File "/home/john/workspace/planemo/.venv/local/lib/python2.7/site-packages/planemo-0.7.0.dev0-py2.7.egg/planemo_ext/galaxy/tools/loader_directory.py", line 29, in load_tool_elements_from_path
    tool_elements.append((file, loader.load_tool(file)))
ParseError: mismatched tag: line 19, column 8
```

See 3b4fade.

There is an open issue #31 for improving the output.

**Comment by peterjc** [comment]
OK, this seems to be covered - closing issue - thanks.
