### ISSUE TITLE
Add additional test output option - junit

### ISSUE THREAD

**Issue by selten** [galaxyproject/planemo#934]
I'd like to suggest junit test reports besides HTML, xUnit and JSON. 

The jUnit test report could then be consumed by other systems that, as of right now, do not support xUnit. 

Could probably be based on https://github.com/galaxyproject/planemo/pull/918

**Comment by selten** [comment]
I'll try to do this myself first

**Comment by mvdbeek** [comment]
Done with https://github.com/galaxyproject/planemo/pull/935, thanks a lot @selten!
