### ISSUE TITLE
Planemo test bug for missing input file

### ISSUE THREAD

**Issue by anilthanki** [galaxyproject/planemo#942]
Planemo test does not add a failed test in the report for missing input file with the following trace:
```

Traceback (most recent call last):
  File "/usr/users/ga002/thankia/.local/lib/python3.6/site-packages/planemo/test/results.py", line 115, in get_dict_value
    return data[key]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:
```

Let me know if you want full trace.

**Comment by mvdbeek** [comment]
thanks for the report, is there an easy way to reproduce this ?

**Comment by anilthanki** [comment]
Try to test a tool using planemo without input file and it should reproduce this.
