### ISSUE TITLE
Problem with test-data sub-directory inputs

### ISSUE THREAD

**Issue by Mataivic** [galaxyproject/planemo#947]
Hello,

I ran into a strange problem while running `planemo test `:

The tool command starts by creating symbolic links between the tmp/test_directory and my inputs test files within the wrapper `test-data` directory. When the inputs are in a sub-directory of `test-data`, it throws an error :

`ln: impossible de créer le lien symbolique 'sub_dir/file1.fasta': Aucun fichier ou dossier de ce type`

(Sorry for french, translation is : _the file 'sub_dir/file1.fasta' does not exist_).

if I run `planemo test` with the inputs directly in the test-data folder, it works ... Also, the tool has no trouble to find the outputs test data, which are also all in sub-directories.

The wrapper command is this :
```
<command>
    <![CDATA[
        #set $infiles = ""
        #for $input in $inputs
            ln -s '$input' '$input.element_identifier';
            #set $infiles = $infiles + $input.element_identifier + ","
        #end for
        #set $infiles = $infiles[:-1]

        python '$__tool_directory__/scripts/the_script.py'

        '$infiles'
        $param1
        $param2
        $aram3
        > ${log}
    ]]>
</command>
```

The test starts like this :
```
<test>
    <param name="inputs" ftype="fasta" value="sub_dir/file1.fasta,sub_dir/file2.fasta,sub_dir/file3.fasta" />
    ...
</test>
```

This might be easy to solve but I haven't been involved in a Galaxy project for a few months, I lost the habit :/ (and it worked fine before so i don't really understand what is happening).

The only clue I have may be my working environment : I made it quick (so maybe I did something dirty), and I just used `pip install planemo` within a conda environment where I already have all the needed dependencies for the tools I'm working on.

Thanks.

**Comment by bernt-matthias** [comment]
I also just wanted to report this error. It happened before and I thought it was solved (I try to find the PR). 

Maybe something went wrong with Galaxy's master branch which is used by planemo.

**Comment by bernt-matthias** [comment]
As additional note: the actual problem is that `$input.element_identifier` contains the path component ie it is `sub_dir/file1.fasta` instead of just `file1.fasta` (it should be the later).

**Comment by abretaud** [comment]
I had the same problem at some point, not sure but I think running planemo with `--galaxy_branch release_19.05` helped

**Comment by bernt-matthias** [comment]
found the PR: https://github.com/galaxyproject/galaxy/pull/8162 ... the commit has been backported to 19.05 .. unfortunately the master branch (which is used by planemo) does not include it yet. 

I asked on the dev gitter channel if someone could do an update.

**Comment by bernt-matthias** [comment]
Should work now https://github.com/galaxyproject/galaxy/pull/8408. Can you test?

**Comment by Mataivic** [comment]
@bernt-matthias Yes it works now :). Thanks !
