### ISSUE TITLE
Move `when` lints from warning to error

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/planemo#949]
In https://github.com/galaxyproject/tools-iuc/pull/2523 we discussed to raise an error if we lint `when`s in a conditional.

**Comment by jmchilton** [comment]
This seems backwards to me, instead of making specific warnings errors... the goal should be eliminating warnings from the tools in tools-iuc so we can fail the repo (or subsets of the repo) on warnings. This isn't an error condition right - the tool can work.

**Comment by nsoranzo** [comment]
> This isn't an error condition right - the tool can work.

I agree that keeping this is a warning is fine, it is very useful to debug issues like typos in conditionals but not mandatory outside IUC best practises. 

On the other hand, I doubt we will be able to fail linting on warnings, for certain tools fixing some warning may not make sense (e.g. "Tool id contains a space - this is discouraged." for tools that are already published on the ToolShed, like all `emboss_5` tools).
