### ISSUE TITLE
linting: Check referenced test input/output files are in test-data/

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/planemo#95]
I have from time to time uploaded a Galaxy tool to the Tool Shed only to have the tests fail for the trivial reason that I forgot to include a new test file. Planemo should help here (less chance of missing the file in the Tool Shed upload), but it would still be nice for a Planemo lint command to check all the references test files exist under ``test-data/``.

**Comment by jmchilton** [comment]
Good idea. Closing as duplicated with a TODO item on https://github.com/galaxyproject/planemo/issues/13. Is that okay?

**Comment by peterjc** [comment]
If you prefer combining related issues into one with a checklists, let's do that - sure.
