### ISSUE TITLE
Naming tests

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/planemo#954]
(moved from https://github.com/galaxyproject/galaxy/issues/8550)
Currently, when testing tools, the output for planemo test looks like:
```
tool_id[0]: passed
tool_id[1]: passed
tool_id[2]: passed
tool_id[3]: failed
tool_id[4]: passed
```
When many tests are run, however, it can be difficult to remember what the difference in each of those were. I propose adding a name variable for tests themselves in the format:
```
<tests>
    <test name="Test 1 specific flags/values/etc"/>
</tests>
```

allowing for the planemo test output:
```
tool_id[Test 1 specific flags/values/ect]: passed/failed
```
in order to allow anyone wrapping tools to debug more easily.

**Comment by bernt-matthias** [comment]
Hey @astrovsky01. Could be really useful. I was always a bit annoyed by the inconsistent numbering. I sometimes tests were indexed starting from 0 sometimes from 1.
