### ISSUE TITLE
publishing to toolshed breaks

### ISSUE THREAD

**Issue by jkanche** [galaxyproject/planemo#956]
Hello,

I am trrying to publish my tool to both toolshed and testtoolshed, but planemo fails 

> ('Connection broken: IncompleteRead(5871 bytes read, 283 more expected)', IncompleteRead(5871 bytes read, 283 more expected))

Is there a fix for this ?

**Comment by martenson** [comment]
@jkanche thanks for the report, we are looking into it

**Comment by jkanche** [comment]
with the testoolshed, I am atleast able to create the repository but not able to push the files

and everything fails on toolshed

**Comment by martenson** [comment]
I think we have remedied the situation, could you please retest from your side? @jkanche
