### ISSUE TITLE
[docs] broken link

### ISSUE THREAD

**Issue by martin-raden** [galaxyproject/planemo#962]
found a broken wiki link 

 https://wiki.galaxyproject.org/Histories#Dataset_Collections

in

 https://github.com/galaxyproject/planemo/blob/master/docs/_writing_collections.rst

but dont know how to fix...

**Comment by nsoranzo** [comment]
I'd replace it with https://galaxyproject.org/tutorials/collections/ . Also, I'd remove " on the Galaxy Wiki", it's now called the "Galaxy Community Hub" and it makes more sense to me to add the link to "creating and managing collections".

**Comment by martin-raden** [comment]
:+1:

**Comment by martin-raden** [comment]
you or me? :smile:

**Comment by nsoranzo** [comment]
Fixed by #963.
