### ISSUE TITLE
Typo for "Building a Galaxy Tool" tutorial

### ISSUE THREAD

**Issue by apetkau** [galaxyproject/planemo#97]
I was following through the [Building a Galaxy Tool](https://planemo.readthedocs.org/en/latest/writing.html) tutorial and near the bottom it says to run `planemo --galaxy_root=/path/to/galaxy t` and `planemo --galaxy_root=/path/to/galaxy s`, but I think these should be `planemo t --galaxy_root=/path/to/galaxy` and `planemo s --galaxy_root=/path/to/galaxy` (command at the begining).

Thanks for the awesome tool and documentation though.  Looks really easy to use.

**Comment by martenson** [comment]
thanks for the heads up @apetkau ! 
I like planemo too! Thanks @jmchilton  :)

**Comment by apetkau** [comment]
Awesome, thanks for fixing it so quickly :).
