### ISSUE TITLE
Can't install via pip. Dependency chain issue.

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/planemo#987]
Python 3.8
Currently the pip installation of planemo is broken due to the _ast module changing.

https://bugzilla.redhat.com/show_bug.cgi?id=1714177#c1

This is fixed in a more recent version of ruamel.yaml but the package pins the dependency to `ruamel.yaml<=0.15.51,>=0.12.4`

**Comment by nsoranzo** [comment]
That's already fixed in the master branch, we need to merge a couple of outstanding PRs and make a new release on PyPI.

**Comment by innovate-invent** [comment]
I tried the master branch, the only wait I could get it to install was:
```
python -m pip install --upgrade pip setuptools wheel 'galaxy-tool-util==19.9.1' 'git+git://github.com/galaxyproject/planemo.git@4e52478d93cf2f4bf37c87ec1ce2de7290c8e795'
```

**Comment by nsoranzo** [comment]
`pip install git+https://github.com/galaxyproject/planemo@master` in a Python 3.8 virtualenv works fine for me.
Only minor issue is that it installs `galaxy-util` 19.9.0 instead of 20.1.0.dev0, but that's because of https://github.com/pypa/pip/issues/988 .
